[[ats_collections_rc-md-success]]
[abstract_test]
====
[%metadata]
identifier:: /conf/collections/rc-md-success
target:: /req/collections/rc-md-success
target:: /req/collections/rc-md-links
target:: /req/collections/rc-md-items
test-purpose:: Validate that the Collections content complies with the required structure and contents.
test-method:: 
+
--
. Validate that the response document complies with <<ats_collections_rc-md-links,/conf/collections/rc-md-links>>
. Validate that the response document complies with <<ats_collections_rc-md-items,/conf/collections/rc-md-items>>
. Validate the Collections resource for all supported media types using the resources and tests identified in <<collections-metadata-schema>>
--
====

The Collections content may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate against that schema. All supported formats should be exercised.

[#collections-metadata-schema,reftext='{table-caption} {counter:table-num}']
.Schema and Tests for Collections content
[width="90%",cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collections.json[collections.json]|<<ats_html_content,/conf/html/content>>
|JSON |link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collections.json[collections.json] |<<ats_json_content,/conf/json/content>>
|===
