[[ats_collections_description-success]]
[abstract_test]
====
[%metadata]
identifier:: /conf/collections/description-success
target:: /req/collections/description-success
test-purpose:: Validate that a Collection document complies with the required structure, contents and values.
test-method::
+
--
For each Collection description (`/collections/{collectionId}`) resource, validate:

. That the Collection description resource includes an `id` property.
. Validate the content of the Collection resource for all supported media types using the resources and tests identified in <<collection-metadata-schema>>
. Verify that the content of the response is consistent with the content for the corresponding collection in the response to the `/collections` resource. That is, the values for `id`, `title`, `description` and `extent` are identical.
--
====

The Collection description content may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate against that schema.
All supported formats should be exercised.

[#collection-metadata-schema,reftext='{table-caption} {counter:table-num}']
.Schema and Tests for Collection content
[width="90%",cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML | link:https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml[collectionDesc.yaml]|<<ats_html_content,/conf/html/content>>
|JSON | link:https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml[collectionDesc.yaml]|<<ats_json_content,/conf/json/content>>
|===
