== Requirements Class Subset

The Subset Requirements Class defines parameters for sub-setting a geospatial resource. Subsetting parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_subset.adoc[]

The subset parameter is defined in the following Requirement:

include::requirements/coverage-subset/REQ_cov-subset-definition.adoc[]

The following permission is granted to facilitate slicing data sparsely populated across a dimension, such as Earth Observation imagery:

include::recommendations/coverage-subset/PER_subset-slice-sparse-dimensions.adoc[]

The results of using a subset parameter are defined by the following Requirement:

include::requirements/coverage-subset/REQ_cov-subset-success.adoc[]

=== Subsetting Examples

include::examples/examples_subsetting.adoc[]

== Requirements Class Scaling

The Scaling Requirements Class defines parameters for retrieving data from n-dimensional Range Sets at a resolution different than the original. Scaling parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_scaling.adoc[]

The scaling parameters are defined in the following Requirement:

include::requirements/coverage-scaling/REQ_cov-scaling-definition.adoc[]

The results of using a scaling parameter are defined by the following Requirement:

include::requirements/coverage-scaling/REQ_cov-scaling-success.adoc[]

=== Scaling Examples

include::examples/examples_scaling.adoc[]

== Requirements Class Coverage Range Subset

The Range Subset Requirements Class defines parameters for selecting a subset of the bands (defined in the Range Type) to retrieve from Range Sets.
Range subsetting parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_rangesubset.adoc[]

The range-subset parameter is defined in the following Requirement:

include::requirements/coverage-rangesubset/REQ_cov-rangesubset-definition.adoc[]

The results of using a range-subset parameter are defined by the following Requirement:

include::requirements/coverage-rangesubset/REQ_cov-rangesubset-success.adoc[]

=== Range Subsetting Examples

include::examples/examples_rangesubsetting.adoc[]

== Requirements Class DomainSet Subset

The DomainSet Subset Requirements Class defines the use of parameters for sub-setting the domainset of the coverage.

include::requirements/requirements_class_domainset_subset.adoc[]

The subset parameter is defined in the following Requirement:

include::requirements/domainset-subset/REQ_cov-subset-definition.adoc[]

The results of using a subset parameter are defined by the following Requirement:

include::requirements/domainset-subset/REQ_cov-subset-success.adoc[]

=== DomainSet Subsetting Examples

include::examples/examples_domainset_subsetting.adoc[]
