[[rc-encoding-section]]
== Requirements Classes for Encodings

=== Overview

This clause specifies two requirements classes for encodings to be used with the <<collections-list,Collections>> and <<collection-description,Collection>> resources.
These encodings are common representations for accessing spatial data on the web:

* <<rc-html-section,HTML>>
* <<rc-json-section,JSON>>

Neither of these encodings is mandatory. An implementation of the <<rc-collections-section,Collections>> requirements class may implement either, both, or neither of them.

[[rc-html-section]]
=== Requirements Class "HTML"

Best practices for sharing geospatial data on the Web (<<SDWBP,W3C Best Practice>>) recommend supporting an HTML representation of API resources.
For consistency with the Web, this should be done in a way that enables users and search engines to access all of the data they are authorized to access.

Providing an HTML representation for the landing page of a dataset, for listing available collections, and for describing detailed metadata about a particular collection
allows users, using only their Web browser as a client, to evaluate the usefulness of data available from the API deployment before proceeding to access this data.

Additionally, an HTML represention of resources facilitate information discovery from Web search engines.

The HTML encoding should present all of the same information available in other representations such as the machine-readable JSON,
so that users see this information in their browser in a way that naturally blends in with the rest of the institutional site,
and ideally following https://www.w3.org/TR/WCAG21/[Web Content Accessibility Guidelines].

Links that correspond to the _Link_ class from the UML class diagram will be included as `<a/>` elements within the HTML `<body/>`, and could also be returned as HTTP response `Link:` headers.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[rc-json-section]]
=== Requirements Class "JSON"

JSON is a text syntax that facilitates structured data interchange between programming languages. JSON is commonly used for Web-based software-to-software interchanges. Most Web developers are comfortable with using a JSON-based format, so supporting JSON is recommended for machine-to-machine interactions.

include::requirements/requirements_class_json.adoc[]

include::requirements/json/REQ_definition.adoc[]

include::requirements/json/REQ_content.adoc[]

JSON Schema for the Collections and Collection responses are available at https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collections.yaml[collections.yaml] and https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml[collectionDesc.yaml].

These are generic schemas that do not include any application schema information about specific resource types or their properties.
