[[rc_collections-section]]
== Requirements Class "Collections"
:sectnums:

include::requirements/requirements_class_collections.adoc[]

This Requirements Class describes the resources and operations used to discover and query resource collections exposed thorugh an OGC Web API. It does not include any requirements about how the resources are aggregated into collections. That detail is reserved for resource-specific OGC Web API standards.

The three resources defined in this Requirements Class are summarized in <<collection-resources>>. Detailed requirements for each of these resources are provided in the <<collection-resource-requirements,Resource Requirements>> section.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,20",options="header"]
|===
^|Path Fragment ^|Name ^|Description
|/collections |Collections Metadata |Information which describes the set of suppoprted Collections
|/collections/{collectionId} |Collection Information |Information about a specific Collection
|/collections/{collectionId}/items |Collection Resource |The resources in a specific Collection
|===

This Requirements Class also describes the operations which can be performed on these resources. Requirements for these operations are included with their associated resource descriptions in the <<collection-resource-requirements,Resource Requirements>> section. Three parameters are also defined for use in these operations. These parameters are defined in the <<parameter-requirements,Parameter Requirements>> section. A summary of the parameters is provided in <<parameter-summary>>.

[#parameter-summary,reftext='{table-caption} {counter:table-num}']
.Parameter Summary
[width="90%",cols="10,10,60",options="header"]
|===
^|Parameter Name ^|Target ^|Description
|Bounding Box |Extent |Selects resources which have an Extent element that intersects the bounding box
|Date-Time|Extent |Selects resources which have an Extent element that intersects the specified time period
|Limit |The result set |Limits the number of resources which can be returned in one response
|===

Finally, requirements which have general applicablity are provided in the <<general-requirements,General Requirements>> section.

[[collection-resource-requirements]]
=== Resource Requirements

This section expresses the requirements for resources and operations used to discover and query resource collections.

[[collections-metadata]]
==== Collections Metadata

OGC APIs typically organize their Spatial Resources into collections. Information about those collections is accessed through the /collections path.

===== Operation

include::requirements/collections/REQ_rc-md-op.adoc[]

===== Parameters

The following query parameters can be used with this operation:

* <<boundingbox-parameter-requirements,Bounding Box>>
* <<datetime-parameter-requirements,Date Time>>
* <<limit-parameter-requirements,Limit>>

===== Response

include::requirements/collections/REQ_rc-md-success.adoc[]

The collections metadata returned by this operation is based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/April-2020-Updates/collections/openapi/schemas/collections.json[collections.json] JSON schema. Examples of collections metadata are provided in <<collections-metadata-examples>>.

.collections.json
[source, JSON]
include::openapi/schemas/collections.json[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-descriptions.adoc[]

The `collections` property of the Collections Metadata provides a description of each collection. These descriptions are based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/April-2020-Updates/collections/openapi/schemas/collectionInfo.json[Collection Information Schema]. This schema is described in detail in the <<collection-information, Collection Information>> section of this Standard. The following requirements and recommendations govern the use of Collection Information in the Collections Metadata.

include::requirements/collections/REQ_rc-md-items.adoc[]

The `timeStamp` of when the response was generated

include::requirements/collections/REQ_rc-timeStamp.adoc[]

The `numberMatched` property of the Collections Metadata

include::requirements/collections/REQ_rc-numberMatched.adoc[]

The `numberReturned` property of the Collections Metadata

include::requirements/collections/REQ_rc-numberReturned.adoc[]

The Collections Metadata should describe all of the collections accessible through the API. However, in some cases that is impractical. As long as they provide a way to retrieve the remaining metadata as well, developers have an option to only return a subset.

include::recommendations/collections/PER_rc-md-items.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[collection-information]]
==== Collection Information

Each resource collection is described by a set of metadata. That metadata is accessed directly using the `/collections/{collectionId}` path or as an entry in the `collections` property of the Collections Metadata resource.

===== Operation

include::requirements/collections/REQ_src-md-op.adoc[]

===== Parameters

No parameters have been standardized for this operation.

===== Response

include::requirements/collections/REQ_src-md-success.adoc[]

Collection Information is based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/April-2020-Updates/collections/openapi/schemas/collectionInfo.json[Collection Information Schema]. Examples of Collection Information are provided in <<collection-information-examples>>.

.Collection Information Schema
[source, JSON]
include::openapi/schemas/collectionInfo.json[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-items-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-items-descriptions.adoc[]

Additional requirements and recommendations apply to the `extent` property of the Collection Information.

include::requirements/collections/REQ_rc-md-extent.adoc[]

include::recommendations/collections/REC_rc-md-extent-single.adoc[]

include::recommendations/collections/PER_rc-md-extent-extensions.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collection-resource]]
==== Collection Resource

A collection resource is the content of the collection as opposed to metadata about that collection. This standard defines the general behavior of this operation, but detailed requirements are the purview of the API standard for that resource type.

===== Operation

include::requirements/collections/REQ_rc-op.adoc[]

===== Parameters

The following query parameters can be used with this operation:

* <<boundingbox-parameter-requirements,Bounding Box>>
* <<datetime-parameter-requirements,Date Time>>
* <<limit-parameter-requirements,Limit>>

[width="90%",cols="2,6a"]
|===
|Note: |Since the type of resource which makes up the collection is not defined, the behavior of these parameters must be tailored to the structure and information content of specific resource types. That tailoring will take place in resource-specific OGC API standards.
|===

===== Response

include::requirements/collections/REQ_rc-response.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[parameter-requirements]]
=== Parameter Requirements

Query parameters are used in URLs to limit the resources which are returned on a GET request. The OGC API - Common - Part 2: Collections Standard defines three query parameters for use in OGC API standards:

* <<bbox-parameter-requirements,bbox>>: Bounding Box
* <<parameter-datetime-requirements,datetime>>: Date and Time
* <<limit-parameter-requirements,limit>>: Response resource count limit

Use of these query parameters with any specific operation is optional. Developers of API-Collections servers should include supported parameters in the API definition as describe in <<apicore,API-Core>>.

OGC API servers are subject to the following requirements when handling query parameters.

* If a parameter *is* included in the API definition:

include::requirements/core/REQ_query-param-known.adoc[]

* If a parameter *is not* included in the API definition:

include::requirements/core/REQ_query-param-unknown.adoc[]

* Query parameters will be validated:

include::requirements/core/REQ_query-param-invalid.adoc[]

[[bbox-parameter-requirements]]
==== Parameter bbox

include::requirements/collections/REQ_rc-bbox-definition.adoc[]

include::requirements/collections/REQ_rc-bbox-response.adoc[]

"Intersects" means that a coordinate that is part of the spatial geometry of the resource falls within the rectangular area specified in the parameter `bbox`. This includes the boundaries of the geometries. For curves the boundary includes the start and end position. For surfaces the boundary includes the outer and inner rings.

In case of a degenerated bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all resources match where the geometry intersects with this point.

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a later version of this standard.

For WGS 84 longitude/latitude the bounding box is in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian (180th meridian) the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

Note that the server will return an error if a latitude value of ``160.0`` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/April-2020-Updates/collections/openapi/parameters/bbox.yaml[bbox.yaml].

[[datetime-parameter-requirements]]
==== Parameter datetime

include::requirements/collections/REQ_rc-time-definition.adoc[]

include::requirements/collections/REQ_rc-time-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`time=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate`), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/April-2020-Updates/collections/openapi/parameters/datetime.yaml[datetime.yaml].

[[limit-parameter-requirements]]
==== Parameter limit

The `limit` parameter limits the number of resources that can be returned in a single response.

include::requirements/collections/REQ_rc-limit-definition.adoc[[]

The number of resources returned depends on the server and the value of the `limit` parameter.

*   The client can request a limit to the number of resources returned.
*   The server may have a default value for the limit, and a maximum limit.
*   If the server has any more results available than it returns (the number it returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

include::requirements/collections/REQ_rc-limit-response.adoc[]

The effect of the limit parameter is to divide the response into a number of pages. Each page (except for the last) contains the specified number of entities. The response contains the first `page`. Additional pages can be accessed through hyperlink navigation.

include::recommendations/collections/REC_rc-next-1.adoc[]

include::recommendations/collections/REC_rc-next-2.adoc[]

include::recommendations/collections/REC_rc-next-3.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::recommendations/collections/PER_rc-prev.adoc[]

[[general-requirements]]
=== General Requirements

The following general requirements and recommendations apply to all OGC APIs which implement the API-Common Collections conformance class.

[[http_status_codes]]
==== HTTP status codes

This API standard does not impose any restrictions on which features of the HTTP and HTTPS protocols may be used. API clients should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 400, and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`304` |An <<web_caching,entity tag was provided in the request>> and the resource has not been changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfil it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/core/PER_additional-status-codes.adoc[]

==== Coordinate Reference Systems (CRS)

As discussed in Chapter 9 of the W3C/OGC Spatial Data on the Web (SDW) <<SDWBP,Best Practices document>>, how to express and share the location of resources in a consistent way is one of the most fundamental aspects of publishing geographic data. Therefore, clearly stating the CRS rules for the coordinates is very important.

For the reasons discussed in the SDW Best Practice, OGC APIs use WGS84 longitude and latitude as the default CRS.

include::requirements/core/REQ_crs84.adoc[]

The implementations compliant with API-Collections are not required to support publishing geometries in CRS other than http://www.opengis.net/def/crs/OGC/1.3/CRS84. API-Collections also does not specify a capability to request geometries in a different CRS than the native one of the published resource. Such a capability will be specified in other OGC API standards.
