[[rc-collections-section]]
== Requirements Class "Collections"
include::requirements/requirements_class_collections.adoc[]

The Collections Requirements Class consistently describes across the OGC API Standards suite the resources and operations used to list and describe geospatial collection resources exposed through a deployed Web API.
This class neither specifies how to organize your data into collections nor how to provide access to the data described in the collections.
That level of detail is reserved for OGC Web API Standards that define access mechanisms through specific resources (see <<access-mechanisms,Access mechanisms Section>>).

include::recommendations/collections/REC_collections-part1-landing-page.adoc[]

The two resources defined by this Requirements Class are summarized in <<collection-resources>> and their operations are defined in the following requirements.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<collections-list,List of Collections>> |/collections ^|GET |List of available Collections including some descriptions of each one
|<<collection-description,Collection description>> |/collections/{collectionId} ^|GET |Description about a specific collection of geospatial data with links to distribution
|===

[[collections-list]]
=== List of Collections Resource (`/collections`)

Implementations of OGC API Standards typically enable deployers to organize their geospatial data into collections.
Information about those collections is accessed through the `/collections` path, which is linked to using the https://www.opengis.net/def/rel/ogc/1.0/data link relation
(or simply `data` for compatibility with OGC API - Features).

==== Operation

include::requirements/collections/REQ_collections-collections-list-op.adoc[]

==== Response

include::requirements/collections/REQ_collections-collections-list-success.adoc[]

The collections response returned by this operation is based on the link:https://github.com/opengeospatial/ogcapi-common/tree/master/collections/openapi/schemas/common-geodata/collections.yaml[collections.yaml] JSON schema.
An example of a response listing collections are provided in <<collections-list-examples>>.

// #TODO: Update to schemas.opengis.net for publication#

// .collections.yaml
// [source, YAML]
// include::openapi/schemas/common-geodata/collections.yaml[]

This Collections schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_collections-collections-list-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_collections-collections-list-describedby.adoc[]

The `collections` property of the Collections response provides a description of each individual collection distributed by the Web API deployment.

include::requirements/collections/REQ_collections-collections-list-collections.adoc[]

The array items included in the `collection` property are described in the <<collection-description,Collection Resource>> section of the Collections Requirements Class.

The Collections Requirements Class does not define any parameters for use against a `collections` resource.

Implementers who plan supporting the offering of large numbers of collections from the same API endpoint may consider extending
their API implementations with capabilities defined in the OGC API - Records Standard (with collections acting as the local resources of a local resource catalog),
as well as candidate extensions to the OGC API - Common Standard that introduce capabilities for hierarchical collections, searching, filtering, and sorting collections.

[[collections-list-examples]]
===== Collections Response Example

The following JSON example response lists available collections for a dataset with a single "buildings" feature collection.

There is a link to the resource listing collections itself (link relation type: `self`).

Representations of this resource in other formats are referenced (link relation type: `alternate`).

An additional link is to the logical schema of the collection (link relation type: `[ogc-rel:schema]`).

The reference systems for describing the spatiotemporal extent do not need to be specified, as they default to [OGC:CRS84] and Gregorian calendar / Coordinated Universal Time (UTC).
This spatiotemporal extent always needs to be specified (or default) this way for data referenced to Earth and a time scale for which the Gregorian calendar is suitable.
For the spatial extent, the `crs` specified in the `spatial` property of the extent only describes the CRS of the `bbox` and is independent of the native / storage reference system of the data itself,
which can be specified separately in the `storageCrs` property.
For explicitly specifying the Gregorian calendar, the URI https://www.opengis.net/def/crs/OGC/0/GregorianDateTime can be used, or alternatively
https://www.opengis.net/def/uom/ISO-8601/0/Gregorian for compatibility with OGC API - Features.

.Example `/collections` response listing collections
[source,json]
----
include::examples/collections_list.json[]
----

==== Error situations

See https://docs.ogc.org/is/19-072/19-072.html#http-status-codes[OGC API - Common - Part 1: Core Section 8.2 "HTTP Status Codes"] for general guidance.

[[collection-description]]
=== Collection Description Resource (`/collections/{collectionId}`)

Each resource collection is described by a set of metadata. That metadata can be accessed directly using the `/collections/{collectionId}` path and as an entry in the `collections` property of the `/collections` resource.

==== Operation

include::requirements/collections/REQ_collections-description-op.adoc[]

[[collection-resource-definition-section]]
==== Response

include::requirements/collections/REQ_collections-description-success.adoc[]

// #TODO: Update to schemas.opengis.net for publication#

The collection description response returned by this operation is based on the https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml[collectionDesc.yaml] JSON schema.

An example of a response describing a collection are provided in <<collection-description-examples>>.

// .Collection Resource Schema
// [source, YAML]
// include::openapi/schemas/common-geodata/collectionDesc.yaml[]

Most of the properties of the Collection resource are self-explanatory. However, a few properties require additional explanation.

[[collection-attribution-section]]
===== Attribution

A collection description can include an `attribution` property allowing clients to display a short attribution for data being visualized.
For example, this is often shown at the bottom of a map in a 2D interface.
This attribution, providing a way to identify the source of the geographic information, can contain markup text whose format may be indicated in the `attributionMediaType` property. That format can be either plain text (`text/plain`), HTML (`text/html`) or https://commonmark.org/[CommonMark] (`text/markdown`).
If the 'attributionMediaType' indicates something other than `text/plain`, the `attribution` element string should be interpreted by a markup parser selected based on that media type to be presented to the user
(e.g., `text/markdown` will be parsed by a library supporting CommonMark). By allowing markup, the attribution string can import images (e.g., organization logos) and format the text (e.g., the name of the organization in italics).
See the example <<collection-description-examples,collection response>> for an example of the use of markup in the attribution element.

Note that in order to support attribution in different languages, a server may take into consideration the `Accept-Language:` request header, for example
a client would make a request specifying `Accept-Language: fr,en;q=0.8` to prioritize a French representation, but fall back to English if a French representation is not available.
This language negotiation mechanism is part of the HTTP standard and affects all resources, and the language of all properties inside these.
For example, in a collection description, this language negotiation will apply to titles, descriptions, keywords, links, etc. (not only the `attribution`).

The following IANA link relations can also be considered to link (using the `links` property -- see <<collection-links-section>>) to resources providing additional information regarding the
origin, ownership, funding and restrictions associated with the data: `about`, `author`, `copyright`, `cite-as`, `sponsored`, `disclosure`, `license`, `terms-of-service`.

[[collection-item-type-section]]
===== Item Type

In some collections of geospatial data, the members (`items`) that make up that collection can be individually accessed by a client. In this case, the `itemType` property in the Collection resource identifies the type of the `items` accessible from that collection.

include::recommendations/collections/REC_collections-description-item-type.adoc[]

[[collection-links-section]]
===== Links

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_collections-description-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_collections-collection-describedby.adoc[]

The `http://www.opengis.net/def/rel/ogc/1.0/schema` link relation should be used to reference a logical schema (see OGC API - Common - Part 3: Schemas).

[[collection-extent-section]]
===== Extent

The extent property defines a spatiotemporal envelope that encompasses the geospatial data in the collection. Since not all collections are nicely clustered around a single place in space and time, the extent property provides flexibility in how that surface can be defined.

* The Spatial bounding boxes (`bbox`, and optionally `storageCrsBbox`) provide a set of rectangular bounding boxes which use coordinates to envelope portions of the collection. Typically only the first element would be populated. Additional boxes may be useful, for example, when the collection is clustered in multiple, widely separated locations.
* Temporal Interval provides a set of temporal periods. Typically only the first temporal period would be populated. However, like `bbox`, additional periods can be added if the collection does not form a single temporal cluster.

The temporal reference system (`trs`) specified in the `temporal` property of the `extent` defines not only the reference system of the `interval`,
but also the reference system for the primary temporal dimension of the data.

For the spatial extent, the `crs` specified in the `spatial` property of the `extent` defines only the coordinate reference system of the `bbox`.
For data referenced to Earth, this `crs` will always be [OGC:CRS84] or [OGC:CRS84h].
The native CRS of the data is specified separately in the `storageCrs` property of the collection description.
For some access mechanisms, this native CRS corresponds to the default output CRS.
These access mechanisms may additionally support other output CRSs which are specified in the `crs` property of the collection description.

For the `storageCrs` as well as for the `crs` list of supported output CRSs, implementors of Web APIs based on OGC API standards are strongly recommended to reference existing CRS definitions in the form of URIs
(or the equivalent CURIEs) such as the ones provided by the https://epsg.org/[EPSG Geodetic Parameter Dataset]. However, there are situations where the required CRS has not been registered with an authority.

For these cases, where a URI does not exist, a http://www.opengis.net/doc/is/wkt-crs/2.0[Well-Known Text] string describing the coordinate reference system,
or a JSON object encoding of the CRS (using the https://proj.org/en/stable/specifications/projjson.html[PROJJSON] schema or a potential "CRS JSON" successor if eventually standardized by the OGC) can be specified.

Such alternate CRS definitions can also be used for the `crs` of the `bbox` for data in an engineering CRS or otherwise not georeferenced to Earth.

In the following example, the native CRS of the data is in the Mercator CRS (EPSG:3395).
The data is referenced to Earth, therefore the bounding box for discovery purpose needs to be specified in OGC:CRS84.
The CRSs available for output (which the client could potentially select using a `crs` query parameter defined by the access mechanism) include both EPSG:3395 and OGC:CRS84.

.Example illustrating the CRS-related properties of the collection description
[source,json]
----
"extent":
{
   "spatial": {
      "crs": "[OGC:CRS84]",
      "bbox": [ -180, -85.0840590500295, 180, 85.0840590500295 ],
      "storageCrsBbox": [ -20037508.342789, -20037508.342684, 20037508.342789, 20037508.342684 ]
   }
},
"storageCrs": "[EPSG:3395]",
"crs": [ "[EPSG:3395]", "[OGC:CRS84]" ]
----

WARNING: While some OGC API Standards explicitly support the use of CURIEs for properties of the collection description such as `storageCrs` and the `crs` array of supported output CRSs, other
OGC API Standards do not. For servers implementing those OGC API Standards that do not allow the use of CURIEs, full URIs therefore need to be used.

// TODO: Create a recommendation to reference existing CRS definitions for `crs` and `storageCrs`

include::requirements/collections/REQ_collections-description-extent.adoc[]

include::requirements/collections/REQ_collections-description-extent-multi.adoc[]

include::recommendations/collections/REC_collections-description-extent-single.adoc[]

include::recommendations/collections/PER_collections-description-extent-extensions.adoc[]

include::recommendations/collections/REC_collections-description-storage-crs-bbox.adoc[]

include::recommendations/collections/PER_collections-description-reference-systems.adoc[]

[[collection-description-examples]]
===== Collection Object Examples

This Collection Description example response in JSON is for a single "buildings" collection.

The basic descriptive information includes:

* "id": an identifier for this collection
* "title": human-readable title for this collection
* "description": longer text describing this collection
* "attribution": markup providing attribution (owner, producer, logo, etc.) of this collection

The response includes links to:

* the response itself (link relation type: `self`),
* representations of this response in other formats are referenced using (link relation type: `alternate`),
* an additional link is to a logical schema for the collection (link relation type: `[ogc-rel:schema]`).

Finally, this response includes both spatial and temporal extents.

The reference systems for describing the spatiotemporal extent do not need to be specified, as they default to [OGC:CRS84] (longitude, latitude) and Gregorian calendar / Coordinated Universal Time (UTC)
and should always be specified (or default) this way for data referenced to Earth and a time scale for which the Gregorian calendar is suitable.
For the spatial extent, the `crs` specified in the `spatial` property of the extent only describes the CRS of the `bbox` and is independent of the native / storage reference system of the data itself,
which can be specified separately in the `storageCrs` property.
For explicitly specifying the Gregorian calendar, the URI https://www.opengis.net/def/crs/OGC/0/GregorianDateTime can be used, or alternatively
https://www.opengis.net/def/uom/ISO-8601/0/Gregorian for compatibility with OGC API - Features.

.Example `/collections/{collectionId}` response describing a collections
[source,json]
----
include::examples/collection_description.json[]
----

[[collection-conformance]]
===== Collection-specific conformance declaration

A client might be able to guess, from the API-wide conformance declaration, which conformance classes are applicable specifically to a particular collection
based on the data access mechanism(s) present within the links.
For instance, if the collection links to a coverage endpoint, the client can guess that the Coverages conformance classes are applicable, while the Features classes are not.
However, this may not be precise enough, for example in the case of scaling or subsetting being supported by one collection, but not by another.
This permission suggests a way to declare the exact list of conformance classes that are applicable specifically to a particular collection.

include::recommendations/collections/PER_collections-conformance.adoc[]

==== Error Situations

See https://docs.ogc.org/is/19-072/19-072.html#http-status-codes[OGC API - Common - Part 1: Core Section 8.2 "HTTP Status Codes"] for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404`.

[[collections-api-records]]
=== OGC API - Records compliance

When implementing the "Collections" requirement class, the `/collections` end-point can be considered a _Local Resource Catalog_, where the local resources are the collections being cataloged.

This requirement class is consistent with the requirements of https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog[OGC API - Records - Part 1: Core "Local Resources Catalog" (Deployment)].
An implementation may gain additional interoperability by conforming to that requirement class from OGC API - Records as well.
In this case, the implementation should verify and declare conformance with these five conformance classes defined in Records corresponding to the following URIs:

[cols="2,7",options="header"]
|===
| OGC API - Records Requirements Class | URI
| https://www.opengis.net/doc/IS/ogcapi-records-1/1.0#clause-record-core[Record Core]                                                   | https://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
| https://www.opengis.net/doc/IS/ogcapi-records-1/1.0#clause-record-collection[Record Collection]                                       | https://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
| https://www.opengis.net/doc/IS/ogcapi-records-1/1.0#clause-crawlable-catalog[Crawlable Catalog]                                       | https://www.opengis.net/spec/ogcapi-records-1/1.0/conf/crawlable-catalog
| https://www.opengis.net/doc/IS/ogcapi-records-1/1.0#clause-local-resources-catalog[Local Resources Catalog]                           | https://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog
| https://www.opengis.net/doc/IS/ogcapi-records-1/1.0#clause-autodiscovery[Autodiscovery]                                               | https://www.opengis.net/spec/ogcapi-records-1/1.0/conf/autodiscovery
|===

The additional requirements include linking to the `/collections` end-point with an `https://www.opengis.net/def/rel/ogc/1.0/ogc-catalog` link relation from the landing page.
