== Conventions
This section provides details of conventions used in this document.

[[identifiers-section]]
=== Identifiers

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-common-2/1.0`.

All <<requirement-definition,Requirements>>, <<requirements-module-definition,Requirements Modules>> and <<ctm-definition,Conformance Modules>> that appear in this document are denoted by partial URIs that are relative to this base.

Additional information about the use of Identifiers in API-Common is provided in the http://docs.opengeospatial.org/DRAFTS/20-071.html[OGC API - Common Users Guide].

[[link-relations-section]]
=== Link relations

<<rfc8288,RFC 8288 (Web Linking)>> is used by this standard to express relationships between resources. Link relation types from the <<link-relations,IANA Link Relations Registry>> are used wherever possible. Additional link relation types are registered with the <<OGCLINKS,OGC Naming Authority>>.

The link relationships used in API-GeoData are described in <<link-relations-table>>. Additional relation types may be used if the implementation warrants it.

[#link-relations-table,reftext='{table-caption} {counter:table-num}']
.Link Relations
[width="90%",cols=",",options="header"]
|===
^|**Link Relation** ^|**Purpose**
|`alternate` |Refers to a substitute for this context [IANA]. + 
Refers to a representation of the current resource which is encoded using another media type (the media type is specified in the `type` link attribute).
|`http://www.opengis.net/def/rel/ogc/1.0/data-meta` |Identifies general metadata for the context (dataset or collection) that is primarily intended for consumption by machines.
|`collection` |The target IRI points to a resource which represents the collection resource for the context IRI. [IANA]
|`http://www.opengis.net/def/rel/ogc/1.0/conformance`|Refers to a resource that identifies the specifications that the link's context conforms to. [OGC]
|`http://www.opengis.net/def/rel/ogc/1.0/data` |Indicates that the link's context is a distribution of a dataset that is an API and refers to the root resource of the dataset in an API. [OGC]
|`describedby`|Refers to a resource providing information about the link's context.[IANA] +
Links to external resources which further describe the subject resource
|`item` |The target IRI points to a resource that is a member of the collection represented by the context IRI. [IANA]
|`http://www.opengis.net/def/rel/ogc/1.0/items` |Refers to a resource that is comprised of members of the collection represented by the link's context. [OGC]
|`license`|Refers to a license associated with this context. [IANA]
|`self`|Conveys an identifier for the link's context. [IANA] +
A link to another representation of this resource.
|`service-desc`|Identifies service description for the context that is primarily intended for consumption by machines. [IANA] +
API definitions are considered service descriptions.
|`service-doc`|Identifies service documentation for the context that is primarily intended for human consumption. [IANA]
|`service-meta`|Identifies general metadata for the context that is primarily intended for consumption by machines. [IANA]
|===

Additional information on the use of link relationships is provided in the link:http://docs.opengeospatial.org/DRAFTS/20-071.html#link-relations-section[OGC API - Common Users Guide].

=== Geometry

[[spatial-geometry-section]]
==== Geospatial Geometry

Standardized concepts for geospatial characteristics are needed in order to share geographic information between applications. Concepts for geometry are key. These concepts are standardized in <<iso19107,_ISO 19107_>>.

The geospatial geometry used in the OGC API - Common Standards is documented in the <<OGC10-100r3,GML Simple Features Profile >> Standard. This Profile defines a subset of the ISO 19107 geometry which is aligned with the OGC <<sfsql,Simple Features for SQL>> Standard. That geometry includes: Point, Curve (LineString), Surface (Polygon), MultiPoint, MultiCurve, and MultiSurface.

[[temporal-geometry-section]]
==== Temporal Geometry

Standardized concepts for temporal characteristics are also needed in order to share date and time information between applications. OGC API Common adopts the Gregorian calendar and a 24 hour time keeping system for its temporal geometry. All representations of that geometry which are discussed in this document conform to <<rfc3339,RFC 3339>>.

An <<rfc5234,ABNF>> representation of the RFC 3339 format is provided in <<date-time-bnf-annex,Annex F>>.

=== Coordinate Reference Systems

As discussed in Chapter 9 of the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practices document>>, the ability to express and share location in a consistent way is one of the most fundamental aspects of publishing geographic data. To do so, it is important to be clear about the coordinate reference system (CRS) within which the coordinates are expressed.

This API-GeoData Standard does not mandate the use of a specific coordinate reference system. However, if no CRS is specified, the default coordinate reference systems for spatial geometries are:

* CRS84 - WGS 84 longitude and latitude without height
* CRS84h - WGS 84 longitude and latitude with ellipsoidal height

Temporal geometry is measured relative to an underlying temporal reference system (TRS). This API-GeoData Standard does not mandate a specific temporal coordinate reference system. However, all dates or timestamps discussed in this document are in the Gregorian calendar and conform to <<rfc3339,RFC 3339>>. In data, other temporal reference systems may be used where appropriate.

OGC Topic Volume 2 – Referencing by Coordinates  (<<iso19111,ISO 19111>>) provides the conceptual model for Coordinate Reference Systems.

=== API definition

==== General remarks

This OGC Standard specifies requirements and recommendations for the development of APIs that share spatial resources using a standard way of doing so. In general, deployed APIs will go beyond the requirements and recommendations stated in this Standard. They will support additional operations, parameters, and so on that are specific to the API or the software tool used to implement the API.

So that developers can more easily learn how to use the API, good documentation is essential. In the best case, documentation would be available both in HTML for human consumption and in a machine readable format that can be processed by software for run-time binding. OpenAPI is one way to provide that machine readable documentation.

==== Role of OpenAPI

This OGC API Standard uses OpenAPI 3.0 fragments in examples and to formally state requirements. Using OpenAPI 3.0 is not required for implementing an OGC API. Other API definition languages may be used along with, or instead of, OpenAPI. However, any API definition language used should have an associated conformance class advertised through the `/conformance` path.

This standard includes a <<rc_oas30-section,conformance class>> for API definitions that follow the <<openapi,OpenAPI specification 3.0>>. Alternative API definition languages are also allowed. Conformance classes for additional API definition languages will be added as the OGC API landscape continues to evolve.

==== References to OpenAPI components in normative statements

Some normative statements (requirements, recommendations and permissions) use a phrase that a component in the API definition of the server must be "based upon" a schema or parameter component in the OGC schema repository.

In this case, the following changes to the pre-defined OpenAPI component are permitted:

* If the server supports an XML encoding, `xml` properties may be added to the relevant OpenAPI schema components.
* The range of values of a parameter or property may be extended (additional values) or constrained (only a subset of all possible values is allowed). An example for a constrained range of values is to explicitly specify the supported values of a string parameter or property using an _enum_.
* Additional properties may be added to the schema definition of a Response Object.
* Informative text, such as comments or description properties, may be changed or added.

For OGC API definitions that do not conform to the <<openapi,OpenAPI Specification 3.0>>, the normative statement should be interpreted in the context of the API definition language used.

==== Reusable OpenAPI components

Reusable components for OpenAPI definitions for an OGC API are referenced from this document. They are available from the OGC Schemas Registry at http://schemas.opengis.net/ogcapi/common/part1/1.0[http://schemas.opengis.net/ogcapi/common/part1/1.0] and http://schemas.opengis.net/ogcapi/common/part2/1.0[http://schemas.opengis.net/ogcapi/common/part2/1.0]

Additional information on the use of OpenAPI as an API definition is provided in the http://docs.opengeospatial.org/DRAFTS/20-071.html#openapi-section[OGC API - Common Users Guide].
