[[rc-simple-query-section]]
== Requirements Class "Simple Query"
:sectnums:

include::requirements/requirements_class_simple_query.adoc[]

This Requirements Class describes query parameters that can be used to discover and select resource collections exposed through an OGC Web API.

Implementors of this Requirements Class must also implement the `/Collections` Requirements Class.

include::requirements/simple_query/REQ_dependency-collections.adoc[]

[[parameter-requirements]]
=== Parameter Requirements

Query parameters are used in URIs to limit the resources which are returned on a GET request. The OGC API - Common - Part 2: Geospatial Data Standard identifies three query parameters for use in OGC API standards:

* <<bbox-parameter-requirements,bbox>>: Bounding Box
* <<parameter-datetime-requirements,datetime>>: Date and Time
* <<limit-parameter-requirements,limit>>: Response resource count limit

The behavior generated by these parameters is specific to the operation and resource upon which they are applied. Those behaviors are described for each resource type and operation in the <<target-resource-requirements,Target Resource Requirements>> section.

Use of these query parameters with any specific operation is optional. Developers of API-GeoData servers should document their supported parameters in the API definition as describe in <<apicore,API-Core>>.

[[bbox-parameter-requirements]]
==== Parameter bbox

include::../api_modules/bbox/requirements_module_bbox.adoc[]

[[datetime-parameter-requirements]]
==== Parameter datetime

include::../api_modules/datetime/requirements_module_datetime.adoc[]

[[limit-parameter-requirements]]
==== Parameter limit

include::../api_modules/limit/requirements_module_limit.adoc[]

[[target-resource-requirements]]
=== Target Resource Requirements

The target of the parameters defined in this conformance class is the <<collection-description,Collection>> resource described in the <<rc-collections-section,Collections>> Requirements Class. The purpose of these parameters is to select a subset of <<collection-description,Collection>> resources to be included in the response to a <<collections-metadata,/collections>> request.

Three parameters are defined for use with the <<collections-metadata,Collections>> resource. These parameters subset the set of <<collection-description,Collection>> entries returned based on spatial, temporal, and volumetric filters. These parameters are documented in the <<parameter-requirements,Parameter Requirements>> section. 

The `collections` property of the Collections response provides a description of each individual collection hosted by the API. These descriptions are based on the link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collectionDesc.json[Resource Collection Schema]. This schema is described in detail in the <<collection-description,Resource Collection>> section of this Standard. 

==== Spatial and Temporal Filtering

A client may select a subset of the hosted collections using the <<bbox-parameter-requirements,`bbox`>> and the <<datetime-parameter-requirements,`datetime`>> parameter. These parameters are evaluated against the `extent` element of each Collection item in the Collections response.

The requirements governing the processing of these parameters are:

include::requirements/simple_query/REQ_rc-bbox-collection-response.adoc[]

include::requirements/simple_query/REQ_rc-datetime-collection-response.adoc[]

==== Volumetric Filtering

The client may limit the number of collections returned in a response by using the `limit` parameter. When applied against the `/collections` resource, the <<limit-parameter-requirements,`limit`>> parameter indicates the maximum number of collections which should be included in a single response.

include::requirements/simple_query/REQ_rc-limit-collection-response.adoc[]

The server also has the option of limiting the size of the Collections response.  

include::recommendations/simple_query/PER_rc-md-items.adoc[]

==== Paged Response

If the collections response does not contain all of the collection resources available from this server, then the client should be informed of that fact.

include::recommendations/simple_query/REC_rc-paged-response.adoc[]

The `numberMatched` property of the Collections response indicates the number of Collection items included in the Collections response. This may be a subset of the total set of collections hosted by the API. Selection of which collections to include in a subset is controled through the <<bbox-parameter-requirements,`bbox`>>, <<datetime-parameter-requirements,`datetime`>> and other selection parameters provided by the client.

include::requirements/simple_query/REQ_rc-numberMatched.adoc[]

The number of collection items included in a Collections response may be a subset of the number matched. In that case, the `numberReturned` property of the Collections response indicates the number of collection items returned in this "page" of the Collections response. 

include::requirements/simple_query/REQ_rc-numberReturned.adoc[]

If the Collections response contains a subset of the selected collection items (numberReturned is less than numberMatched) then the Collections response should contain links for navigating to the rest of the collection items as described in the <<limit-parameter-requirements,limit parameter>> section.

