== Conformance

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the <<citepp,OGC Compliance Testing Policies and Procedures>> and the https://www.ogc.org/compliance/[OGC Compliance Testing] web site.

The one Standardization Target for this standard is Web APIs.

API-GeoData defines API modules intended for re-use by other OGC Web API standards. It is anticipated that this standard will only be implemented through inclusion in other standards. Therefore, all the relevant abstract tests in Annex A shall be included or referenced in the Abstract Test Suite for each separate standard that normatively references this standard.

API-GeoData builds on API modules defined in the `OGC API - Common - Part 1: Core` (<<apicore,API-Core>>) Standard. Each <<requirements-class-definition,Requirements Class>> in the API-GeoData Standard identifies the API-Core <<ctc-definition,Conformance Classes>> upon which it depends. 

Proof of conformance with a Requirements Class includes demonstration of conformance with all dependencies of that Requirements Class. Unless otherwise specified, conformance only has to be demonstrated for those operations, parameters, and resources which are defined in that Requirements Class.  

This standard identifies five <<ctc-definition,conformance classes>>. The conformance classes implemented by an OGC API are advertised through the `/conformance` path on the landing page. Each conformance class is defined by one <<requirements-class-definition,requirements class>>. The tests in Annex A are organized by Requirements Class. So an implementation of the _Collections_ conformance class must pass all tests specified in Annex A for the _Collections_ requirements class.

The requirements classes for API-GeoData are:

* <<rc_collections-section,Collections>>
* <<rc-simple-query-section,Simple Query>>
* <<rc-umd-collection-section,Uniform Multi-Dimension Collection>>
* <<rc_html-section,HTML>>
* <<rc_json-section,JSON>>

The <<rc_collections-section,Collections Requirements Class>> defines a common means to describe and access <<collection-definition,collections>> of <<spatial-resource-definition,spatial resources>>.

The <<rc-simple-query-section,Simple Query Requirements Class>> defines basic query parameters for the selection of individual <<collection-definition,collections>> of <<spatial-resource-definition,spatial resources>>.

The <<rc-umd-collection-section,Uniform Multi-Dimension Collection Requirements Class>> extends the <<rc-simple-query-section,Simple Query Requirements Class>> to support selection of individual <<collection-definition,collections>> of <<spatial-resource-definition,spatial resources>> in an arbitrary uniform multi-dimension space.

The <<rc_collections-section,Collections Requirements Class>> does not mandate a specific encoding or format for representing resources. The <<rc_html-section,_HTML_>> and <<rc_json-section,_JSON_>> requirements classes specify representations for these resources in commonly used encodings for spatial data on the web.

The structure and organization of a collection of spatial resources is very much dependent on the nature of that resource and the expected access patterns. This is information which cannot be specified in a common manner. This Standard specifies the requirements necessary to discover and understand a generic collection and its' contents. Requirements governing a specific type of resource are specified in resource-specific OGC API standards.



