[[rc-umd-collection-section]]
== Requirements Class "Uniform Multi-Dimension Collection" 
:sectnums:

include::requirements/requirements_class_umd-collection.adoc[]

include::requirements/umd_collection/REQ_dependency-collections.adoc[]

include::recommendations/umd_collection/REC_dependency-collections.adoc[]

The <<rc-collections,Collections>> Requirements Class defines a <<collection-resource-definition-section,Collection>> resource which supports both <<spatial-geometry-section,geospatial>> and <<temporal-geometry-section,temporal>> geometries. However, some resources cannot be fully described with just these two geometries. The <<rc-umd-collection-section,Uniform Multi-Dimension Collection>> Requirements Class extends the <<collection-resource-definition-section,Collection>> resource to support geometries with an unlimited number of uniform, domain-specific axis. 

[[umd-collection-definition]]
=== Uniform Multi-Dimension Collection Definition

The Uniform Multi-Dimension Collection is an extension of the <<collection-resource-definition-section,Collection>> resource. So all of the requirements defined in  <<rc-collections-section,Collections>> Requirements Class are required.

Support for domain-specific Collections is supplied by the `Extent with Uniform Additional Dimensions` requirements module.

include::../api_modules/extent-uad/requirements_module_extent-uad.adoc[]

[[umd-selection-parameter]]
=== Multi-Dimension Collection Selection

Selection and access of a Uniform Multi-Dimension Collection is similar to that of a <<collection-resource-definition-section,Collection>> resource. All of the requirements defined in the <<rc-simple-query-section,Simple Query>> Requirements Class also apply to this Requirements Class.  So all of the requirements defined in  <<rc-collections-section,Collections>> Requirements Class are required. 
