[[rc-collections-section]]
== Requirements Class "Collections"
include::requirements/requirements_class_collections.adoc[]

This Requirements Class describes the resources and operations used to list and describe geospatial collection resources exposed through a Web API consistently across OGC API Standards. This class does neither specify how to organize your data into collections nor how to provide access to the data described in the collections. That level of detail is reserved for OGC Web API standards defining access mechanisms through specific resources (see <<access-mechanisms,Access mechanisms Section>>).

include::recommendations/collections/REC_collections-part1-landing-page.adoc[]

The two resources defined by this Requirements Class are summarized in <<collection-resources>> and their operations are defined in the following requirements.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<collections-metadata,Collections>> |/collections ^|GET |List of available Collections including some descriptions of each one
|<<collection-description,Collection description>> |/collections/{collectionId} ^|GET |Description about a specific collection of geospatial data with links to distribution
|===

[[collections-metadata]]
=== Collections Resource

OGC API implementations typically organize their geospatial resources into collections. Information about those collections is accessed through the `/collections` path and the http://www.opengis.net/def/rel/ogc/1.0/data link relation.

==== Operation

include::requirements/collections/REQ_collections-collections-list-op.adoc[]

==== Response

include::requirements/collections/REQ_collections-collections-list-success.adoc[]

The collections response returned by this operation is based on the link:https://github.com/opengeospatial/ogcapi-common/tree/master/collections/openapi/schemas/common-geodata/collections.yaml[collections.yaml] JSON schema.
An example of a response listing collections are provided in <<collections-list-examples>>.

#TODO: Update to schemas.opengis.net for publication#

// .collections.yaml
// [source, YAML]
// include::openapi/schemas/common-geodata/collections.yaml[]

This Collections schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_collections-collections-list-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_collections-collections-list-describedby.adoc[]

The `collections` property of the Collections response provides a description of each individual collection hosted by the API.

include::requirements/collections/REQ_collections-collections-list-collections.adoc[]

The array items included in the `collection` property are described in the <<collection-description,Collection Resource>> section of this Requirements Class.

This Requirements Class does not define any parameters for use against a `collections` resource. Implementers who wish to support filtering of the collections to be included in a result set should implement the   <<rc-simple-query-section,Simple Query>> Conformance Class for that purpose.

[[collections-list-examples]]
===== Collections Response Example

This example response listing available collections in JSON is for a dataset with a single "buildings" feature collection.

There is a link to the resource listing collections itself (link relation type: `self`).

Representations of this resource in other formats are referenced (link relation type: `alternate`).

An additional link is to the logical schema of the collection (link relation type: `[ogc-rel:schema]`).

The reference systems for describing the spatiotemporal extent do not need to be specified, as they default to [OGC:CRS84] and Gregorian calendar / Coordinated Universal Time (UTC),
and should always be specified this way for data referenced to Earth (independently of the native / storage reference system of the data itself).

.Example `/collections` response listing collections
[source,json]
----
include::examples/collections_list.json[]
----

==== Error situations

See <<http-status-codes>> for general guidance.

[[collection-description]]
=== Collection Description Resource

Each resource collection is described by a set of metadata. That metadata can be accessed directly using the `/collections/{collectionId}` path and as an entry in the `collections` property of the `/collections` resource.

==== Operation

include::requirements/collections/REQ_collections-description-op.adoc[]

[[collection-resource-definition-section]]
==== Response

include::requirements/collections/REQ_collections-description-success.adoc[]

#TODO: Update to schemas.opengis.net for publication#

The collection description response returned by this operation is based on the https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml[collectionDesc.yaml] JSON schema.

An example of a response describing a collection are provided in <<collection-description-examples>>.

// .Collection Resource Schema
// [source, YAML]
// include::openapi/schemas/common-geodata/collectionDesc.yaml[]

Most of the properties of the Collection resource are self-explanatory. However, a few properties require additional explanation.

[[collection-attribution-section]]
===== Attribution

A collection description can include an `attribution` property allowing clients to display a short attribution for data being visualized, typically shown at the bottom of a map.
This attribution can contain markup text whose format may be indicated in the `attributionMediaType` property (e.g., `text/html` for HTML or `text/markdown` for https://commonmark.org/[CommonMark]).
If the 'attributionMediaType' indicates something other than `text/plain`, the `attribution` element string should be interpreted by a markup parser selected based on that media type to be presented to the user
(e.g., `text/markdown` will be parsed by a library supporting CommonMark). By allowing markup, the attribution string can import images (e.g., organization logos) and format the text (e.g., the name of the organization in italics).
See the example <<collection-description-examples,collection response>> for an example of the use of markup in the attribution element.

[[collection-item-type-section]]
===== Item Type

In some Geospatial collections, the members (`items`) that make up that collection can be individually accessed by a client. In this case, the `itemType` property in the Collection resource identifies the type of the `items` accessible from that collection.

include::recommendations/collections/REC_collections-description-item-type.adoc[]

[collection-links-section]]
===== Links

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_collections-description-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_collections-collection-describedby.adoc[]

[[collection-extent-section]]
===== Extent

The extent property defines a spatial-temporal envelope that encompasses the geospatial data in the collection. Since not all collections are nicely clustered around a single place in space and time, the extent property provides flexibility in how that surface can be defined.

* Spatial Bounding Box (Bbox) provides a set of rectangular bounding boxes which use geographic coordinates to envelope portions of the collection. Typically only the first element would be populated. Additional boxes may be useful, for example, when the collection is clustered in multiple, widely-separated locations.
* Temporal Interval provides a set of temporal periods. Typically only the first temporal period would be populated. However, like Bbox, additional periods can be added if the collection does not form a single temporal cluster.

The temporal reference system (`trs`) specified in the `temporal` property of the `extent` defines not only the reference system of the `interval`,
but also the reference system for the primary temporal dimension of the data.

For the spatial extent, the `crs` specified in the `spatial` property of the `extent` defines only the coordinate reference system of the `bbox`.
For data referenced to Earth, this `crs` will always be [OGC:CRS84] or [OGC:CRS84h].
The native CRS of the data is specified separately in the `storageCrs` property of the collection description.
For some access mechanisms, this native CRS corresponds to the default output CRS.
These access mechanisms may additionally support other output CRSs which are specified in the `crs` property of the collection description.

For the `storageCrs` as well as for the `crs` list of supported output CRSs, implementors of web APIs based on OGC API standards are strongly recommended to reference existing CRS definitions in the form of URIs
(or the equivalent CURIEs) such as the ones provided by the EPSG database. However, there are situations where the required CRS has not been registered with an authority.

For these cases, where a URI does not exist, a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition of the reference system,
or a JSON encoding of the CRS (using the PROJ JSON schema or a potential "CRS JSON" successor once defined by the OGC) can be specified.

Such alternate CRS definitions can also be used for the `crs` of the `bbox` for data in an engineering CRS or otherwise not georeferenced to Earth.

// TODO: Create a recommendation to reference existing CRS definitions for `crs` and `storageCrs`

include::requirements/collections/REQ_collections-description-extent.adoc[]

include::requirements/collections/REQ_collections-description-extent-multi.adoc[]

include::recommendations/collections/REC_collections-description-extent-single.adoc[]

include::recommendations/collections/PER_collections-description-extent-extensions.adoc[]

include::recommendations/collections/REC_collections-description-storage-crs-bbox.adoc[]

include::recommendations/collections/PER_collections-description-reference-systems.adoc[]

[[collection-description-examples]]
===== Collection Object Examples

This Collection Description example response in JSON is for a single "buildings" collection.

The basic descriptive information includes:

* "id": an identifier for this collection
* "title": human-readable title for this collection
* "description": longer text describing this collection
* "attribution": markup providing attribution (owner, producer, logo, etc.) of this collection

The response includes links to:

* the response itself (link relation type: `self`),
* representations of this response in other formats are referenced using (link relation type: `alternate`),
* an additional link is to a logical schema for the collection (link relation type: `[ogc-rel:schema]`).

Finally, this response includes both spatial and temporal extents.

The reference systems for describing the spatiotemporal extent do not need to be specified, as they default to [OGC:CRS84] (longitude, latitude) and Gregorian calendar / Coordinated Universal Time (UTC),
and should always be specified this way for data referenced to Earth (independently of the native / storage reference system of the data itself).

.Example `/collections/{collectionId}` response describing a collections
[source,json]
----
include::examples/collection_description.json[]
----

==== Error Situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collections-api-records]]
=== OGC API - Records compliance

When implementing this "Collections" requirement class, the `/collections` end-point can be considered a _Local Resource Catalog_, where the local resources are the collections being cataloged.

This requirement class is consistent with the requirements of https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog[OGC API - Records - Part 1: Core "Local Resources Catalog" (Deployment)].
An implementation may gain additional interoperability by conforming to that requirement class from OGC API - Records as well.
In this case, the implementation should verify and declare conformance with these five conformance classes defined in Records corresponding to the following URIs:

[cols="2,7",options="header"]
|===
| OGC API - Records Requirements Class | URI
| https://docs.ogc.org/DRAFTS/20-004.html#clause-record-core[Record Core]                                                   | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
| https://docs.ogc.org/DRAFTS/20-004.html#clause-record-collection[Record Collection]                                       | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
| https://docs.ogc.org/DRAFTS/20-004.html#clause-crawlable-catalog[Crawlable Catalog]                                       | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/crawlable-catalog
| https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog[Local Resources Catalog]                           | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog
| https://docs.ogc.org/DRAFTS/20-004.html#clause-autodiscovery[Autodiscovery]                                               | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/autodiscovery
|===

The additional requirements include linking to the `/collections` end-point with an `http://www.opengis.net/def/rel/ogc/1.0/ogc-catalog` link relation from the landing page.
