[abstract]
== Abstract

The OGC standards baseline has been extended to include https://en.wikipedia.org/wiki/Resource-oriented_architecture[Resource Oriented Architectures] and https://portal.ogc.org/files/?artifact_id=71776&version=1[Web APIs]. In the course of developing OGC Web API standards, some practices proved to be common across multiple OGC Web API standards. These common practices are documented in the OGC API - Common Multi-Part Standard. OGC API - Common standards serve as reusable building-blocks. Standards developers can use these building-blocks in the construction of OGC Web API Standards. The result is a modular suite of coherent API standards which can be adapted by a system designer for the unique requirements of their system.

Spatial data is rarely considered as a single entity. <<feature-collection-definition,Feature Collections>>, <<coverage-definition,Coverages>>, <<dataset-definition,Data Sets>>. They are all aggregations of <<spatial-thing-definition,Spatial>> or <<temporal-thing-definition,Temporal>> Resources. It stands to reason that an OGC Web API would also expose its' holdings as aggregates of spatial resources.

The purpose of the OGC API - Common - Part 2: Geospatial Data (API-GeoData) Standard is to provide a means of organizing these collections and to define operations for the discovery and selection of individual collections. 

OGC API-GeoData does not specify the nature of the geospatial data that make up a collection. Rather, the standard specifies a basic capability which should be applicable to any geospatial resource type. Additional OGC Web API standards extend this foundation to define resource-specific capabilities.


////
== Keywords

Keywords inserted here automatically by Metanorma
////


.Preface

This document defines the _OGC API - Common - Part 2: Geospatial Data_ Standard. Suggested additions, changes and comments on this standard are welcome and encouraged. Such suggestions may be submitted as an issue on the https://github.com/opengeospatial/ogcapi-common/issues[_OGC API - Common_ GitHub repository].

////
*OGC Declaration*
////

////
[THIS TEXT IS ALREADY ADDED AUTOMATICALLY IN THE FRONTISPIECE OF ALL OGC DOUCMENTS]

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
////

== Security Considerations

See <<OAComm,OGC API - Common - Part 1: Core>>, Clause 11.


[.preface]
== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*
|Chuck Heazel _(editor)_ |Heazeltech
|Jerome St-Louis _(editor)_ |Ecere Corporation
|Joan Masó (editor) | Universitat Autònoma de Barcelona (CREAF)
|Chris Little |UK Met Office
|Carl Reed |Self
|Panagiotis (Peter) A. Vretanos |CubeWerx Inc.
|===
