[[rc-umd-collection-section]]
== Requirements Class "Uniform Multi-Dimension Collection"
:sectnums:

include::requirements/requirements_class_umd-collection.adoc[]

The <<rc-collections,Collections>> Requirements Class defines a <<collection-resource-definition-section,Collection>> resource which supports both geospatial and temporal dimensions.
However, the domain of some datasets cannot be fully described with only spatiotemporal dimensions.
The <<rc-umd-collection-section,Uniform Multi-Dimension Collection>> Requirements Class extends the <<collection-resource-definition-section,Collection>> resource to support an unlimited number of
dimensions defined in a uniform manner, so that clients supporting this requirements class can interpret these dimensions in a generic manner.

[[umd-collection-definition]]
=== Uniform Multi-Dimension Collection Definition

The Uniform Multi-Dimension Collection is an extension of the <<collection-resource-definition-section,Collection>> resource.

include::requirements/umd-collection/REQ_extent-uad-definition.adoc[]

.Diagram explaining relationship between cellsCount, interval and resolution in regular grids
[source]
----
 interval: [0, 1]

 0.0     0.5     1.0  Coordinate values (resolution 0.5)
  |       |       |

  *       *       *   cellsCount = 3   cell whose geometry is a point  (1 - 0) / 0.5 + 1  = 3

 [========|=======]   cellsCount = 2   cell whose geometry is an area  (1 - 0) / 0.5      = 2
----

include::recommendations/umd-collection/PER_categorical_dimension_interval.adoc[]

This requirement class allows the definition of additional dimensions by specifiying a temporal reference system (`trs`), a vertical reference system (`vrs`) or a semantic `definition` property,
an interval providing the lower and upper bound for the coordinates along that dimension, as well as a `unit` of measure where applicable.

The `trs` or `vrs` property can be populated with either a URI or CURIE, a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition of the reference system, or a JSON encoding of the CRS
(using the PROJ JSON schema or a potential "CRS JSON" successor once defined by the OGC).

NOTE: If a 3D CRS including the vertical dimension, that CRS should be used inside the "spatial" object of the extent, instead of defining a separate vertical dimension using `vrs`.
For vertical CRSes corresponding to the concept of a variable, such as a pressure level, the semantic definition for that variable should be used instead of `vrs`.

A YAML JSON Schema for the uniform additional dimensions is available here:
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/extent-uad.yaml[extent-uad.yaml] and reproduced below.

[[uniform-uad-schema]]
.Schema for collection description extent with Uniform Additional Dimensions
[source,yaml,options="unnumbered"]
----
include::./openapi/schemas/common-geodata/extent-uad.yaml[]
----
