[[rc-collections-section]]
== Requirements Class "Collections"
:sectnums:

include::requirements/requirements_class_collections.adoc[]

This Requirements Class describes the resources and operations used to describe and access resource collections exposed through an OGC Web API. It does not include any requirements about how resources are aggregated into collections nor about the aggregated resources themselves. That detail is reserved for resource-specific OGC Web API standards (see <<views-introduction,Views Section>>)..

The two resources defined in this Requirements Class are summarized in <<collection-resources>>. 

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<collections-metadata,Collections>> |/collections ^|GET |Information which describes the set of available Collections 
|<<collection-description,Collection>> |/collections/{collectionId} ^|GET |Information about a specific collection of geospatial data with links to distribution
|===

[[collections-metadata]]
=== Collections

OGC APIs typically organize their Spatial Resources into collections. Information about those collections is accessed through the `/collections` path and the http://www.opengis.net/def/rel/ogc/1.0/data link relation.

==== Operation

include::requirements/collections/REQ_rc-md-op.adoc[]

==== Response

include::requirements/collections/REQ_rc-md-success.adoc[]

The collections response returned by this operation is based on the link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collections.json[collections.json] JSON schema. Examples of collections responses are provided in <<collections-metadata-examples>>.

.collections.json
[source, JSON]
include::openapi/schemas/collections.json[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-descriptions.adoc[]

The `timeStamp` property of the Collections response indicates when the response was generated.

include::requirements/collections/REQ_rc-timeStamp.adoc[]

The `collections` property of the Collections response provides a description of each individual collection hosted by the API. These descriptions are based on the link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collectionDesc.json[Resource Collection Schema]. This schema is described in detail in the <<collection-description,Resource Collection>> section of this Standard. 

include::requirements/collections/REQ_rc-md-items.adoc[]

A client may wish to select a subset of the hosted collections using HTTP query parameters. The <<rc-simple-query-section,Simple Query>> Conformance Class defines the <<bbox-parameter-requirements,`bbox`>> and the <<datetime-parameter-requirements,`datetime`>> parameter for that purpose.  It also defines how a server should process those parameters. These parameters are evaluated against the `extent` element of each Collection item in the Collections response.

The requirements governing the processing of these parameters are provided by the <<rc-simple-query-section,Simple Query>> Requirements Class.

include::requirements/collections/REQ_rc-bbox-unsupported.adoc[]

include::requirements/collections/REQ_rc-datetime-unsupported.adoc[]

The <<rc-simple-query-section,Simple Query>> Conformance Class also defines a parameter to limit the number of collections returned in a response. This <<limit-parameter-requirements,`limit`>> parameter indicates the maximum number of collections which should be included in a single response.

include::requirements/collections/REQ_rc-limit-unsupported.adoc[]

==== Error situations

See <<http-status-codes>> for general guidance.

[[collection-description]]
=== Resource Collection

Each resource collection is described by a set of metadata. That metadata is accessed directly using the `/collections/{collectionId}` path or as an entry in the `collections` property of the Collections resource.

==== Operation

include::requirements/collections/REQ_src-md-op.adoc[]

==== Response

include::requirements/collections/REQ_src-md-success.adoc[]

==== Error Situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collection-resource-definition-section]]
==== Collection Resource Definition

include::requirements/collections/requirements_module_collection.adoc[]

Examples of Collection resources are provided in <<collection-description-examples>>.

include::requirements/collections/REQ_collection-definition.adoc[]

.Collection Resource Schema
[source, JSON]
include::./openapi/schemas/collectionDesc.json[]

Many of the properties of the Collection resource are self-explanitory. However, a few call for additional explanation.

[[collection-attribution-section]]
===== Attribution

The attribution element is a special type of string property. Specifically, it can contain markup text. Markup allows a text string to import images and format text. The capabilities are only limited by the markup language used. See the example <<collection-description-examples,collection response>> for an example of the use of markup in the attribution element.

[[collection-item-type-section]]
===== Item Type

In some Geospatial collections, the members (`items`) that make up that collection can be individually accessed by a client. In this case, the `itemType` property in the Collection resource identifies the type of the `items` accessible from that collection.  

include::recommendations/collections/REC_rc-md-item-type.adoc[]

[collection-links-section]]
===== Links

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-items-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-items-descriptions.adoc[]

[[collection-extent-section]]
===== Extent

The extent property defines a spatial-temporal surface which encompasses the geospatial data in the collection. Since not all collections are nicely clustered around a single place in space and time, the extent property provides flexibility in how that surface can be defined. 

* Spatial Bounding Box (Bbox) provides a set of rectangular bounding boxes which use geographic coordinates to envelope portions of the collection. Typically only the first element would be populated. Additional boxes may be useful, for example, when the collection is clustered in multiple, widely-separated locations. 
* Temporal Interval provides a set of temporal periods. Typically only the first temporal period would be populated. However, like bbox, additional periods can be added if the collection does not form a single temporal cluster.

include::requirements/collections/REQ_rc-md-extent.adoc[]

include::recommendations/collections/REC_rc-md-extent.adoc[]

include::recommendations/collections/REC_rc-md-extent-single.adoc[]

include::recommendations/collections/PER_rc-md-extent-extensions.adoc[]
