[[rc_collections-section]]
== Requirements Class "Collections"
:sectnums:

include::requirements/requirements_class_collections.adoc[]

This Requirements Class describes the resources and operations used to discover and query resource collections exposed through an OGC Web API. It does not include any requirements about how resources are aggregated into collections nor about the aggregated resources themselves. That detail is reserved for resource-specific OGC Web API standards.

The three resources defined in this Requirements Class are summarized in <<collection-resources>>. Detailed requirements for each of these resources are provided in the <<collection-resource-requirements,Resource Requirements>> section.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<collections-metadata,Collections Metadata>> |/collections ^|GET |Information which describes the set of suppoprted Collections 
|<<collection-description,Collection Description>> |/collections/{collectionId} ^|GET |Information about a specific Collection
|<<collection-resource,Collection Resource>> |/collections/{collectionId}/items ^|GET |The resources in a specific Collection
|===

This Requirements Class also describes the operations which can be performed on these resources. Requirements for these operations are included with their associated resource descriptions in the <<collection-resource-requirements,Resource Requirements>> section. Three parameters are defined for use in these operations. These parameters are documented in the <<parameter-requirements,Parameter Requirements>> section. A summary of the parameters is provided in <<parameter-summary>>.

[#parameter-summary,reftext='{table-caption} {counter:table-num}']
.Parameter Summary
[width="90%",cols="10,10,60",options="header"]
|===
^|Parameter Name ^|Target ^|Description
|Bounding Box |Extent |Selects resources which have an Extent element that intersects the bounding box
|Date-Time|Extent |Selects resources which have an Extent element that intersects the specified time period
|Limit |The result set |Limits the number of resources which can be returned in one response
|===

Finally, requirements which have general applicablity are provided in the <<general-requirements,General Requirements>> section.

[[collection-resource-requirements]]
=== Resource Requirements

This section expresses the requirements for resources and operations used to discover and query resource collections.

[[collections-metadata]]
==== Collections Metadata

OGC APIs typically organize their Spatial Resources into collections. Information about those collections is accessed through the `/collections` path.

===== Operation

include::requirements/collections/REQ_rc-md-op.adoc[]

===== Parameters

The following query parameters can be used with this operation:

* <<boundingbox-parameter-requirements,Bounding Box>>
* <<datetime-parameter-requirements,Date Time>>
* <<limit-parameter-requirements,Limit>>

===== Response

include::requirements/collections/REQ_rc-md-success.adoc[]

The collections metadata returned by this operation is based on the link:http://schemas.opengis.net/ogcapi/common/part2/1.0/schemas/collections.json[collections.json] JSON schema. Examples of collections metadata are provided in <<collections-metadata-examples>>.

.collections.json
[source, JSON]
include::openapi/schemas/collections.json[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-descriptions.adoc[]

The `collections` property of the Collections Metadata provides a description of each individual collection hosted by the API. These descriptions are based on the link:http://schemas.opengis.net/ogcapi/common/part2/1.0/schemas/collectionDesc.json[Collection Description Schema]. This schema is described in detail in the <<collection-description, Collection Description>> section of this Standard. 

include::requirements/collections/REQ_rc-md-items.adoc[]

The `timeStamp` property of the Collections Metadata indicates when the response was generated.

include::requirements/collections/REQ_rc-timeStamp.adoc[]

The `numberMatched` property of the Collections Metadata indicates the number of collection descriptions included in the Collections Metadata. This may be a subset of the total set of collections hosted by the API. Selection of which collections to include in a subset is controled through selection parameters provided by the client.

include::requirements/collections/REQ_rc-numberMatched.adoc[]

The Collections Metadata should describe all of the collections accessible through the API. However, in some cases that is impractical. An API implementation has the option of limiting the size of the Collections Metadata response.  

include::recommendations/collections/PER_rc-md-items.adoc[]

The number of collection descriptions included in a Collections Metadata response may be a subset of the number matched. This can due to a server imposed limit or the client specified <<limit-parameter-requirements,limit>> parameter. In that case, the `numberReturned` property of the Collections Metadata indicates the number of collection descriptions returned in this "page" of the Collections Metadata. 

include::requirements/collections/REQ_rc-numberReturned.adoc[]

If the Collections Metadata contains a subset of the selected collection descriptions (numberReturned is less than numberMatched) then the Collections Metadata should contain links for navigating to the rest of the collection descriptions as described in the <<limit-parameter-requirements,limit parameter>> section.

===== Error situations

See <<http-status-codes>> for general guidance.

[[collection-description]]
==== Collection Description

Each resource collection is described by a set of metadata. That metadata is accessed directly using the `/collections/{collectionId}` path or as an entry in the `collections` property of the Collections Metadata resource.

===== Operation

include::requirements/collections/REQ_src-md-op.adoc[]

===== Parameters

No parameters have been standardized for this operation.

===== Response

include::requirements/collections/REQ_src-md-success.adoc[]

Collection Descriptions are based on the link:http://schemas.opengis.net/ogcapi/common/part2/1.0/schemas/collectionDesc.json[Collection Description Schema]. Examples of Collection Descriptions are provided in <<collection-description-examples>>.

.Collection Description Schema
[source, JSON]
include::openapi/schemas/collectionDesc.json[]

This schema is further constrained by the following requirements and recommendations.

include::recommendations/collections/REC_rc-md-item-type.adoc[]

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-items-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-items-descriptions.adoc[]

Additional requirements and recommendations apply to the `extent` property of the Collection Description.

include::requirements/collections/REQ_rc-md-extent.adoc[]

include::recommendations/collections/REC_rc-md-extent-single.adoc[]

include::recommendations/collections/PER_rc-md-extent-extensions.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collection-resource]]
==== Collection Resource

A collection resource is the content of the collection as opposed to metadata about that collection. This standard defines the general behavior of this operation, but detailed requirements are the purview of the API standard for that resource type.

===== Operation

include::requirements/collections/REQ_rc-op.adoc[]

===== Parameters

The following query parameters can be used with this operation:

* <<boundingbox-parameter-requirements,Bounding Box>>
* <<datetime-parameter-requirements,Date Time>>
* <<limit-parameter-requirements,Limit>>

[width="90%",cols="2,6a"]
|===
|Note: |Since the type of resource which makes up the collection is not defined, the behavior of these parameters must be tailored to the structure and information content of specific resource types. That tailoring will take place in resource-specific OGC API standards.
|===

===== Response

include::requirements/collections/REQ_rc-response.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[parameter-requirements]]
=== Parameter Requirements

Query parameters are used in URLs to limit the resources which are returned on a GET request. The OGC API - Common - Part 2: Geospatial Data Standard defines three query parameters for use in OGC API standards:

* <<bbox-parameter-requirements,bbox>>: Bounding Box
* <<parameter-datetime-requirements,datetime>>: Date and Time
* <<limit-parameter-requirements,limit>>: Response resource count limit

Use of these query parameters with any specific operation is optional. Developers of API-GeoData servers should document their supported parameters in the API definition as describe in <<apicore,API-Core>>.

[[bbox-parameter-requirements]]
==== Parameter bbox

include::requirements/collections/REQ_rc-bbox-definition.adoc[]

include::requirements/collections/REQ_rc-bbox-response.adoc[]

"Intersects" means that a coordinate that is part of the spatial geometry of the resource falls within the area specified in the parameter `bbox`. This includes the boundaries of the geometries. For curves the boundary includes the start and end position. For surfaces the boundary includes the outer and inner rings.

In case of a degenerated bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all resources match where the geometry intersects with this point.

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a later version of this standard.

For WGS 84 longitude/latitude the bounding box is in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian (180th meridian) the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

Note that the server will return an error if a latitude value of ``160.0`` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://schemas.opengis.net/ogcapi/common/part2/1.0/parameters/bbox.yaml[bbox.yaml].

[[datetime-parameter-requirements]]
==== Parameter datetime

include::requirements/collections/REQ_rc-time-definition.adoc[]

include::requirements/collections/REQ_rc-time-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`time=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate`), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://schemas.opengis.net/ogcapi/common/part2/1.0/parameters/datetime.yaml[datetime.yaml].

[[limit-parameter-requirements]]
==== Parameter limit

The `limit` parameter limits the number of resources that can be returned in a single response.

include::requirements/collections/REQ_rc-limit-definition.adoc[[]

The number of resources returned depends on the server and the value of the `limit` parameter.

*   The client can request a limit to the number of resources returned.
*   The server may have a default value for the limit, and a maximum limit.
*   If the server has any more results available than it returns (the number it returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

include::requirements/collections/REQ_rc-limit-response.adoc[]

The effect of the limit parameter is to divide the response into a number of pages. Each page (except for the last) contains the specified number of entities. The response contains the first `page`. Additional pages can be accessed through hyperlink navigation.

include::recommendations/collections/REC_rc-next-1.adoc[]

include::recommendations/collections/REC_rc-next-2.adoc[]

include::recommendations/collections/REC_rc-next-3.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::recommendations/collections/PER_rc-prev.adoc[]

[[general-requirements]]
=== General Requirements

The following general requirements and recommendations apply to all OGC APIs which implement the API-Common Geospatial Data Standard.

include::../general/clause_8_general.adoc[]
