== Terms and Definitions

[[collection-definition]]
=== *Collection*
A geospatial resource that may be available as one or more <<resource-definition,sub-resource>> <<distribution-definition,distributions>> that conform to one or more OGC API standards. (OGC 20-024)

[[coverage-definition]]
=== *Coverage*
feature that acts as a function to return values from its range for any direct position within its spatiotemporal domain, as defined in OGC Abstract Topic 6 http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[(OGC 09-146r6)]

[[dataset-definition]]
=== *Dataset*
A collection of data, published or curated by a single agent, and available for access or download in one or more representations. (<<DCAT,DCAT>>)

[[distribution-definition]]
=== *Distribution*
A specific representation of a <<dataset-definition,dataset>>. A <<dataset-definition,dataset>> might be available in multiple serializations that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above). (<<DCAT,DCAT>>) +
 +
EXAMPLE: a downloadable file, an RSS feed or an API.

[[extent-definition]]
=== *Extent*
The area covered by something. Within this document, "extent" refers to spatial extent. The size or shape that may be expresses using coordinates. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[feature-definition]]
=== *Feature*
abstraction of real world phenomena (<<iso19101,ISO 19101-1:2014>>) +

[[feature-collection-definition]]
=== *Feature Collection*
a set of *Features* from a *dataset*

[[geometry-definition]]
=== *Geometry*
An ordered set of _n_-dimensional points in a given coordinate reference system. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[ogc-webapi-definition]]
=== *OGC Web API*
A <<webapi-definition,Web API>> that implements one or more <<ctc-definition,Conformance Classes>> from an OGC API Standard.

[[resource-definition]]
=== *Resource*
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>) +

NOTE: The term "resource", when used in the context of an OGC Web API standard, should be understood to mean a <<web-resource-definition,Web Resource>> unless otherwise indicated.

[[queryable-def]]
=== *queryable*
the name of a property of a resource that can be used in a filter expression

[[receivable-def]]
=== *receivable*
the name of a property of a web resource that can be included in representations of the resource when creating or updating a resource

[[resource-type-definition]]
=== *Resource Type*
the definition of a type of <<resource-definition,resource>>. Resource types are re-usable components which are independent of where the resource resides in the API. +

NOTE: Resource types are re-usable components that are independent of where the resource resides in the API."

[[returnable-def]]
=== *returnable*
the name of a property of a web resource that is available in representations of the resource when fetching the resource

[[sortable-def]]
=== *sortable*
the name of a property of a resource that can be used to sort resources of the same type

[[spatial-resource-definition]]
=== *Spatial Resource*
the <<resource-definition,resources>> which we usually think of as Geospatial Data. A <<spatial-thing-definition,Spatial Thing>>. (<<apicore,OGC 19-072>>)

[[spatial-thing-definition]]
=== *Spatial Thing*
anything with spatial extent, (i.e. size, shape, or position) and is a combination of the real-world phenomenon and its abstraction. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[temporal-cs-definition]]
=== *Temporal Coordinate System*
temporal reference system based on an interval scale on which distance is measured as a multiple of a single unit of time. (<<iso19108,ISO 19108>>)

[[temporal-position-definition]]
=== *Temporal Position*
location relative to a temporal reference system (<<iso19108,ISO 19108>>)

[[trs-definition]]
=== *Temporal Reference System*
reference system against which time is measured (<<iso19108,ISO 19108>>)

[[temporal-resource-definition]]
=== *Temporal Resource*
the <<resource-definition,resources>> which we usually think of as time and date focused data. A <<temporal-thing-definition,Temporal Thing>>. (<<apicore,OGC 19-072>>)

[[temporal-thing-definition]]
=== *Temporal Thing*
Anything with temporal extent, i.e. duration. Examples are: the taking of a photograph, a scheduled meeting, a GPS time-stamped track-point. (<<W3C-BASIC-GEO,W3C Basic Geo>>)

[[webapi-definition]]
=== *Web API*
API using an architectural style that is founded on the technologies of the Web. (<<DWBP,W3C Data on the Web Best Practices>>)

[[web-resource-definition]]
=== *Web Resource*
a <<resource-definition,resource>> that is identified by an URI.

=== Abbreviated terms

API::
    Application Programming Interface
CORS::
    Cross-Origin Resource Sharing
CRS::
    Coordinate Reference System
HTTP::
    Hypertext Transfer Protocol
HTTPS::
    Hypertext Transfer Protocol Secure
IANA::
    Internet Assigned Numbers Authority
OGC::
    Open Geospatial Consortium
TRS::
    Temporal Coordinate Reference System
URI::
    Uniform Resource Identifier
YAML::
    YAML Ain’t Markup Language

