[[rc-umd-collection-section]]
== Requirements Class "Uniform Multi-Dimension Collection"
:sectnums:

include::requirements/requirements_class_umd-collection.adoc[]

The <<rc-collections,Collections>> Requirements Class defines a <<collection-resource-definition-section,Collection>> resource which supports both geospatial and temporal dimensions.
However, the domain of some datasets cannot be fully described with only spatiotemporal dimensions.
The <<rc-umd-collection-section,Uniform Multi-Dimension Collection>> Requirements Class extends the <<collection-resource-definition-section,Collection>> resource to support an unlimited number of
dimensions defined in a uniform manner, so that clients supporting this requirements class can interpret these dimensions in a generic manner.

[[umd-collection-definition]]
=== Uniform Multi-Dimension Collection Definition

The Uniform Multi-Dimension Collection is an extension of the <<collection-resource-definition-section,Collection>> resource.

==== Uniform description of all dimensions

This requirement class allows the definition of additional dimensions beyond spatial and temporal in a specific way which is consistent with the spatial and temporal dimensions.

Each dimension is identified by using a semantic `definition` property.
An `interval` providing the lower and upper bound for the coordinates along that dimension also needs to be included, as well as a `unit` of measure where applicable.

As an alternative or in addition to the `definition`, a temporal reference system (`trs`) or a vertical reference system (`vrs`) can be specified.
The `trs` or `vrs` property can be populated with either a URI or CURIE, a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition of the reference system, or a JSON encoding of the CRS
(using the PROJ JSON schema or a potential "CRS JSON" successor once defined by the OGC).

NOTE: If a 3D CRS exists including the vertical dimension, that CRS should be used inside the "spatial" object of the extent, instead of defining a separate vertical dimension using `vrs`.
For vertical CRSes corresponding to the concept of a variable, such as a pressure level, the semantic definition for that variable should be used instead of `vrs`.

For additional dimensions beyond spatial and temporal, the reference system is defined as a combination of the `definition` and `unit`, or alternatively the `trs` or `vrs`.
In addition to specifying the reference system of the `interval`, this also specifies the reference system of that dimension for the data itself.
Unlike the spatial CRS, the collection description in this standard only supports defining a single reference system for the temporal dimension and each additional dimension.

To validate against this UMD Requirements Class, the `- type: object` line within the `anyOf:` in the
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/extent.yaml[extent.yaml] YAML JSON Schema of the collection description's extent should be commented out.

include::requirements/umd-collection/REQ_extent-uad-definition.adoc[]

==== Describing gridded dimensions

For data which is gridded, whether using a regular or irregular grid, this conformance class defines a `grid` property which is used to describe this grid.

.Diagram illustrating a _Value-is-Point_ regular grid
[source]
----
 0.0     0.5     1.0
  |       |       |
  *       *       *

 cellsCount: 3, firstCoordinate: 0, resolution: 0.5,
 relativeBounds: [ 0, 0 ], interval: [ 0, 1 ]
----

.Diagram illustrating two equivalent ways to define the same _Value-is-Area_ regular grid
[source]
----
 0.0     0.5     1.0
  |       |       |
 [========|=======]

 cellsCount: 2, firstCoordinate: 0, resolution: 0.5,
 relativeBounds: [ 0, 0.5 ], interval: [ 0, 1 ]

or

 cellsCount: 2, firstCoordinate: 0.25, resolution: 0.5,
 relativeBounds: [ -0.25, 0.25 ], interval: [ 0, 1 ]
----

include::requirements/umd-collection/REQ_grid-description.adoc[]

include::recommendations/umd-collection/PER_categorical_dimension_interval.adoc[]
