[[terms_and_definitions]]
== Terms and Definitions
This document uses the terms defined in Sub-clause 5 of <<apicore,OGC API - Common - Part 1: Core>> (OGC 19-072), which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "shall" (not "must") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

[[collection-definition]]
* *Collection* +
A body of resources that belong or are used together. An aggregate, set, or group of related resources. (OGC 20-024)

[[coverage-definition]]
* *Coverage* +
feature that acts as a function to return values from its range for any direct position within its spatiotemporal domain, as defined in OGC Abstract Topic 6 http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[(OGC 09-146r6)]

[[dataset-definition]]
* *Dataset* +
collection of data, published or curated by a single agent, and available for access or download in one or more serializations or formats (<<DCAT,DCAT>>)

[[distribution-definition]]
* *Distribution* +
specific representation of a <<dataset-definition,dataset>>. (<<DCAT,DCAT>>) +
 +
EXAMPLE: a downloadable file, an RSS feed or an API.

[[extent-definition]]
* *Extent* +
The area covered by something. Within this document, we always imply spatial extent; e.g. size or shape that may be expresses using coordinates. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[feature-definition]]
* *Feature* +
abstraction of real world phenomena (<<iso19101,ISO 19101-1:2014>>)

[width="90%",cols="1,10"]
|===
|*NOTE:*| More details about the term `feature` may be found in the http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#SDWBP[W3C/OGC Spatial Data on the Web Best Practice] in the section https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry[Spatial Things, Features and Geometry].
|===

[[feature-collection-definition]]
* *Feature Collection* +
a set of *Features* from a *dataset*

[[geometry-definition]]
* *Geometry* +
An ordered set of _n_-dimensional points in a given coordinate reference system. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[resource-definition]]
* *Resource* +
. Any information that can be named. (<<fielding2000,Fielding 2000>>) +
. The intended conceptual target of a hypertext reference. (<<fielding2000,Fielding 2000>>)

[[resource-type-definition]]
* *Resource Type* +
the definition of a type of <<resource-definition,resource>>. Resource types are re-usable components which are independent of where the resource resides in the API.  

[[spatial-resource-definition]]
* *Spatial Resource* +
the <<resource-definition,resources>> which we usually think of as Geospatial Data. A <<spatial-thing-definition,Spatial Thing>>. (<<apicore,OGC 19-072>>)

[[spatial-thing-definition]]
* *Spatial Thing* +
anything with spatial extent, (i.e. size, shape, or position) and is a combination of the real-world phenomenon and its abstraction. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[temporal-cs-definition]]
* *Temporal Coordinate System* +
temporal reference system based on an interval scale on which distance is measured as a multiple of a single unit of time. (<<iso19108,ISO 19108>>)

[[temporal-position-definition]]
* *Temporal Position* +
location relative to a temporal reference system (<<iso19108,ISO 19108>>)

[[trs-definition]]
* *Temporal Reference System* +
reference system against which time is measured (<<iso19108,ISO 19108>>)

[[temporal-resource-definition]]
* *Temporal Resource* +
the <<resource-definition,resources>> which we usually think of as time and date focused data. A <<temporal-thing-definition,Temporal Thing>>. (<<apicore,OGC 19-072>>)

[[temporal-thing-definition]]
* *Temporal Thing* +
Anything with temporal extent, i.e. duration. e.g. the taking of a photograph, a scheduled meeting, a GPS time-stamped track-point. (<<W3C-BASIC-GEO,W3C Basic Geo>>)

[[webapi-definition]]
* *Web API* +
API using an architectural style that is founded on the technologies of the Web. (<<DWBP,W3C Data on the Web Best Practices>>)
