== Terms and Definitions

[[collection-definition]]
=== *Collection*
(in the context of OGC APIs) A set of spatiotemporal data that may be available through one or more <<data-access-mechanism-definition,access mechanisms>> defined by OGC API standard(s)

[[coverage-definition]]
=== *Coverage*

include::./glossaries/iso_tc211/2573_coverage.adoc[]

[[data-access-mechanism-definition]]
=== *Data access mechanism*
(in the context of OGC APIs) A mechanism defined by an OGC API Standard to access spatiotemporal data from a <<collection-definition,collection>>
 +
Such mechanism is based on Web resources which are sub-resources of that collection. The access mechanism could be as simple as the definition of a single sub-resource URL template.
The access mechanism may allow Web clients to access parts and/or the totality of the data available from the collection.

[[dataset-definition]]
=== *Dataset*
A collection of data, published or curated by a single agent, and available for access or download in one or more representations. (<<DCAT,DCAT>>)

[[distribution-definition]]
=== *Distribution*
A specific representation of a <<dataset-definition,dataset>>. A <<dataset-definition,dataset>> might be available in multiple serializations that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above). (<<DCAT,DCAT>>) +
 +
EXAMPLE: a downloadable file, an RSS feed or an API.

[[extent-definition]]
=== *Extent*
The area covered by something. Within this document, "extent" refers to spatial extent. The size or shape that may be expresses using coordinates. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[feature-definition]]
=== *Feature*

include::./glossaries/iso_tc211/168_feature.adoc[]

[[feature-collection-definition]]
=== *Feature Collection*

include::./glossaries/iso_tc211/2500_feature_collection.adoc[]

[[geometry-definition]]
=== *Geometry*
An ordered set of _n_-dimensional points in a given coordinate reference system. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[ogc-webapi-definition]]
=== *OGC Web API*
A <<webapi-definition,Web API>> that implements one or more <<ctc-definition,Conformance Classes>> from an OGC API Standard.

[[resource-definition]]
=== *Resource*
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>) +

NOTE: The term "resource", when used in the context of an OGC Web API standard, should be understood to mean a <<web-resource-definition,Web Resource>> unless otherwise indicated.

[[queryable-def]]
=== *queryable*
the name of a property of a resource that can be used in a filter expression

[[receivable-def]]
=== *receivable*
the name of a property of a web resource that can be included in representations of the resource when creating or updating a resource

[[resource-type-definition]]
=== *Resource Type*
the definition of a type of <<resource-definition,resource>>. Resource types are re-usable components which are independent of where the resource resides in the API. +

NOTE: Resource types are re-usable components that are independent of where the resource resides in the API."

[[returnable-def]]
=== *returnable*
the name of a property of a web resource that is available in representations of the resource when fetching the resource

[[sortable-def]]
=== *sortable*
the name of a property of a resource that can be used to sort resources of the same type

[[spatial-resource-definition]]
=== *Spatial Resource*
the <<resource-definition,resources>> which we usually think of as Geospatial Data. A <<spatial-thing-definition,Spatial Thing>>. (<<OGC19-072,OGC 19-072>>)

[[spatial-thing-definition]]
=== *Spatial Thing*
anything with spatial extent, (i.e. size, shape, or position) and is a combination of the real-world phenomenon and its abstraction. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[temporal-cs-definition]]
=== *Temporal Coordinate System*

include::./glossaries/iso_tc211/446_temporal_coordinate_system.adoc[]

[[temporal-position-definition]]
=== *Temporal Position*

include::./glossaries/iso_tc211/449_temporal_position.adoc[]


[[trs-definition]]
=== *Temporal Reference System*

include::./glossaries/iso_tc211/450_temporal_reference_system.adoc[]

[[temporal-resource-definition]]
=== *Temporal Resource*
the <<resource-definition,resources>> which we usually think of as time and date focused data. A <<temporal-thing-definition,Temporal Thing>>. (<<OGC19-072,OGC 19-072>>)

[[temporal-thing-definition]]
=== *Temporal Thing*
Anything with temporal extent, i.e. duration. Examples are: the taking of a photograph, a scheduled meeting, a GPS time-stamped track-point. (<<W3C-BASIC-GEO,W3C Basic Geo>>)

[[webapi-definition]]
=== *Web API*
API using an architectural style that is founded on the technologies of the Web. (<<DWBP,W3C Data on the Web Best Practices>>)

[[web-resource-definition]]
=== *Web Resource*
a <<resource-definition,resource>> that is identified by an URI.

=== Abbreviated terms

API::
    Application Programming Interface
CORS::
    Cross-Origin Resource Sharing
CRS::
    Coordinate Reference System
HTTP::
    Hypertext Transfer Protocol
HTTPS::
    Hypertext Transfer Protocol Secure
IANA::
    Internet Assigned Numbers Authority
OGC::
    Open Geospatial Consortium
TRS::
    Temporal Coordinate Reference System
URI::
    Uniform Resource Identifier
YAML::
    YAML Ain’t Markup Language

