[[rc-hierarchical-collections]]
== Requirements Class "Hierarchical Collections"
:sectnums:

include::requirements/requirements_class_hierarchy.adoc[]

This "Hierarchical Collections" requirement class allows to organize a large number of collections according to a single pre-determined hierarchy.
This capability addresses two primary use cases:

- Drilling down through a very large number of collections in a tree-like manner, allowing clients to explore the entire hierarchy without first needing to retrieve the entire list of collections.
  The hierarchical organization also allows to present the list of collections in a hierarchical manner, for example using a tree view control, and makes it easier to discover or browse to a
  particular collection of interest using such an interface, with the ability to expand and collapse branches of the hierarchy.
  For example, data collections may be organized as a hierarchy of countries, states, and cities.
- The `ancestor` parameter defined herein allows to load a limited subset of interest from  the available collections.
  In conjunction with the "Searchable Collections" and/or "Filtering collections using CQL2" requirement classes, this parameter also allows to narrow down a search to a particular branch of the hierarchy.

NOTE: This requirement class does not address the use cases of defining simultaneous multiple hierarchies -- a collection can have a single `parent` collection.
Such multiple hierarchies capability could be defined independently (for example, the https://docs.ogc.org/per/18-045.html#hierarchical_paths_extension[`/themes` extension] proposed previously),
or the use case could be addressed through the `keywords` and/or `themes` core queryable properties defined by _OGC API - Records_ and applicable to the "Searchable Collections" requirement class.

All collections of the hierarchy, whether leaf colections, top-level collections, or anywhere in between, may or may not directly offer access to data using one or more access mechanisms
defined in one or more OGC API data access standards, such as _OGC API - Tiles_, _OGC API - Maps_, _OGC API - Features_ or _OGC API - Coverages_ (or others).
Those access mechanisms will be included as usual in `links` of the collections.

In the case where a parent collection offers a direct data access mechanism while also having children collections, the `collections=` query parameter might be applicable to some of these access mechanisms,
in a similar way to how `collections=` is applicable to data access mechanisms tied to the root of the API (see for example the "Collection Selection" requirement classes of _OGC API - Maps_ and _OGC API - Tiles_).

A client that is not aware of the capability defined in this requirement class can safely ignore it without any impact, and will simply treat the list of collections in the usual flat manner,
 as defined in the "Collections" requirement class.

=== `parent` property in collection description

A new `parent` property is defined to include in the collection description resources (`/collections/{collectionId}`)
and collection listing resource (`/collections`), indicating the `{collectionId}` of the parent for that collection.
The property is omitted or set to a _null_ value for top-level collections.

include::requirements/hierarchy/REQ_parent_property.adoc[]

Although not required, it is recommended that the identifier of children collections start by their parent collection identifier,
followed by a specific separator (such as the colon `:`), followed by their distinctive part.
Programmatic clients should not establish the hierarchical relationships based on the presence of that separator nor of the parent collecton identifier
within a collection identifier, but it is a useful hint for users, including to allow editing the URLs of a collection in a browser's address bar to directly access the parent collection.

include::recommendations/hierarchy/REC_parent_convention.adoc[]

In the HTML representation of a collection description resource (`/collections/{collectionId}`), it can be useful to directly show the
list of children collections, allowing a user to directly click and explore the hierarchy this way.
For programmatic clients, a separate `/collections?parent={parentId}` request is performed instead to retrieve the list of children collections (see below).

include::recommendations/hierarchy/PER_collection_children.adoc[]

Example of a collection description response for `/collections/{collectionId}`:

```json
{
   "id": "can:qc:mtl",
   "parent": "can:qc",
   "links": [
      { "rel": "self", "/collections/can:qc:mtl" },
      { "rel": "items", "href": "/collections/can:qc:mtl/items" },
      { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:mtl/map" },
      { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:mtl/tiles" }
   ],
   ...
}
```

Example of a hierarchical collection listing response for `/collections`:

```json
{
   "collections": [
      {
         "id": "can",
         "links": [
            { "rel": "self", "href": "/collections/can" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can/map" }
         ]
      },
      {
         "id": "usa",
         "links": [
            { "rel": "self", "href": "/collections/usa" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa/map" }
         ]
      },
      {
         "id": "can:qc", "parent": "can",
         "links": [
            { "rel": "self", "href": "/collections/can:qc" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc/tiles" }
         ]
      },
      {
         "id": "can:on", "parent": "can",
         "links": [
            { "rel": "self", "href": "/collections/can:on" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on/tiles" }
         ]
      },
      {
         "id": "usa:ny", "parent": "usa",
         "links": [
            { "rel": "self", "href": "/collections/usa:ny" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa:ny/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/usa:ny/tiles" }
         ]
      },
      {
         "id": "usa:ca", "parent": "usa",
         "links": [
            { "rel": "self", "href": "/collections/usa:ca" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa:ca/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/usa:ca/tiles" }
         ]
      },
      {
         "id": "can:qc:qc", "parent": "can:qc",
         "links": [
            { "rel": "self", "href": "/collections/can:qc:qc" },
            { "rel": "items", "href": "/collections/can:qc:qc/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:qc/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:qc/tiles" }
         ]
      },
      {
         "id": "can:qc:mtl", "parent": "can:qc",
         "links": [
            { "rel": "self", "href": "/collections/can:qc:mtl" },
            { "rel": "items", "href": "/collections/can:qc:mtl/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:mtl/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:mtl/tiles" }
         ]
      },
      {
         "id": "can:on:tor", "parent": "can:on",
         "links": [
            { "rel": "self", "href": "/collections/can:on:tor" },
            { "rel": "items", "href": "/collections/can:on:tor/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on:tor/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on:tor/tiles" }
         ]
      },
      {
         "id": "can:on:ott", "parent": "can:on",
         "links": [
            { "rel": "self", "href": "/collections/can:on:ott" },
            { "rel": "items", "href": "/collections/can:on:ott/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on:ott/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on:ott/tiles" }
         ]
      },
      {
         "id": "usa:ny:ny", "parent": "usa:ny",
         "links": [
            { "rel": "self", "href": "/collections/usa:ny:ny" },
            { "rel": "items", "href": "/collections/usa:ny:ny/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa:ny:ny/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/usa:ny:ny/tiles" }
         ]
      },
      {
         "id": "usa:ny:su", "parent": "usa:ny",
         "links": [
            { "rel": "self", "href": "/collections/usa:ny:su" },
            { "rel": "items", "href": "/collections/usa:ny:su/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa:ny:su/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/usa:ny:su/tiles" }
         ]
      },
      {
         "id": "usa:ca:sf", "parent": "usa:ca",
         "links": [
            { "rel": "self", "href": "/collections/usa:ca:sf" },
            { "rel": "items", "href": "/collections/usa:ca:sf/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa:ca:sf/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/usa:ca:sf/tiles" }
         ]
      },
      {
         "id": "usa:ca:sd", "parent": "usa:ca",
         "links": [
            { "rel": "self", "href": "/collections/usa:ca:sd" },
            { "rel": "items", "href": "/collections/usa:ca:sd/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa:ca:sd/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/usa:ca:sd/tiles" }
         ]
      }
   ]
   ...
}
```

=== `parent` query parameter for `/collections`

A `parent` query parameter is defined to filter the list of collections returned to only those whose immediate parent is identified by the specified parent id.

A special value of `none` (which must be avoided as a collection id) takes the special meaning of returning only the top-level collections without a parent.

include::requirements/hierarchy/REQ_parent_parameter.adoc[]

In order to allow implementations and deployments to present a list of collections in a hierarchical manner by default in a browser,
a permission specific to an HTML representation is introduced.
Since such an HTML representation is not primarily intended for consumption by programmatic clients, this should not impact compatibility with clients not implementing this extension.

include::recommendations/hierarchy/PER_parent_default_html.adoc[]

Example response, based on the hierarchical collections listed earlier, for `/collections?parent=none`:

```json
{
   "collections": [
      {
         "id": "can",
         "links": [
            { "rel": "self", "href": "/collections/can" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can/map" }
         ]
      },
      {
         "id": "usa",
         "links": [
            { "rel": "self", "href": "/collections/usa" },
            { "rel": "[ogc-rel:map]", "href": "/collections/usa/map" }
         ]
      }
   ]
   ...
}
```

Example response, based on the hierarchical collections listed earlier, for `/collections?parent=can`:

```json
{
   "collections": [
      {
         "id": "can:qc", "parent": "can",
         "links": [
            { "rel": "self", "href": "/collections/can:qc" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc/tiles" }
         ]
      },
      {
         "id": "can:on", "parent": "can",
         "links": [
            { "rel": "self", "href": "/collections/can:on" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on/tiles" }
         ]
      }
   ]
   ...
}
```

Example response, based on the hierarchical collections listed earlier, for `/collections?parent=can:qc`:

```json
{
   "collections": [
      {
         "id": "can:qc:qc", "parent": "can:qc",
         "links": [
            { "rel": "self", "href": "/collections/can:qc:qc" },
            { "rel": "items", "href": "/collections/can:qc:qc/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:qc/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:qc/tiles" }
         ]
      },
      {
         "id": "can:qc:mtl", "parent": "can:qc",
         "links": [
            { "rel": "self", "href": "/collections/can:qc:mtl" },
            { "rel": "items", "href": "/collections/can:qc:mtl/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:mtl/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:mtl/tiles" }
         ]
      },
   ]
   ...
}
```

=== `ancestor` query parameter for `/collections`

An `ancestor` query parameter is also defined to filter the list of collections returned to only those having parent identified by the specified parent id as an ancestor.

include::requirements/hierarchy/REQ_ancestor_parameter.adoc[]

Example response, based on the hierarchical collections listed earlier, for `/collections?ancestor=can`:

```json
{
   "collections": [
      {
         "id": "can:qc", "parent": "can",
         "links": [
            { "rel": "self", "href": "/collections/can:qc" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc/tiles" }
         ]
      },
      {
         "id": "can:on", "parent": "can",
         "links": [
            { "rel": "self", "href": "/collections/can:on" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on/tiles" }
         ]
      },
      {
         "id": "can:qc:qc", "parent": "can:qc",
         "links": [
            { "rel": "self", "href": "/collections/can:qc:qc" },
            { "rel": "items", "href": "/collections/can:qc:qc/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:qc/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:qc/tiles" }
         ]
      },
      {
         "id": "can:qc:mtl", "parent": "can:qc",
         "links": [
            { "rel": "self", "href": "/collections/can:qc:mtl" },
            { "rel": "items", "href": "/collections/can:qc:mtl/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:qc:mtl/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:qc:mtl/tiles" }
         ]
      },
      {
         "id": "can:on:tor", "parent": "can:on",
         "links": [
            { "rel": "self", "href": "/collections/can:on:tor" },
            { "rel": "items", "href": "/collections/can:on:tor/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on:tor/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on:tor/tiles" }
         ]
      },
      {
         "id": "can:on:ott", "parent": "can:on",
         "links": [
            { "rel": "self", "href": "/collections/can:on:ott" },
            { "rel": "items", "href": "/collections/can:on:ott/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/can:on:ott/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/can:on:ott/tiles" }
         ]
      }
   ]
   ...
}
```

The following example query demonstrates combining filtering by ancestor with capabilities defined in "Searchable Collections" to look for collections related to precipitations
in a hierarchy within the descendants of a collection with the identifier `canada`:

```
GET /collections?ancestor=canada&q=precipitations
```
