[[rc-collections-section]]
== Requirements Class "Collections"
:sectnums:

include::requirements/requirements_class_collections.adoc[]

include::requirements/collections/REQ_dependency-HTTP.adoc[]

include::recommendations/collections/REC_dependency-core.adoc[]

include::recommendations/collections/REC_dependency-landing-page.adoc[]

This Requirements Class describes the resources and operations used to describe and access resource collections exposed through an OGC Web API. This class does not include any requirements about how resources are aggregated into collections nor about the aggregated resources themselves. That detail is reserved for resource-specific OGC Web API standards (see <<views-introduction,Views Section>>).

The two resources and their operations are defined in this Requirements Class. They are summarized in <<collection-resources>>. 

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<collections-metadata,Collections>> |/collections ^|GET |Information which describes the set of available Collections 
|<<collection-description,Collection>> |/collections/{collectionId} ^|GET |Information about a specific collection of geospatial data with links to distribution
|===

[[collections-metadata]]
=== Collections

OGC APIs typically organize their Spatial Resources into collections. Information about those collections is accessed through the `/collections` path and the http://www.opengis.net/def/rel/ogc/1.0/data link relation.

==== Operation

include::requirements/collections/REQ_rc-md-op.adoc[]

==== Response

include::requirements/collections/REQ_rc-md-success.adoc[]

The collections response returned by this operation is based on the link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collections.yaml[collections.yaml] JSON schema. Examples of collections responses are provided in <<collections-metadata-examples>>.

.collections.yaml
[source, YAML]
include::openapi/schemas/collections.yaml[]

This Collections schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-descriptions.adoc[]

The `timeStamp` property of the Collections response indicates when the response was generated.

include::requirements/collections/REQ_rc-timeStamp.adoc[]

The `collections` property of the Collections response provides a description of each individual collection hosted by the API. 

include::requirements/collections/REQ_rc-md-items.adoc[]

The array items included in the `collection` property are described in the <<collection-description,Collection Resource>> section of this Requirements Class.

This Requirements Class does not define any parameters for use against a `collections` resource. Implementers who wish to support filtering of the collections to be included in a result set should implement the   <<rc-simple-query-section,Simple Query>> Conformance Class for that purpose.

==== Error situations

See <<http-status-codes>> for general guidance.

[[collection-description]]
=== Resource Collection

Each resource collection is described by a set of metadata. That metadata can be accessed directly using the `/collections/{collectionId}` path and as an entry in the `collections` property of the `/Collections` resource.

==== Operation

include::./requirements/collections/REQ_src-md-op.adoc[]

==== Response

include::./requirements/collections/REQ_src-md-success.adoc[]

==== Error Situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collection-resource-definition-section]]
==== Collection Resource Definition

include::../api_modules/collection/requirements_module_collection.adoc[]

