[[rc-umd-collection-section]]
== Requirements Class "Uniform Multi-Dimension Collection"
:sectnums:

include::requirements/requirements_class_umd-collection.adoc[]

The <<rc-collections,Collections>> Requirements Class defines a <<collection-resource-definition-section,Collection>> resource which supports both geospatial and temporal dimensions.
However, the domain of some datasets cannot be fully described with only spatiotemporal dimensions.
The <<rc-umd-collection-section,Uniform Multi-Dimension Collection>> Requirements Class extends the <<collection-resource-definition-section,Collection>> resource to support an unlimited number of
dimensions defined in a uniform manner, so that clients supporting this requirements class can interpret these dimensions in a generic manner.

[[umd-collection-definition]]
=== Uniform description of all dimensions

The Uniform Multi-Dimension Collection is an extension of the <<collection-resource-definition-section,Collection>> resource.

This requirement class allows the definition of additional dimensions beyond spatial and temporal in a specific way which is consistent with the spatial and temporal dimensions.

Each dimension is identified by using a semantic `definition` property.
An `interval` providing the lower and upper bound for the coordinates along that dimension also needs to be included, as well as a `unit` of measure where applicable.

As an alternative or in addition to the `definition`, a temporal reference system (`trs`) or a vertical reference system (`vrs`) can be specified.
The `trs` or `vrs` property can be populated with either a URI or CURIE, a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition of the reference system, or a JSON encoding of the CRS
(using the PROJ JSON schema or a potential "CRS JSON" successor once defined by the OGC).

NOTE: If a 3D CRS exists including the vertical dimension, that CRS should be used inside the "spatial" object of the extent, instead of defining a separate vertical dimension using `vrs`.
For vertical CRSes corresponding to the concept of a variable, such as a pressure level, the semantic definition for that variable should be used instead of `vrs`.

For additional dimensions beyond spatial and temporal, the reference system is defined as a combination of the `definition` and `unit`, or alternatively the `trs` or `vrs`.
In addition to specifying the reference system of the `interval`, this also specifies the reference system of that dimension for the data itself.
Unlike the spatial CRS, the collection description in this standard only supports defining a single reference system for the temporal dimension and each additional dimension.

To validate against this UMD Requirements Class, the `- type: object` line within the `anyOf:` in the
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/extent.yaml[extent.yaml] YAML JSON Schema of the collection description's extent should be commented out.

include::requirements/umd-collection/REQ_extent-uad-definition.adoc[]

=== Describing gridded dimensions

For data which is gridded, whether using a regular or irregular grid, this conformance class defines a `grid` property which is used to describe such grids.

While the `interval` specified for the dimension (or `bbox` for spatial dimensions) describes the region occupied by all cells, including the region of validity or bounds of all measurements,
this grid property describes in more details each individual measurement.

Common types of grids are often called _Measure-is-Area_ or _Measure-is-Point_, but especialy in the case of sensor measurements, other situations in-between are also possible.

==== Regular grids

A regular grid has data measurements separated by a constant distance (the resolution of the grid), while for an irregular grid the distance between data measurements varries.
For both cases, the number of cells (`cellsCount`) is specified. A cell is a region within which a particular measurement is valid.

The bounds are specified as `relativeBounds` which are relative to points starting from a `firstCoordinate` separated by an equal distance of `resolution` units.
The lower value for the `interval` for a particular dimension (or `bbox` in the case of spatial dimensions) corresponds to the `firstCoordinate` plus the first value of the `relativeBounds`, while
the upper value corresponds to the `firstCoordinate` plus `cellsCount` times the `resolution` plus the second value of the `relativeBounds`.

For example, a regular grid where each measure is associated with infinitely small points would have `relativeBounds` of `[0, 0]`.
With a `cellsCount` of 3, a `resolution` of 0.5, and a `firstCoordinate` at 0, the corresponding `interval` would be `[0, 1]`.

.Diagram illustrating a _Measure-is-Point_ regular grid
[source]
----
 0.0     0.5     1.0
  |       |       |
  *       *       *
----

When each measure is associated with an area filling entire cells, there could be multiple ways to define the same grid
based on a preference of how the coordinate points are defined. Consider the following regular grids, with a `cellsCount` of 2, a `resolution` of `0.5`, and an interval of `[0, 1]`.

.Diagram illustrating a _Measure-is-Area_ regular grid
[source]
----
 0.0      0.5     1.0
  |        |       |
  [========|=======]
----

One way to describe this grid would be with the `firstCoordinate` at 0 and the relativeBounds as `[0, 0.5]`.

Another equivalent way to describe the same grid would a `firstCoordinate` at 0.25 and the relativeBounds as `[-0.25, 0.25]`.

If the `relativeBounds` property is not provided, the default relative bounds of the cells are assumed to be `[-resolution/2, resolution/2]`.
In other words, the cell, or the region of validity of the measurement, is centered on each repeating point starting from the `firstCoordinate`.

For a _Measure-is-Area_ grid, the `interval` (or `bbox` for the spatial dimensions) will be `resolution/2` larger in each direction compared to the same number of cells and same resolution
representing _Measure-is-Point_ values.

==== Irregular grids

Irregular grids are described by explicitly listing a sequence of `coordinates` (one for each cell).

Bounds for each coordinates can also be individually specified in a parallel `boundsCoordinates` array.

If the `boundsCoordinates` property is not included, the default bounds of the cells are assumed to lie in the middle of the two values specified in coordinates, and for the two extremities,
the lower (for the first cell) and upper bounds (for the last cell) are assumed to be at the same distance from the specified coordinate as to their immediate neighbor.

==== Requirements for describing grids

include::requirements/umd-collection/REQ_grid-description.adoc[]

include::recommendations/umd-collection/PER_categorical_dimension_interval.adoc[]
