[[rc-searchable-collections]]
== Requirements Class "Searchable Collections"
:sectnums:

include::requirements/requirements_class_searchable_collections.adoc[]

This Requirements Class describes query parameters that can be used to discover and select resource collections exposed through an OGC Web API.

Implementers of this Requirements Class must also implement the `/Collections` Requirements Class.

include::requirements/searchable-collections/REQ_dependency-collections.adoc[]

[[parameter-requirements]]
=== Parameter Requirements

Query parameters are used in URIs to limit the resources which are returned on a GET request. The OGC API - Common - Part 2: Geospatial Data Standard identifies three query parameters for use in OGC API standards:

* <<bbox-parameter-requirements,bbox>>: Bounding Box
* <<parameter-datetime-requirements,datetime>>: Date and Time
* <<limit-parameter-requirements,limit>>: Response resource count limit

The behavior generated by these parameters is specific to the operation and resource upon which they are applied. Those behaviors are described for each resource type and operation in the <<target-resource-requirements,Target Resource Requirements>> section.

Use of these query parameters with any specific operation is optional. Developers of OGC API-Geospatial Data servers should document their supported parameters in the API definition as describe in <<apicore,API-Core>>.

[[bbox-parameter-requirements]]
==== Parameter bbox

The `bbox` parameter is used to select resources based on the geospatial footprint or extent.

The `bbox` parameter is defined as follows:

include::./requirements/searchable-collections/REQ_rc-bbox-definition.adoc[]

While the processing of the `bbox` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::./requirements/searchable-collections/REQ_rc-bbox-response.adoc[]

"Intersects" means that a coordinate that is part of the spatial geometry of the resource falls within the area specified in the parameter `bbox`. This includes the boundaries of the geometries. For curves the boundary includes the start and end position. For surfaces the boundary includes the outer and inner rings.

In case of a degenerate bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all resources match where the geometry intersects with this point.

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a later version of this standard.

The bounding box for WGS 84 longitude/latitude is, in most cases, the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian (180th meridian) the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

Note that the server will return an error if a latitude value of ``160.0`` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/bbox.yaml[bbox.yaml].

[[datetime-parameter-requirements]]
==== Parameter datetime

The `datetime` parameter selects resources based on their temporal extent. The definition of temporal extent is specific to the resource type being filtered.

The `datetime` parameter is defined as follows:

include::./requirements/searchable-collections/REQ_rc-datetime-definition.adoc[]

While the processing of the `datetime` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::./requirements/searchable-collections/REQ_rc-datetime-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`datetime=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (such as `lastUpdate`), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/datetime.yaml[datetime.yaml].


[[limit-parameter-requirements]]
==== Parameter limit

The `limit` parameter limits the number of resources that can be returned in a single response.

include::./requirements/searchable-collections/REQ_rc-limit-definition.adoc[]

While the processing of the `limit` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::./requirements/searchable-collections/REQ_rc-limit-response.adoc[]

The number of resources returned depends on the server and the value of the `limit` parameter.

*   The client can request a limit to the number of resources returned.
*   The server may have a default value for the limit, and a maximum limit.
*   If the server has any more results available than it returns (the number it returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

include::./recommendations/searchable-collections/PER_rc-server-limit.adoc[]

Since many servers will place a limit on the size of their responses, clients should be prepared to handle a paged response even if they have not specified a `limit` parameter in their query.

The effect of the limit parameter is to divide the response into a number of pages. Each page (except for the last) contains the specified number of entities. The response contains the first page. Additional pages can be accessed through hyperlink navigation.

include::./recommendations/searchable-collections/REC_rc-next-1.adoc[]

include::./recommendations/searchable-collections/REC_rc-next-2.adoc[]

include::./recommendations/searchable-collections/REC_rc-next-3.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::./recommendations/searchable-collections/PER_rc-prev.adoc[]

[[target-resource-requirements]]
=== Target Resource Requirements

The target of the parameters defined in this conformance class is the <<collection-description,Collection>> resource described in the <<rc-collections-section,Collections>> Requirements Class. The purpose of these parameters is to select a subset of <<collection-description,Collection>> resources to be included in the response to a <<collections-metadata,/collections>> request.

Three parameters are defined for use with the <<collections-metadata,Collections>> resource. These parameters subset the set of <<collection-description,Collection>> entries returned based on spatial, temporal, and volumetric filters. These parameters are documented in the <<parameter-requirements,Parameter Requirements>> section.

The `collections` property of the Collections response provides a description of each individual collection hosted by the API. These descriptions are based on the link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collectionDesc.yaml[Resource Collection Schema]. This schema is described in detail in the <<collection-resource-definition-section,Resource Collection Description>> section of this Standard.

==== Spatial and Temporal Filtering

A client may select a subset of the hosted collections using the <<bbox-parameter-requirements,`bbox`>> and the <<datetime-parameter-requirements,`datetime`>> parameter. These parameters are evaluated against the `extent` element of each Collection item in the Collections response.

The requirements governing the processing of these parameters are:

include::requirements/searchable-collections/REQ_rc-bbox-collection-response.adoc[]

include::requirements/searchable-collections/REQ_rc-datetime-collection-response.adoc[]

==== Volumetric Filtering

The client may limit the number of collections returned in a response by using the `limit` parameter. When applied against the `/collections` resource, the <<limit-parameter-requirements,`limit`>> parameter indicates the maximum number of collections which should be included in a single response.

include::requirements/searchable-collections/REQ_rc-limit-collection-response.adoc[]

The server also has the option of limiting the size of the Collections response.

include::recommendations/searchable-collections/PER_rc-md-items.adoc[]

==== Paged Response

If the collections response does not contain all of the collection resources available from this server, then the client should be informed of that fact.

include::recommendations/searchable-collections/REC_rc-paged-response.adoc[]

The `numberMatched` property of the Collections response indicates the number of Collection items included in the Collections response. This may be a subset of the total set of collections hosted by the API. Selection of which collections to include in a subset is controlled through the <<bbox-parameter-requirements,`bbox`>>, <<datetime-parameter-requirements,`datetime`>> and other selection parameters provided by the client.

include::requirements/searchable-collections/REQ_rc-numberMatched.adoc[]

The number of collection items included in a Collections response may be a subset of the number matched. In that case, the `numberReturned` property of the Collections response indicates the number of collection items returned in this "page" of the Collections response.

include::requirements/searchable-collections/REQ_rc-numberReturned.adoc[]

If the Collections response contains a subset of the selected collection items (numberReturned is less than numberMatched) then the Collections response should contain links for navigating to the rest of the collection items as described in the <<limit-parameter-requirements,limit parameter>> section.

