[[rc-umd-collection-section]]
== Requirements Class "Uniform Multi-Dimension Collection"
:sectnums:

include::requirements/requirements_class_umd-collection.adoc[]

The <<rc-collections,Collections>> Requirements Class defines a <<collection-resource-definition-section,Collection>> resource which supports both geospatial and temporal dimensions.
However, the domain of some datasets cannot be fully described with only spatiotemporal dimensions.
The <<rc-umd-collection-section,Uniform Multi-Dimension Collection>> Requirements Class extends the <<collection-resource-definition-section,Collection>> resource to support an unlimited number of
dimensions defined in a uniform manner, so that clients supporting this requirements class can interpret these dimensions in a generic manner.

[[umd-collection-definition]]
=== Uniform Multi-Dimension Collection Definition

The Uniform Multi-Dimension Collection is an extension of the <<collection-resource-definition-section,Collection>> resource.

include::requirements/umd-collection/REQ_extent-uad-definition.adoc[]

include::recommendations/umd-collection/PER_categorical_dimension_interval.adoc[]

This requirement class allows the definition of additional dimensions by specifiying a temporal reference system (`trs`), a vertical reference system (`vrs`) or a semantic `definition` property,
an interval providing the lower and upper bound for the coordinates along that dimension, as well as a `unit` of measure where applicable.

The `trs` or `vrs` property can be populated with either a URI or CURIE, a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition of the reference system, or a JSON encoding of the CRS
(using the PROJ JSON schema or a potential "CRS JSON" successor once defined by the OGC).

NOTE: If a 3D CRS exists including the vertical dimension, that CRS should be used inside the "spatial" object of the extent, instead of defining a separate vertical dimension using `vrs`.
For vertical CRSes corresponding to the concept of a variable, such as a pressure level, the semantic definition for that variable should be used instead of `vrs`.

To validate against this UMD Requirements Class, the `- type: object` line within the `anyOf:` in the
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/extent.yaml[extent.yaml] YAML JSON Schema of the collection description's extent should be commented out.

