[[rc-uad-collections-section]]
== Requirements Class "Uniform Additional Dimensions Collections"
:sectnums:

include::requirements/requirements_class_uad-collections.adoc[]

The <<rc_collections,Collections>> Requirements Class defines a <<collection-resource-definition-section,Collection>> resource which supports both geospatial and temporal dimensions.
However, the domain of some datasets cannot be fully described with only spatiotemporal dimensions.
The <<rc-uad-collections-section,Uniform Additional Dimensions Collections>> Requirements Class extends the <<collection-resource-definition-section,Collection>> resource to support an unlimited number of
dimensions defined in a uniform manner, so that clients supporting this requirements class can interpret these dimensions in a generic manner.

[[uad-collections-definition]]
=== Uniform description of all dimensions

A Uniform Additional Dimensions Collection is an extension of the <<collection-resource-definition-section,Collection>> resource.

This requirements class supports the definition of additional dimensions beyond spatial and temporal in a specific way which is consistent with the spatial and temporal dimensions.

Each dimension is identified by using a semantic `definition` property.
An `interval` providing the lower and upper bound for the coordinates along that dimension also needs to be included, as well as a `unit` of measure where applicable.

As an alternative - or in addition to - the `definition`, a temporal reference system (`trs`) or a vertical reference system (`vrs`) can be specified.
The `trs` or `vrs` property can be populated with either a URI or CURIE.

The following table lists all properties defined as part of a uniform additional dimension's extent.

[#otherdimensionextent-properties,reftext='{table-caption} {counter:table-num}']
.JSON OtherDimensionExtent Properties
[cols="1,1,3", options="header"]
|===
| Name (as encoded in JSON) | JSON Type | Definition

| **definition**
| String (URI)
| **_(at least one of `definition`, `trs`, `vrs` is required)_** A URI for the definition of the measured or observed property corresponding to this dimension

| **unit**
| String
| The unit of measure in which the interval and/or grid values are expressed

| **trs**
| String (URI, CURIE or https://www.opengis.net/doc/is/crs-wkt/2.1.11[WKT2CRS]) or object (https://proj.org/en/stable/specifications/projjson.html[PROJJSON] or https://github.com/opengeospatial/CRS-JSON-Encoding[CRS JSON])
| **_(at least one of `definition`, `trs`, `vrs` is required)_** Temporal Coordinate Reference System (e.g. as defined by Features for 'temporal'). This should be a URI to a registered TRS if one is available, or a full
description of the TRS otherwise using e.g., a WKT2CRS string, or a PROJJSON, or CRS JSON object.

| **interval**
| Array of (at least 1) Array of 2 (Real or String)
| **_(required)_** One or more intervals that describe the extent for this dimension of the dataset. The value `null` is supported and indicates an unbounded or half-bounded
interval. The first interval describes the overall extent of the data for this dimension. All subsequent intervals describe more precise intervals,
e.g., to identify clusters of data. Clients only interested in the overall extent will only need to access the first item (a pair of lower and upper bound
values).

| **grid**
| <<regulargrid-properties,RegularGrid>> or <<irregulargrid-properties,IrregularGrid>>
| Grid description providing information about the limited availability of data within the collection organized as a grid (regular or irregular) along the
temporal dimension.

| **unitLang**
| String
| The language (or vocabulary) in which the unit is expressed (defaults to "UCUM" if not specified).

| **variableType**
| VariableType (`continuous`, `numericalOrdinal`, `numericalNominal`, `categoricalOrdinal`, `categoricalNominal`)
| The type of variable which may inform correct interpretation and interpolation methods

| **vrs**
| String (URI, CURIE or https://www.opengis.net/doc/is/crs-wkt/2.1.11[WKT2CRS]) or object (https://proj.org/en/stable/specifications/projjson.html[PROJJSON] or https://github.com/opengeospatial/CRS-JSON-Encoding[CRS JSON])
a| **_(at least one of `definition`, `trs`, `vrs` is required)_** Vertical Coordinate Reference System (e.g. as defined in EDR for 'vertical'). This should be a URI to a registered VRS if one is available, or a full
description of the VRS otherwise using e.g., a WKT2CRS string, or a PROJJSON, or CRS JSON object.

NOTE: This property is included mainly for compatibility with https://docs.ogc.org/is/19-086r6/19-086r6.html[OGC API - Environmental Data Retrieval (EDR)].
A true vertical CRS such as height above the ellipsoid would normally be the third dimension of the <<spatialextent-properties,`spatial` extent>>,
while a dimension representing a parameter such as pressure would more accurately be described as a parametric CRS, and would generally be described using the
semantic `definition` and `unit` properties.
|===

For additional dimensions beyond spatial and temporal, the reference system is defined as a combination of the `definition` and `unit`, or alternatively the `trs` or `vrs`.
In addition to specifying the reference system of the `interval`, this also specifies the reference system of that dimension for the data itself.
Unlike the spatial CRS, the collection description in this standard only supports defining a single reference system for the temporal dimension and each additional dimension.

To validate against this Uniform Additional Dimensions Collections Requirements Class, the
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc-UAD.yaml[collectionDesc-UAD.yaml]
collection description YAML JSON Schema including
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/extent-UAD.yaml[extent-UAD.yaml]
should be used instead of
https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml[collectionDesc.yaml]

include::requirements/uad-collections/REQ_extent-uad-definition.adoc[]

=== Describing gridded dimensions

For gridded data, whether using a regular or an irregular grid, this requirements class defines a `grid` property which is used to describe such grids.

While the `interval` specified for the dimension (or `bbox` for spatial dimensions) describes the region occupied by all cells, including the region of validity or bounds of all measurements,
this grid property describes in more detail each individual measurement.

Common types of grids are often called _Value-is-Area_ or _Value-is-Point_, but especially in the case of sensor measurements, other situations in-between are also possible.

==== Regular grids

A regular grid has data measurements separated by a constant distance (the resolution of the grid), while for an irregular grid the distance between data measurements varies.
For both cases, the number of cells (`cellsCount`) is specified. A cell is a region within which a particular measurement is valid.

The bounds are specified as `relativeBounds` which are relative to points starting from a `firstCoordinate` separated by an equal distance of `resolution` units.
The lower value for the `interval` for a particular dimension (or `bbox` in the case of spatial dimensions) corresponds to the `firstCoordinate` plus the first value of the `relativeBounds`, while
the upper value corresponds to the `firstCoordinate` plus `cellsCount` times the `resolution` plus the second value of the `relativeBounds`.

The following table lists all properties defined as part of a regular grid.

[#regulargrid-properties,reftext='{table-caption} {counter:table-num}']
.JSON RegularGrid Properties
[cols="1,1,3", options="header"]
|===
| Name (as encoded in JSON) | JSON Type | Definition

| **cellsCount**
| Integer (positive)
| **_(required)_** Number of samples available along the dimension

| **resolution**
| Real or String
| **_(required)_** Resolution of regularly gridded data along the dimension in the collection

| **firstCoordinate**
| Real or String
| **_(required)_** First coordinate where a regular grid begins, with subsequent coordinates adding `resolution` unit at each step

| **relativeBounds**
| Array of 2 (Real or String)
| Distance in units from coordinate to the lower and upper bounds of each cell for regular grids, describing the geometry of the cells

| **availableResolutions**
| Array of (Real or String)
| List of resolutions made available by the API. If not specified, there are no limit other than the limits indicated in `minCellSize` and `maxCellSize` of the collection description (though the API might still allow requesting data beyond these).
|===

For example, a regular grid where each measure is associated with infinitely small points would have `relativeBounds` of `[0, 0]`.
With a `cellsCount` of 3, a `resolution` of 0.5, and a `firstCoordinate` at 0, the corresponding `interval` would be `[0, 1]`.

.Diagram illustrating a _Value-is-Point_ regular grid
[source]
----
 0.0     0.5     1.0
  |       |       |
  *       *       *
----

When each measure is associated with an area filling entire cells, there could be multiple ways to define the same grid
based on a preference of how the coordinate points are defined. Consider the following regular grids, with a `cellsCount` of 2, a `resolution` of `0.5`, and an interval of `[0, 1]`.

.Diagram illustrating a _Value-is-Area_ regular grid
[source]
----
 0.0      0.5     1.0
  |        |       |
  [========|=======]
----

One way to describe this grid would be with the `firstCoordinate` at 0 and the relativeBounds as `[0, 0.5]`.

Another equivalent way to describe the same grid would be a `firstCoordinate` at 0.25 and the relativeBounds as `[-0.25, 0.25]`.

If the `relativeBounds` property is not provided, the default relative bounds of the cells are assumed to be `[-resolution/2, resolution/2]`.
In other words, the cell, or the region of validity of the measurement, is centered on each repeating point starting from the `firstCoordinate`.

For a _Value-is-Area_ grid, the `interval` (or `bbox` for the spatial dimensions) will be `resolution/2` larger in each direction compared to the same number of cells and same resolution
for a _Value-is-Point_ grid.

==== Irregular grids

Irregular grids are described by explicitly listing a sequence of `coordinates` (one for each cell) along each irregularly gridded dimension(s).

Bounds for each coordinate can also be individually specified in a parallel `boundsCoordinates` array.

If the `boundsCoordinates` property is not included, the default bounds of the cells are assumed to lie in the middle of the two values specified in `coordinates`, and for the two extremities,
the lower (for the first cell) and upper bounds (for the last cell) are assumed to be at the same distance from the specified coordinate as to their immediate neighbor.

The following table lists all properties defined as part of a regular grid.

[#irregulargrid-properties,reftext='{table-caption} {counter:table-num}']
.JSON IrregularGrid Properties
[cols="1,1,3", options="header"]
|===
| Name (as encoded in JSON) | JSON Type | Definition

| **cellsCount**
| Integer (positive)
| **_(required)_** Number of samples available along the dimension

| **coordinates**
| Array of (Real or String)
| **_(required)_** List of coordinates along the dimension for which data organized as an irregular grid in the collection is available.

| **boundsCoordinates**
| Array of Array of 2 (Real or String)
| For irregular grids, an ordered list of the coordinates in absolute units of the lower and upper bounds of the dimension for each cell.
|===

==== Requirements for describing grids

include::requirements/uad-collections/REQ_grid-description.adoc[]

include::recommendations/uad-collections/PER_categorical_dimension_interval.adoc[]
