[[rc-filterable-collections]]
== Requirements Class "Filtering Collections with CQL2"
:sectnums:

include::requirements/requirements_class_filtering.adoc[]

This Requirements Class describes query parameters that can be used to discover and select collections exposed through an OGC Web API, by using an OGC Common Query Language filter expression.

[[filtering-overview]]
=== Overview

This "Filtering Collections with CQL2" defines query parameters which can be used with the `/collections` endpoint (described in the <<rc-collections-section,Collections>> Requirements Class)
to select which collections to return on a GET request:

* <<filtering-filter-parameter,filter>>: The expression used as a filter
* <<filtering-filter-lang-parameter,filter-lang>>: The language used to experss the filter (e.g., CQL2-JSON or CQL2-Text)

If implementing https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1: Core] "Landing Page", these supported query parameters need to be described in the API definition as described in that part.

[[filtering-api-records]]
=== OGC API - Records compliance

When implementing this "Filtering Collections with CQL2" requirement class, the `/collections` end-point can be considered a _Local Resource Catalog_, where the local resources are the collections being cataloged.

This requirement class is consistent with the requirements of https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog_filtering[OGC API - Records - Part 1: Core "Local Resources Catalog - Filtering" (Deployment)].
An implementation may gain additional interoperability by conforming to that requirement class from OGC API - Records as well.
In this case, the implementation should verify and declare conformance with these seven conformance classes defined in Records corresponding to the following URIs:

[cols="2,7",options="header"]
|===
| OGC API - Records Requirements Class | URI
| https://docs.ogc.org/DRAFTS/20-004.html#clause-record-core[Record Core]                                                   | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-core
| https://docs.ogc.org/DRAFTS/20-004.html#clause-record-collection[Record Collection]                                       | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/record-collection
| https://docs.ogc.org/DRAFTS/20-004.html#clause-crawlable-catalog[Crawlable Catalog]                                       | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/crawlable-catalog
| https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog[Local Resources Catalog]                           | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/local-resources-catalog
| https://docs.ogc.org/DRAFTS/20-004.html#clause-autodiscovery[Autodiscovery]                                               | http://www.opengis.net/spec/ogcapi-records-1/1.0/conf/autodiscovery
| https://docs.ogc.org/DRAFTS/20-004.html#clause-filtering[Filtering]                                                       | http://www.opengis.net/spec/ogcapi-records-1/1.0/req/filtering
| https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog_filtering[Local Resources Catalog - Filtering]     | http://www.opengis.net/spec/ogcapi-records-1/1.0/req/local-resources-catalog/filtering
|===

The additional requirements include linking to the `/collections` end-point with an `http://www.opengis.net/def/rel/ogc/1.0/ogc-catalog` link relation from the landing page.

[[filtering-filter-parameter]]
=== Parameter `filter`


[[filtering-filter-lang-parameter]]
=== Parameter `filter-lang`
