:req-class: schemas
[#rc_{req-class}]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/req/schemas
|Target type |Web API
|Dependency |<<jschema,JSON Schema: A Media Type for Describing JSON Documents>>
|Indirect Dependency |<<json-schema-validation,JSON Schema Validation: A Vocabulary for Structural Validation of JSON>>
|Indirect Dependency |<<ogc06_103r4,Simple feature access - Part 1: Common architecture>>
|Indirect Dependency |<<ucum,The Unified Code for Units of Measure>>
|Indirect Dependency |<<qudt,QUDT Ontologies, derived models and vocabularies>>
|===

[#schema-representation]
=== Schema representation

:req: json-schema
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The schema SHALL be a valid JSON Schema.
^|B |The schema SHALL have the following characteristics:

* "$schema" is "\https://json-schema.org/draft/2020-12/schema";
* "$id" is a HTTP(S) URI without query parameters that returns the schema, if requested with the header "Accept: application/schema+json"; and
* "type" is "object".
|===

In addition to the JSON Schema data types, geospatial data typically also uses spatial and temporal data types.

:req: properties
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |Each property SHALL include a "type" member, except for spatial properties.
^|B |Each spatial property SHALL not include a "type" or "$ref" member.
^|C |Each spatial property SHALL include a "format" member with a string value "geometry", followed by a hyphen, followed by the name of the geometry type in lower case. I.e., the values for the Simple Feature geometry types are: "geometry-point", "geometry-multipoint", "geometry-linestring", "geometry-multilinestring", "geometry-polygon", "geometry-multipolygon", and "geometry-geometrycollection". In addition, the following special values are supported: "geometry-any" as the wildcard for any geometry type, "geometry-point-or-multipoint" for a Point or MultiPoint, "geometry-linestring-or-multilinestring" for a LineString or MultiLineString, and "geometry-polygon-or-multipolygon" for a Polygon or MultiPolygon.
^|D |Each temporal property SHALL be a "string" literal with the appropriate format (e.g., "date-time" or "date" for instances, depending on the temporal granularity).
^|E |Properties that are only applicable when creating new data or updating existing data SHALL include "writeOnly: true".
^|F |Properties that are only applicable when data is fetched SHALL include "readOnly: true".
^|G |The "additionalProperties" member with a value of "true" (the default) or "false" is used to state the expected behavior with respect to properties that are not explicitly declared in the schema. If "additionalProperties" is set to "false", properties that are not explicitly declared in the schema SHALL NOT be allowed, otherwise they SHALL be allowed.
|===

The following recommendations are intended to simplify parsing a schema and to help understanding the meaning of the properties:

:rec: properties
[width="90%",cols="2,7a"]
|===
^|*Recommendation {counter:rec-num}* |/rec/{req-class}/{rec}
^|A |Each property SHOULD have a human readable title ("title") and, where necessary for the understanding of the property, a description ("description").
^|B |The "type" SHOULD be one of the following values: "string" (string or temporal properties), "number"/"integer" (numeric properties), "boolean" (boolean properties), "object" (object properties) or "array" (array properties).
^|C |Properties that represent a URI SHOULD be represented as a string with format "uri" or "uri-reference".
^|D |Properties that represent a URI template SHOULD be represented as a string with format "uri-template".
^|E |Properties that represent a UUID SHOULD be represented as a string with format "uuid".
^|F |For string properties, "minLength", "maxLength", "enum" and/or "pattern" SHOULD be provided, where applicable.
^|G |For numeric properties, "multipleOf", "minimum", "exclusiveMinimum", "maximum", "exclusiveMaximum" SHOULD be provided, where applicable.
^|H |For integer properties that represent enumerated values without providing a description for each, "enum" SHOULD be provided.
^|I |For integer properties that represent enumerated values while providing a description for each, "anyOf" with a combination of "const" and "title" for each entry SHOULD be provided.
^|J |For array properties, the property SHOULD consist of items that are strings or numbers.
^|K |Required properties SHOULD be included in "required".
^|L |The JSON Schema keywords SHOULD be constrained to those mentioned in this recommendation, requirement `/req/{req-class}/properties` and requirements in the _additional keywords_ section below.
|===

[#additional-keywords]
=== Additional keywords

In order to be able to map the logical schema to a format-specific schema, extensions to the JSON Schema vocabulary are needed.

:req: additional-keywords
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |Additional keywords SHALL start with "x-ogc-".
|===

CAUTION: The next version of JSON Schema will likely restrict the use of additional keywords. As a result, this Standard may need to change the prefix or change how the vocabulary is extended.

:req: role
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The keyword "x-ogc-role" SHALL be used to declare a specific role of the property.
^|B |The value of the keyword "x-ogc-role" SHALL be a string.
|===

:req: role-id
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "id" SHALL be the identifier of the item in the collection that contains the item.
^|B |A property with role "id" SHALL either be a string or integer.
^|C |Only one property in a schema SHALL have "x-ogc-role" with a value "id".
|===

For cases, where the properties of the data have to be ordered in some representations of the data, the sequence of the properties can be expressed using a keyword "x-ogc-propertySeq".

:req: property-seq
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The keyword "x-ogc-propertySeq" SHALL be used to declare a specific relative position of the property.
^|B |The value of the keyword "x-ogc-propertySeq" SHALL be an integer representing the relative position in ascending order.
^|C |Each value of the keyword SHALL be unique for all members of a "properties" object in the JSON Schema.
|===

In geospatial data, numeric property values often represent a measurement and have a unit of measure. For fixed units, this can be expressed in the schema using the keyword "x-ogc-unit".

:req: unit
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The keyword "x-ogc-unit" SHALL be used to declare the unit of measure of the property.
^|B |The value of the keyword "x-ogc-unit" SHALL be a string representing the unit of measure.
^|C |The value of the keyword "x-ogc-unit" SHALL be the case sensitive UCUM representation ("c/s") unless a different language / register for units is identified in keyword "x-ogc-unitLang".
^|D |The value for UCUM, if explicitly declared as the language for units in keyword "x-ogc-unitLang", SHALL be "UCUM".
^|E |For specifying a unit from QUDT Units Vocabulary, "x-ogc-unitLang", SHALL be "QUDT".
^|F |For specifying a unit from QUDT Units Vocabulary, the value of the keyword "x-ogc-unit" SHALL be the URI of the unit.
|===

Communities or other OGC Standards can specify additional values for other unit languages, e.g., https://www.opengis.net/def/uom[units registered in the OGC Rainbow]. For each language it must be specified how units have to be represented in the "x-ogc-unit" value.

NOTE: UCUM provides a language to define units while QUDT provides a units vocabulary. The term "language" is used as it is the broader term.

NOTE: For example, the value for hectopascal is `hPa` in UCUM and `\https://qudt.org/vocab/unit/HectoPA` in QUDT.

:req: definition
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The keyword "x-ogc-definition" SHALL be used to identify the semantic definition for the property.
^|B |The value of the keyword "x-ogc-definition" SHALL be a URI.
|===

:req: nilvalues
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |The keyword "x-ogc-nilValues" SHALL be used to identify the values considered nil.
^|B |The value of the keyword "x-ogc-nilValues" SHALL be an array of objects, each including a mandatory "const" value and an optional "title" explanation of the meaning of that particular nil value.
|===

=== Property roles

The following requirements specifies property roles.
To understand how data is encoded in a specific format, property roles need to be identified in the logical schema. These roles depend on the format.

For example, the role "primary-geometry" is needed in feature types with multiple spatial properties to decide:

* Which geometry is encoded as the geometry of a feature in formats such as FlatGeobuf, Shapefile or Mapbox Vector Tiles, which only support a single geometry; or,
* Which geometry is encoded in the "geometry" member in GeoJSON.

The other roles specified in this requirements class support formats that support representing primary temporal information or the type of the feature, such as JSON-FG.

==== Primary geometry

If the features have multiple spatial properties, the role "primary-geometry" can be used to identify the primary geometry of the features.

:req: role-primary-geometry
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "primary-geometry" SHALL be a spatial property.
^|B |At most one property in a schema SHALL have "x-ogc-role" with a value "primary-geometry".
^|C |If the schema has only one spatial property, the property SHALL be the primary geometry even if the property is not explicitly tagged with the role "primary-geometry".
|===

NOTE: Since only a single property can be tagged in the schema as the primary geometry, varying primary geometries at different zoom levels are currently not supported. This would require the capability to assign the role depending on the zoom level.

==== Primary temporal information

If the features have multiple temporal properties, the roles "primary-instant", "primary-interval-start" and "primary-interval-end" can be used to identify the primary temporal information of the features.

:req: role-primary-instant
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "primary-instant" SHALL be a temporal property.
^|B |At most one property in a schema SHALL have "x-ogc-role" with a value "primary-instant".
^|C |If the schema has only one temporal property, the property SHALL be the primary temporal information even if the property is not explicitly tagged with the role "primary-instant".
|===

:req: role-primary-interval-start
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "primary-interval-start" SHALL be a temporal property.
^|B |At most one property in a schema SHALL have "x-ogc-role" with a value "primary-interval-start".
|===

:req: role-primary-interval-end
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "primary-interval-end" SHALL be a temporal property.
^|B |At most one property in a schema SHALL have "x-ogc-role" with a value "primary-interval-end".
|===

:req: primary-temporal-constraints
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If a schema has a property with role "primary-instant", the schema SHALL NOT have properties with role "primary-interval-start" or "primary-interval-end".
^|B |If a schema has properties with both roles "primary-interval-start" and "primary-interval-end", both properties SHALL have the same temporal granularity ("date" or "date-time").
|===

==== Data type

If the data has a property that represents the data type (for example, the _feature type_ for features), the role "type" can be used for this property.

:req: role-type
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "type" SHALL be a string property.
^|B |At most one property in a schema SHALL have "x-ogc-role" with a value "type".
|===

=== Returnables and Receivables

The following requirement describes how to link to a web resource representing the schema with the <<returnable-def,returnable>> and <<receivable-def,receivable>> properties of a collection in OGC Web APIs.

This requirement enables clients to discover the list of resource properties with their types and constraints that is returned when fetching a representation of the resource or when creating a new resource or updating an existing resource.

:req: returnables
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If a Returnables and Receivables resource is available for a Collection resource, the Returnables and Receivables resource SHALL be referenced from the Collection resource with a link using the relation type `\http://www.opengis.net/def/rel/ogc/1.0/schema` (or, alternatively, `[ogc-rel:schema]`).
^|B |A Returnables and Receivables resource SHALL support the HTTP GET operation and the media type `application/schema+json`.
^|C |A successful retrieval operation of the the Returnable and Receivables resources SHALL be reported as a response with a HTTP status code `200`.
^|D |For Returnables and Receivables resource responses that use `application/schema+json` as the `Content-Type` of the response, the response SHALL conform to <<rc_schemas>>.
|===

=== Queryables

The following requirement describes how to link to a schema representing the web resource for the <<queryable-def,queryable>> properties of a collection in OGC Web APIs.

This requirement enables clients to discover the list of resource properties with their types and constraints that may be used to construct filter expressions on a collection of data, for example, a set of features, or a gridded coverage.

Some OGC API Standards do not assume that the content schema of a resource being queried is available for inspection, whereas others depend on the capability defined in this requirement class to provide this information.
Therefore, a means needs to exist to interrogate an <<endpoint-def,endpoint>> to determine the names and types of the properties that may be used to construct a filter expression ("queryables").

In addition, a <<publisher-def,publisher>> may want to support <<queryable-def,queryables>> that are not directly represented as resource properties in the content schema of the resource.
Or the <<publisher-def,publisher>> may want to restrict filtering on certain properties. For example, because the backend datastore has not been configured to allow high-performance queries on those properties.

:req: queryables
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If a Queryables resource is available for a Collection resource, the Queryables resource SHALL be referenced from the Collection resource with a link using the relation type `\http://www.opengis.net/def/rel/ogc/1.0/queryables` (or, alternatively, `[ogc-rel:queryables]`).
^|B |A Queryables resource SHALL support the HTTP GET operation and the media type `application/schema+json`.
^|C |A successful retrieval operation of the Queryables resource SHALL be reported as a response with a HTTP status code `200`.
^|D |For Sortables resource responses that use `application/schema+json` as the `Content-Type` of the response, the response SHALL conform to <<rc_schemas>>.
^|E |If `additionalProperties` is not included or has the default value `true`, any property name is valid in a filter expression on the collection that is evalutated by the Web API and the property reference SHALL evaluate to `null`, if the property does not exist in the data.

If `additionalProperties` is set to false, property references that are not explicitly declared in the queryables schema SHALL result in a 400 response.
|===

NOTE: Depending on the filter language, some properties cannot be supported in filter expressions.
For example, if the filter language does not support predicates on object-valued properties, using such properties in a filter expression will result in an error.

=== Sortables

The following requirement describes how to link to a web resource representing the schema with the <<sortable-def,sortable>> properties of a collection returned by Web API endpoint(s) implementing OGC API Standards.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class}
|Target type |Web API
|Dependency |<<rc_schemas>>
|===

This requirements enables clients to discover the list of properties with their types and constraints that may be used to sort the data in a collection.

Some OGC API Standards do not assume that the content schema of a resource being queried is available for inspection, whereas others depend on the capability defined in this requirement class to provide this information.
Therefore, a means needs to exist to interrogate an <<endpoint-def,endpoint>> to determine the names and types of the properties that may be used to sort data ("sortables").

In addition, a <<publisher-def,publisher>> may want to support <<sortable-def,sortable>> that are not directly represented as resource properties in the content schema of the resource. Or the <<publisher-def,publisher>> may want to restrict sorting on certain properties. For example, because the backend datastore has not been configured to allow high-performance queries on those properties.

:req: sortables
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If a Sortables resources is available for a Collection resource, the Sortables resource SHALL be referenced from the Collection resource with a link using the relation type `\http://www.opengis.net/def/rel/ogc/1.0/sortables` (or, alternatively, `[ogc-rel:sortables]`).
^|B |A Sortables resource SHALL support the HTTP GET operation and the media type `application/schema+json`.
^|C |A successful retrieval operation of the Sortables resource SHALL be reported as a response with a HTTP status code `200`.
^|D |For Sortables resource responses that use `application/schema+json` as the `Content-Type` of the response, the response SHALL conform to <<rc_schemas>>.
^|E |No property of the Sortables SHALL be of type "object" or "array".
^|F |No property of the Sortables SHALL be a spatial property.
^|G |If `additionalProperties` is not included or has the default value `true`, any property name is valid in a sorting expression on the collection that is evaluated by the server and the property reference SHALL evaluate to `null`, if the property does not exist in the data.

If `additionalProperties` is set to false, property references that are not explicitly declared in the sortables schema SHALL result in a 400 response.
|===
