[[rc_collections-section]]
== Requirement Class "Collections"
:sectnums:

include::requirements/requirements_class_collections.adoc[]

[[collections-overview]]
=== Overview

Spatial Resources are the resources which we usually think of as Geospatial Data. They include Features, Coverages, and Images. This Conformance Class defines basic patterns for accessing Spatial Resources. Additional OGC API Standards have been developed to address specific API requirements for each Spatial Resource type.

OGC APIs are designed to support two access patterns; Hypermedia Access, and Direct Access. OGC APIs support both access patterns through the use of API Definition documents, standardized paths, and standardized hypermedia schemas.

Hypermedia Access was described in the <<navigation-introduction>> section of Clause 8. For Spatial Resources, hypermedia navigation is enabled through the links included in each schema defined by this Requirement Class. 

Direct access is the use of know URL paths to access a resource directly. The requirements in this Requirement Class are organized around the standard paths for Spatial Data. 

[[spatial-resources-requirements]]
=== Spatial Resources

Detailed requirements for each Spatial Resource type are dealt with in the resource-specific API standards. However, this API Common standard has the responsiblity to see that all OGC API standards work together by:

. Providing specifications for the description of each collection (/collections/{collectionId}), and the list of collections (/collections)
. Providing a consistent framework for serving spatial data from the OGC API, regardless of the type. Consistent means that #1 works exactly the same (potentially with type-specific additional properties) and that the different types of data can all be collections on the same OGC API end-point.
. Providing a tie point for other OGC API modules to connect to and reference (processes inputs & outputs, cataloging, searching and filtering collections, detailed metadata, tiles, styles, clipping and intersecting bounding boxes in common) Just by virtue of understanding that /collections/{collectionId} points to a spatial **data layer**.

Spatial Resources are exposed using the path template.

 /collections/{collectionId}/items

The resources returned from each node in this template are described in <<spatial-resource-paths>>.

[#spatial-resource-paths,reftext='{table-caption} {counter:table-num}']
.Spatial Resource Paths
[width="90%",cols="3,4",options="header"]
|===
^|**Path Template** ^|**Resource**
|/collections |Metadata describing the spatial collections available from this API.
|/collections/{collectionId} |Metadata describing the collection with the unique identifier `{collectionId}`
|/collections/{collectionId}/items |The spatial collection resource identified by the `{collectionId}` parameter.
|===

[[collections-metadata]]
==== Collections Metadata

OGC APIs typically organize their Spatial Resources into collections. Information about those collections is accessed through the /collections path.

===== Operation

include::requirements/collections/REQ_rc-md-op.adoc[]

===== Response

include::requirements/collections/REQ_rc-md-success.adoc[]

The collections metadata returned by this operation is based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collections.json[Collections Metadata Schema]. Examples of collections metadata are provided in <<collections-metadata-examples>>.

.Collections Metadata Schema
[source, JSON]
include::openapi/schemas/collections.json[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-descriptions.adoc[]

The `collections` property of the Collections Metadata provides a description of each collection. These descriptions are based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collectionInfo.json[Collection Information Schema]. This schema is described in detail in the <<collection-information>> section of this Standard. The following requirements and recommendations govern the use of Collection Information in the Collections Metadata.

include::requirements/collections/REQ_rc-md-items.adoc[]

While it is prefered that the Collections Metadata describe all of the collections accessible through the API, in some cases that is impractical. Developers have an option to only return a subset, as long as they provide a way to retrieve the remaining metadata as well.

include::recommendations/collections/PER_rc-md-items.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[collection-information]]
==== Collection Information

Each resource collection is described by a set of metadata. That metadata is accessed directly using the `/collections/{collectionId}` path or as an entry in the `collections` property of the Collections Metadata resource.

===== Operation

include::requirements/collections/REQ_src-md-op.adoc[]

===== Response

include::requirements/collections/REQ_src-md-success.adoc[]

Collection Information is based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collectionInfo.json[Collection Information Schema]. Examples of Collection Information are provided in <<collection-information-examples>>.

.Collection Information Schema
[source, JSON]
include::openapi/schemas/collectionInfo.json[]

This schema is further constrained by the following requirements and recommendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-items-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-items-descriptions.adoc[]

Additional requirements and recommendations apply to the `extent` property of the Collection Information.

include::requirements/collections/REQ_rc-md-extent.adoc[]

include::recommendations/collections/REC_rc-md-extent-single.adoc[]

include::recommendations/collections/PER_rc-md-extent-extensions.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collection-resource]]
==== Collection Resource

A collection resource is the content of the collection as opposed to metadata about that collection. This standard defines the general behavior of this operation, but detailed requirements are the purview of the API standard for that resource type.

===== Operation

include::requirements/collections/REQ_rc-op.adoc[]

===== Response

include::requirements/collections/REQ_rc-response.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[collection-information-resources]]
=== Information Resources

Information Resources are non-spatial resources which support the operation of the API or the access and use of the Spatial Resources. They are described in the <<information-resources>> section.

Information Resources related to Spatial Resources can be exposed using the path template:

* /collections/{collectionId}/{resourceType}

The resources returned from each node in this template are described in <<information-resource-paths>>.

[#information-resource-paths,reftext='{table-caption} {counter:table-num}']
.Information Resource Paths
[width="90%",cols="2,4",options="header"]
|===
^|**Path Template** ^|**Resource**
|/collections |The root resource describing the spatial collections available from this API.
|/collections/{collectionId} |Identifies a collection with the unique identifier `{collectionId}`
|/collections/{collectionId}/{resourceType} |Identifies an Information Resource of type {resourceType} associated with the `{collectionId}` collection.
|===

The OGC API-Common standard does not define any Information Resource types. However <<information-resource-table>> provides a mapping of the known Information Resource types to the standard where they are defined.

=== Parameter Modules

NOTE: ISSUE: Should we add a limit parameter. See GitHub issues https://github.com/opengeospatial/oapi_common/issues/87[87], https://github.com/opengeospatial/oapi_common/issues/83[83], and https://github.com/opengeospatial/oapi_common/issues/82[82].

NOTE: ISSUE: Should we be more explicit about the scope of parameters and other elements of the API definition?  See issues https://github.com/opengeospatial/oapi_common/issues/67[67] and https://github.com/opengeospatial/oapi_common/issues/88[88]. Also see API-Coverages issue https://github.com/opengeospatial/ogc_api_coverages/issues/53[53].   

Query parameters are used in URLs to limit the resources which are returned on a GET request. The API Common standard defines two standard parameters for use in OGC API standards.

==== Parameter bbox

include::requirements/collections/REQ_rc-bbox-definition.adoc[]

include::requirements/collections/REQ_rc-bbox-response.adoc[]

"Intersects" means that the rectangular area specified in the parameter `bbox` includes a coordinate that is part of the (spatial) geometry of the resource. This includes the boundaries of the geometries (e.g. for curves the start and end position and for surfaces the outer and inner rings).

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a later version of this specification.

For WGS84 longitude/latitude the bounding box is in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/parameters/bbox.yaml[bbox.yaml].

==== Parameter datetime

include::requirements/collections/REQ_rc-time-definition.adoc[]

include::requirements/collections/REQ_rc-time-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.
 
.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`time=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate` in the building features), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/parameters/datetime.yaml[datetime.yaml].

[[collection-general-requirements]]
=== General Requirements

The following general requirements and recommendations apply to all OGC APIs which host Spatial Resources.

==== Coordinate Reference Systems

As discussed in Chapter 9 of the W3C/OGC Spatial Data on the Web <<SDWBP,Best Practices document>>, how to express and share the location of resources in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that define the coordinates.

For the reasons discussed in the Best Practices, OGC APIs use WGS84 longitude and latitude as the default coordinate reference system.

include::requirements/collections/REQ_crs84.adoc[]

The implementations compliant with the Core are not required to support publishing geometries in coordinate reference systems other than http://www.opengis.net/def/crs/OGC/1.3/CRS84. The Core also does not specify a capability to request geometries in a different reference system than the native one of the published resource. Such a capability will be specified in other OGC API standards.
