== Conformance
Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

=== Approach
OGC APIs are modular. The _"Core"_ module defines the minimum set of capabilities which are required of all implementations. Extension modules define capability packages which can be added to the API. Each module is a complete package, usually with no extenal dependencies except for _"Core"_. This approach allows the implementor to build an API which suites their needs out of standard, re-usable building blocks.

Since OGC APIs are modular, it makes little sense to claim conformance with an OGC API Standard. Rather, you claim conformance with an enumerated set of modules which are defined in a standard. Each module is associated with a Conformance Class as defined in <<ogc08-131,OGC 08-131>>. Each Conformance Class is identified by a URI. The list of Conformance Classes (and associated modules) implemented by an API is advertised by listing their URIs on the _/conformance_ path. Conformance with an API Standard is conformance with the _Core_ Conformance Class as well as all Conformance Classes listed on _/conformance_.

=== Measuring Conformance
The first step in measuring conformance is to identify the type of entity which is being tested. A standard can have more than one _Standardization Target_. For example, an encoding standard may have requirements which apply to encoded documents. It may also have requirements which apply to the software which produces and/or consumes those documents. The document and software are two different _Standardization Targets_. Conformance for one target does not imply conformance for the other. For this reason, OGC <<ogc08-131,08-131>> requires that a _Conformance Class_ have one and only one _Standardization Target_.

The next step is to select the _Conformance Classes_. The _Standardization Target_ selected serves as the first filter criteria. The _Core Conformance Class_ is always on the list. Finally, the _Conformance Classes_ for all additional modules implemented by the _Standardization Target_ should be included.

A list of _Conformance Classes_ identifies the modules to be evaluated for conformance. But it does not identify the crieria for conformance. _Requirements Classes_ serve that purpose. Each _Conformance Class_ has an associated _Requirements Class_. A _Requirements Class_ serves as the root of a collection of requirements. To prove conformance, a _Standardization Target_ must demonstrate that it meets all of the requirements within the _Requirements Class_ for each _Conformance Class_ it claims to implement.

The Abstract Test Suite (Annex A) provides a test plan for every requirement in every _Requirements Class_. It serves as direction to test developers, ensuring that the _Executable Test Suites_ sufficiently exercise the _Standardization Target_ to prove conformance. Successful completion of the _Executable Test Suite_ for a _Conformance Class_ is proof that all of the requirments for that _Conformance Class_ have been met.   

=== API-Common Conformance
The one Standardization Target for this standard is Web APIs.

This standard identifies five conformance classes. The conformance classes implemented by an API are advertised through the /conformance path on the landing page. Each conformance class is defined by one requirements class. The tests in Annex A are organized by Requirements Class. So an implementation of the _Core_ conformance class must pass all tests specified in Annex A for the _Core_ requirements class.

The requirements classes for OGC API-Common are:

* <<rc_core-section,Core>>

The _Core Requirements Class_ is the minimal useful service interface for an OGC API. The requirements specified in this requirements class are mandatory for all OGC APIs

Additional capabilities such as support for transactions, complex data structures, and rich queries are specified in additional OGC API standards and in OGC managed API extensions. Those standards and extensions build on the API-Common foundation to provide the full functionality required of the API implementation. 

* <<rc_collections-section,Collections>>

The _Collections Requirements Class_ extends the _Core_ to enable fine-grained access to spatial resources. This requirements class is mandatory for all OGC APIs which expose spatial resources.

The structure and organziation of a collection of spatial resources is very much dependent on the nature of that resource and the expected access patterns. This is information which cannot be specified in a common manner. The _Collections Requirements Class_ specifies the requirements necessary to discover and understand that structure and organization. Requirements governing the resource collections themselves are specified in the resource-specific OGC API standards.  

* <<rc_html-section,HTML>>
* <<rc_geojson-section,GeoJSON>>

Neither the nor _Core_ nor _Collections_ requirements class mandate a specific encoding or format for representing resources. The _HTML_ and _GeoJSON_ requirements classes specify representations for these resources in commonly used encodings for spatial data on the web.

Neither of these encodings are mandatory. An implementation of the _API-Common_ standard may decide to implement another encoding instead of, or in addition to, these two.

* <<rc_oas30-section,OpenAPI 3.0>>

The _API-Common_ does not mandate any encoding or format for the formal definition of the API. The prefered option is the OpenAPI 3.0 specification. The _OpenAPI 3.0_ requirements class has been specified for APIs implementing OpenAPI 3.0.

