== Overview

requirements/requirements_class_core.adoc

An OGC API provides access to a resource. Resources are identified using a URI. For purposes of this specification, a URI is composed of three parts:

* Server URI - a URI which identifies a server which hosts the resource
* Path - the "location" of the resource on the server
* Query - terms used to select one or more resources out of a group

Resources can be files or Web pages. But the don't have to be. Many OGC APIs will return dynamic content. Content that is generated in response to the request.

=== Requirement Class A: API Common

All OGC APIs share some common features.

include::requirements/requirements_class.adoc[]

==== Requirement A.1: Landing Page

Each OGC API has a single Landing Page at the path "/" which describes the API and provides links to all of the resources exposed through the API.

*Operation*

include::requirements/Class_A/REQ_root-op.adoc[]

*Response*

include::requirements/Class_B/REQ_root-success.adoc[]

*Schema for the landing page*

  type: object
  required:
    - links
  properties:
    links:
      type: array
      items:
        $ref: https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/link.yaml

Example 1. Landing page response document

  {
    "links": [
      { "href": "http://data.example.org/",
        "rel": "self", "type": "application/json", "title": "this document" },
      { "href": "http://data.example.org/api",
        "rel": "service", "type": "application/openapi+json;version=3.0", "title": "the API definition" },
      { "href": "http://data.example.org/conformance",
        "rel": "conformance", "type": "application/json", "title": "WFS 3.0 conformance classes implemented by this server" },
      { "href": "http://data.example.org/collections",
        "rel": "data", "type": "application/json", "title": "Metadata about the feature collections" }
    ]
  }

*Error situations*

See HTTP status codes for general guidance.

==== Requirement A.2: API Definition

The Landing Page shall expose an API definion on the path "/api".  

The API Definition describes the capabilities of the server that can be used by clients to connect to the server or by development tools to support the implementation of servers and clients. Accessing the API Definition using HTTP GET returns a description of the API.

*Operation*

Every WFS provides an API definition that describes the capabilities of the server and which can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

include::requirements/Class_A/REQ_api-definition-op.adoc[]

*Response*

include::requirements/Class_A/REQ_api-definition-success.adoc[]

include::requirements/Class_A/REC_api-definition-oas.adoc[]

If multiple API definition formats are supported by a server, use content negotiation to select the desired representation.

The API definition document describes the API. In other words, there is no need to include the /api operation in the API definition itself.

The idea is that any API can be used by developers that are familiar with the API definition language(s) supported by the server. For example, if an OpenAPI definition is used, it should be possible to create a working client using the OpenAPI definition. The developer may need to learn a little bit about geometry data types, etc., but it should not be required to read this standard to access the data via the API.

*Error situations*

See HTTP status codes for general guidance.

==== Requirement A.3: Declaration of conformance classes

The Landing Page shall expose an list of compliance class identifiers on the path "/conformance". These identifiers shall be the identifiers assigned by the OGC Naming Authority for the compliance classes implemeted by this API.   

*Operation*

To support "generic" clients for accessing Web Feature Services in general - and not "just" a specific API / server, the server has to declare the requirements classes it implements and conforms to.

include::requirements/Class_A/REQ_conformance-op.adoc[]

*Response*

include::requirements/Class_A/REQ_conformance-success.adoc[]

*Schema for the list of requirements classes*

  type: object
  required:
    - conformsTo
  properties:
    conformsTo:
      type: array
      items:
        type: string

Example 2. Requirements class response document

This example response in JSON is for a server that supports OpenAPI 3.0 for the API definition and HTML and GeoJSON as encodings for features.

  {
    "conformsTo": [
      "http://www.opengis.net/spec/wfs-1/3.0/req/core",
      "http://www.opengis.net/spec/wfs-1/3.0/req/oas30",
      "http://www.opengis.net/spec/wfs-1/3.0/req/html",
      "http://www.opengis.net/spec/wfs-1/3.0/req/geojson"
    ]
  }

*Error situations*

See HTTP status codes for general guidance.

=== Requirement Class B: Protocol Layer

Discussion of the protocol layer requirements

include::requirements/requirements_class.adoc[]

==== Requirement B.1: HTTP 1.1

include::requirements/Class_B/REQ_http.adoc[]

This includes the correct use of status codes, headers, etc.

*HTTP status codes*

Table 1 lists the main HTTP status codes that clients should be prepared to receive.

This includes, for example, support for specific security schemes or URI redirection.

In addition, other error situations may occur in the transport layer outside of the server.

.Typical HTTP Status Codes
[cols="10,90",width="100%",options="header,footer"]
|====================
|Status Code  |Description  
|200  |A successful request  
|304  |An entity tag was provided in the request and the resource has not been changed since the previous request.  
|400  |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|401  |The request requires user authentication. The response includes a WWW-Authenticate header field containing a challenge applicable to the requested resource.
|403  |The server understood the request, but is refusing to fulfill it. While status code 401 indicates missing or bad authentication, status code 403 indicates that authentication is not the issue, but the client is not authorised to perform the requested operation on the resource.
|404  |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|405  |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|406  |The Accept header submitted in the request did not support any of the media types supported by the server for the requested resource.
|500  |An internal error occurred in the server.
|====================

More specific guidance is provided for each resource, where applicable.

include::requirements/Class_B/PER_additional-status-codes.adoc[]

==== Requirement B.2: Web caching

include::requirements/Class_B/REQ_http.adoc[]

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by HTTP/1.1 (RFC 2616).

include::requirements/Class_B/REC_etag.adoc[]

==== Requirement B.3: Support for cross-origin requests

Access to data from a HTML page is by default prohibited for security reasons, if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.

include::requirements/Class_B/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

    Cross-origin resource sharing (CORS)

    JSONP (JSON with padding)

==== Requirement B.4: Encodings

While the OGC API Common standard does not specify any mandatory encoding, we recommend the following encodings. See Clause 6 (Overview) for a discussion.

include::requirements/Class_B/REC_html.adoc[]

include::requirements/Class_B/REC_geojson.adoc[]

Requirement /req/core/http implies that the encoding of a server response is determined using content negotiation as specified by the HTTP RFC.

The section Media Types includes guidance on media types for encodings that are specified in this document.

Note that any server that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.
Note

Two common approaches are:

    an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");

    an additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.

=== Requirement Class C: Spatial-Temporal

Discussion of how common spatial-temporal concepts shall be implemented.

include::requirements/requirements_class.adoc[]

==== Requirement C.1: Coordinate reference systems

As discussed in Chapter 9 of the W3C/OGC Spatial Data on the Web Best Practices document, how to express and share the location of features in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, Web Feature Service 3.0 uses WGS84 longitude and latitude as the default coordinate reference system.

include::requirements/Class_C/REQ_crs84.adoc[]

The implementations compliant with the Core are not required to support publishing feature geometries in coordinate reference systems other than http://www.opengis.net/def/crs/OGC/1.3/CRS84. The Core also does not specify a capability to request feature geometries in a different coordinate reference system than the native one of the published features. Such a capability will be specified in another part(s) of the WFS 3.0 series.

Link headers

include::requirements/Class_C/REC_link-header.adoc[]

==== Requirement C.2: Parameter bbox

include::requirements/Class_C/REQ_fc-bbox-definition.adoc[]

include::requirements/Class_C/REQ_fc-bbox-response.adoc[]

"Intersects" means that the rectangular area specified in the parameter
`bbox` includes a coordinate that is part of the (spatial) geometry of the feature.
This includes the boundaries of the geometries (e.g. for curves the start
and end position and for surfaces the outer and inner rings).

This standard does not specify requirements for the parameter `bbox-crs`. 

For WGS84 longitude/latitude the bounding box is in most cases the sequence of
minimum longitude, minimum latitude, maximum longitude and maximum latitude.
However, in cases where the box spans the anti-meridian the first value
(west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S)
would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

A template for the definition of the parameter in YAML according to
OpenAPI 3.0 is available at
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/parameters/bbox.yaml[bbox.yaml].

==== Requirement C.3: Parameter time

include::requirements/Class_C/REQ_fc-time-definition.adoc[]

include::requirements/Class_C/REQ_fc-time-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter
`time` includes a timestamp that is part of the temporal geometry of the feature
(again, a time instant or period). For time periods this includes the start
and end time.

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`time=2018-02-12T23%3A20%3A50Z`
=================

For features with a temporal property that is a timestamp (like `lastUpdate`
in the building features), a date-time value would match all features where
the temporal property is identical.

For features with a temporal property that is a date or a time period,
a date-time value would match all features where the timestamp is on that
day or within the time period.

.A period using a start and end time
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`time=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`
=================

.A period using start time and a duration
=================
A duration of 1 month, 6 days, 12 hours, 31 minutes and 12 seconds from
February 12, 2018, 00:00:00 GMT:

`time=2018-02-12T00%3A00%3A00Z%2FP1M6DT12H31M12S`
=================

For features with a temporal property that is a timestamp (like `lastUpdate`
in the building features), a time period would match all features where
the temporal property is within the period.

For features with a temporal property that is a date or a time period,
a time period would match all features where the values overlap.

A template for the definition of the parameter in YAML according to
OpenAPI 3.0 is available at
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/parameters/time.yaml[time.yaml].


_From template:_****

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===



