== Requirements classes for encodings

=== Overview

This clause specifies four pre-defined requirements classes for encodings to be used by an OGC API implementation. These encodings are commonly used encodings for spatial data on the web:

* <<rc_html-section,HTML>>
* <<rc_geojson-section,GeoJSON>>
* <<rc_gmlsf0-section,Geography Markup Language (GML), Simple Features Profile, Level 0>>
* <<rc_gmlsf2-section,Geography Markup Language (GML), Simple Features Profile, Level 2>>

None of these encodings are mandatory and an implementation of the <<rc_core-section,Core>> requirements class may implement some, all, or none of them.

[[rc_html-section]]
=== Requirement Class "HTML"

Geographic information that is only accessible in formats such as GeoJSON or GML have two issues:

* The data is not discoverable using Web crawlers and search engines,
* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, this publication should be done in a way that enables users and search engines to discover and access all of the data.

This is discussed in detail in the  <<SDWBP,W3C/OGC SDW Best Practice>>. Therefore, the OGC API-Common Standard <<rec_html,recommends>> supporting HTML as an encoding.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[rc_geojson-section]]
=== Requirement Class "GeoJSON"

GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format, supporting GeoJSON is recommended with the caveat that the resource can be represented in GeoJSON for the intended use.

include::requirements/requirements_class_geojson.adoc[]

include::requirements/geojson/REQ_definition.adoc[]

include::requirements/geojson/REQ_content.adoc[]

Templates for the definition of the schemas for the GeoJSON responses in JSON Schema definitions are available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collections.yaml[collections.yaml] and link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collectionInfo.yaml[collectionInfo.yaml].

These are generic schemas that do not include any application schema information about specific resource types or their properties.

[[rc_gmlsf0-section]]
=== Requirement Class GMLSF0
"Geography Markup Language (GML), Simple Features Profile, Level 0"

NOTE: To be provided

[[rc_gmlsf2-section]]
=== Requirement Class GMLSF2
"Geography Markup Language (GML), Simple Features Profile, Level 2"

NOTE: To be provided

