[big]*i.     Abstract*

The OGC has started a focused effort to extend their service standards efforts into the Resource Oriented Architecture world.  In the course of these efforts, some practices will be common accross all OGC API standards.  The purpose of this GitHub is to provide a forum to discuss and capture those practices.  When suitably mature, this repository will be presented as a candidate "OWS Common" standard for Resource Oriented APIs.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

OpenAPI, AsyncAPI, REST, Common, Standard

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

Heazeltech LLC

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

Name  Affiliation

Chuck Heazel Heazeltech
