[[req_core_query-param-value-double]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/query-param-value-double*
^|A |Double values SHALL be represented by a mantissa followed, optionally, by the character "e", followed by an exponent.
^|B |The exponent SHALL be an integer.
^|C |The mantissa SHALL be a decimal number.
^|D |The representations for exponent and mantissa SHALL follow the lexical rules for integer and decimal.
^|E |If the "e" and the following exponent are omitted, an exponent value of 0 SHALL be assumed.
|===
////


[requirement]
====
[%metadata]
identifier:: /req/core/query-param-value-double
part:: Double values SHALL be represented by a mantissa followed, optionally, by the character "e", followed by an exponent.
part:: The exponent SHALL be an integer.
part:: The mantissa SHALL be a decimal number.
part:: The representations for exponent and mantissa SHALL follow the lexical rules for integer and decimal.
part:: If the "e" and the following exponent are omitted, an exponent value of 0 SHALL be assumed.
====
