[[link-relations-section]]
== Link Relations

This section provides a discussion of link relations, the governing policies and Standards, as well as how they should be used.

Links between elements of an OGC API are encoded using the link relation schema provided in <<link-schema>>.

[#link-schema,reftext='{figure-caption} {counter:figure-num}']
.Link Schema
[source,yaml]
----
type: object
required:
  - href
  - rel
properties:
  href:
    type: string
    description: Supplies the URI to a remote resource (or resource fragment).
    example: http://data.example.com/buildings/123
  rel:
    type: string
    description: The type or semantics of the relation.
    example: alternate
  type:
    type: string
    description: A hint indicating what the media type of the result of dereferencing the link should be.
    example: application/geo+json
  hreflang:
    type: string
    description: A hint indicating what the language of the result of dereferencing the link should be.
    example: en
  title:
    type: string
    description: Used to label the destination of a link such that it can be used as a human-readable identifier.
    example: Trierer Strasse 70, 53115 Bonn
  length:
    type: integer
----

[[relation-attributes-section]]
=== Attributes of Link Relations

The attributes supported by link relations are presented in this subsection.

==== Href Attribute

The `href` attribute is mandatory.

"The Locator Attribute (href) supplies the data that allows an application to find a remote resource or resource fragment. The value of this attribute is an Internationalized Resource Identifier (IRI) which serves as the Uniform Resource Identifier for the remote resource." (W3C XLink Version 1.1)

NOTE: An IRI is a sequence of characters from the Universal Character Set (Unicode/ISO 10646).  A mapping from IRIs to URIs is defined, which means that IRIs can be used instead of URIs, where appropriate, to identify resources. (<<rfc3987,RFC 3987>>)

==== Rel Attribute

The `rel` attribute is mandatory.

"In the simplest case, a link relation type identifies the semantics of a link.  For example, a link with the relation type "copyright" indicates that the current link context has a copyright resource at the link target.

Link relation types can also be used to indicate that the target resource has particular attributes, or exhibits particular behaviors; for example, a "service" link implies that the link target can be used as part of a defined protocol (in this case, a service description).

Relation types are not to be confused with media types [<<rfc2046,RFC 2046>>]; they do not identify the format of the representation that results when the link is dereferenced.  Rather, they only describe how the current context is related to another resource.

Relation types SHOULD NOT infer any additional semantics based upon the presence or absence of another link relation type, or its own cardinality of occurrence.  An exception to this is the combination of the "alternate" and "stylesheet" registered relation types, which has special meaning in HTML for historical reasons.

There are two kinds of relation types: registered and extension." (<<rfc8288,RFC 8288>>)

==== Type Attribute

The `type` attribute is optional.

"The "type" attribute, when present, is a hint indicating what the media type of the result of dereferencing the link should be.  Note that this is only a hint; for example, it does not override the
Content-Type header field of a HTTP response obtained by actually following the link.  The type attribute MUST NOT appear more than once in a given link-value; occurrences after the first MUST be ignored by parsers." (<<rfc8288,RFC 8288>>)

==== Hreflang Attribute

The `hreflang` attribute is optional.

"The "hreflang" attribute, when present, is a hint indicating what the language of the result of dereferencing the link should be.  Note that this is only a hint; for example, it does not override the Content-Language header field of a HTTP response obtained by actually following the link.  Multiple hreflang attributes on a single link-value indicate that multiple languages are available from the indicated resource." (<<rfc8288,RFC 8288>>)

==== Title Attribute

The `title` attribute is optional.

"The "title" attribute, when present, is used to label the destination of a link such that it can be used as a human-readable identifier (e.g., a menu entry) in the language indicated by the Content-Language header field (if present).  The title attribute MUST NOT appear more than once in a given link; occurrences after the first MUST be ignored by parsers." (<<rfc8288,RFC 8288>>)

==== Length Attribute

The `length` attribute does not appear to be defined in the normative Standards.

[[relation-type-section]]
=== Relation Types

There are two kinds of relation types; registered and extension.

Registered relation types are registered in the IANA register at https://www.iana.org/assignments/link-relations/link-relations.xhtml[https://www.iana.org/assignments/link-relations/link-relations.xhtml] <<link-relations>>. Registered relation types are used in OGC API Standards whenever appropriate.

Extension relation types are those which are not registered with IANA. These extension types are in the form of "--- a URI [<<rfc3986,RFC 3986>>] that uniquely identifies the relation type.  Although the URI can point to a resource that contains a definition of the semantics of the relation type, clients SHOULD NOT automatically access that resource to avoid overburdening its server.

The URI used for an extension relation type SHOULD be under the control of the person or party defining it or be delegated to them.

When extension relation types are compared, they MUST be compared as strings (after converting to URIs if serialized in a different format) in a case-insensitive fashion, character by character. Because of this, all-lowercase URIs SHOULD be used for extension relations.

Note that while extension relation types are required to be URIs, a serialization of links can specify that they are expressed in another form, as long as they can be converted to URIs." (<<rfc8288,RFC 8288>>)

Extension relation types used in OGC API Standards are registered at http://www.opengis.net/def/rel[http://www.opengis.net/def/rel]
