[abstract]
== Abstract

The OGC API — Common standard is a multi-part standard that specifies reusable building-blocks that can be used in the construction of OGC API Standards. The OGC API — Common — Users Guide presents information useful to developers or users of implementations of the OGC API — Common standard. The information in the Users Guide is not normative. That is, it is not mandatory. However, it may prove essential to fully understand the normative text in the OGC API — Common standard. The Users Guide is therefore intended to serve as an aid to developers and users.


[[preface-section]]
== Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[[submitters-section]]
== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[#submitters-table,reftext='{table-caption} {counter:table-num}']
.Submitters
[width="90%",cols="4,6",options="header"]
|===
|*Name* |*Affiliation*
|Charles Heazel _(editor)_ |Heazeltech
|Jérôme Jacovella-St-Louis |Ecere Corporation
|Joan  Masó |UAB-CREAF
|===
