[[req_searchable_q]]

[requirement]
====
[%metadata]
identifier:: /req/searchable-collections/q
part:: The implementation SHALL support a `q` parameter consisting of one or more comma-separated strings of characters.
part:: The implementation SHALL only return collections whose description matches at least one (logical OR) of the comma-separated items in the `q` array.
part:: An item of the `q` array without white space SHALL be considered a match if the whole word appears at least once in the collection description.
part:: An item of the `q` array consisting of multiple terms separated by white space SHALL be considered a match if the terms appears in the order specified in a particular property of the collection description,
with nothing but white spaces between those terms.
part:: The implementation SHALL match items in a case-insensitive manner.
part:: The implementation SHALL match the items at minimum with the `title`, `description` and `keywords` properties of the collection descriptions.
====

NOTE: The specific set of text keys/fields/properties of a collection description to which the `q` terms are matched applied SHALL be left to the discretion of the implementation.
