[[req_searchable-resolution]]

[requirement]
====
[%metadata]
identifier:: /req/searchable-collections/resolution
part:: For the `/collections` resource, the Implementation SHALL support a `resolution` query parameter specified as a range of numeric values,
using the syntax `<low cell size>/<high cell size>` e.g., `resolution=0.000009/0.0045`, where an empty string or two dots (`..`) is an unbounded low or high value (e.g., `/0.0045` or `0.000009/..`).
part:: The Implementation SHALL interpret a single cell size value for `resolution` e.g., `resolution=0.000009` as equivalent to `<cell size>/<cell size>` (specifying a single target cell size).
part:: The low and high cell sizes SHALL be interpreted as decimal degrees of latitude and longitudes for collections of data referenced to Earth,
and to units of the native CRS (`storageCrs`) otherwise (corresponding to the units of the `minCellSize` and `maxCellSize` properties of the collection description).
part:: If a low cell size is specified (not unbounded `..` or empty), the Implementation SHALL NOT include in the response collections for which a `maxCellSize`
or a `maxScaleDenominator` property is declared in the collection description, and the `maxCellSize` (or, if `maxCellSize` is not present, the equivalent conversion for `maxScaleDenominator` assuming 0.28mm/cell)
is smaller than the low cell size specified.
part:: If a high cell size is specified (not unbounded `..` or empty), the Implementation SHALL NOT include in the response collections for which a `minCellSize`
or a `minScaleDenominator` property is declared in the collection description, and the `minCellSize` (or, if `minCellSize` is not present, the equivalent conversion for `minScaleDenominator` assuming 0.28mm/cell)
is greater than the high cell size specified.
part:: The Implementation SHALL return a 4xx error if both low and high cell sizes are specified and the high value is smaller than the low value.
part:: The Implementation SHALL return a 4xx error if both `sd` and `resolution` query parameters are specified, as they are mutually exclusive.
part:: The Implementation SHALL interpret a range specified as `../..` or `/` as not filtering out any collection based on scale denominator / resolution.
====
