[[ats_json_definition]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/json/definition*
^|Test Purpose |Verify support for JSON
^|Requirement |<<req_json_definition,/req/json/definition>> +
<<req_json_content,/req/json/content>>
^|Test Method|DO FOR EACH resource and operation defined in the Landing Page Conformance Class:

. Execute the operation specifing `application/json` as the media type
. Validate that a document was returned with a status code `200`
. Validate the contents of the returned document using test <<ats_json_content,/conf/json/content>>.

DONE
|===
////

[abstract_test]
====
[%metadata]
label:: /conf/json/definition
subject:: <<req_json_definition,/req/json/definition>> +
<<req_json_content,/req/json/content>>
test-purpose:: Verify support for JSON
test-method::
+
--
DO FOR EACH resource and operation defined in the Landing Page Conformance Class:

. Execute the operation specifying `application/json` as the media type
. Validate that a document was returned with a status code `200`
. Validate the contents of the returned document using test <<ats_json_content,/conf/json/content>>.

DONE
--
====
