[[req_domainset_subset-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/domainset-subset/definition*
^|A |The operation SHALL support a parameter `subset` with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  SubsetSpec:        "subset"=axisName(intervalOrPoint)
  axisName:          {text}
  intervalOrPoint:   interval \| point
  interval:          low : high
  low:               point \| *
  high:              point \| *
  point:             {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----
^|B |The axis name SHALL be the same as one of the axes defined in the coverage's envelope as part of its collection description document, or else the server SHALL return a 400 status code.
^|C |If the intervalOrPoint values fall entirely outside the range of the DomainSet for the identified axis, a 204 status code SHALL be returned
^|D |For a CRS where an axis can wrap around, such as subsetting across the dateline (anti-meridian) in a geographic CRS, a `low` value greater than `high` SHALL
be supported to indicate an extent crossing that wrapping point.
|===
