////
[[ats_core_query-param-name-invalid]]
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/core/query-param-name-invalid*
^|Test Purpose |Validate that an error is returned when a query parameter contains a value that is not valid for that parameter.
^|Requirement |<<req_core_query-param-name-invalid,/req/core/query-param-name-invalid>>
^|Test Method |DO FOR ALL query parameters advertised in the API definition +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Execute that operation using the query parameter +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}with values that do not comply with the advertised constraints on those values. +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}(Example: exceeding minimum or maximum values) +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the operation returns a response with the status code `400`. +
{nbsp}{nbsp}DONE +
DONE
|===
////

[[ats_core_query-param-name-invalid]]
[abstract_test]
====
[%metadata]
label:: /conf/core/query-param-name-invalid
subject:: <<req_core_query-param-name-invalid,/req/core/query-param-name-invalid>>
test-purpose:: Validate that an error is returned when a query parameter contains a value that is not valid for that parameter.
test-method::
+
--
DO FOR ALL query parameters advertised in the API definition +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Execute that operation using the query parameter +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}with values that do not comply with the advertised constraints on those values. +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}(Example: exceeding minimum or maximum values) +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the operation returns a response with the status code `400`. +
{nbsp}{nbsp}DONE +
DONE
--
====
