////
[[ats_core_query-param-list-empty]]
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/core/query-param-list-empty*
^|Test Purpose |For every query parameter where the value may be a list, validate that the server interprets an empty string as an empty list.
^|Requirement |<<req_core_query-param-list-empty,/req/core/query-param-list-empty>>
^|Test Method |DO FOR ALL query parameters advertised in the API definition where the parameter value can be a list +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Generate a request using that parameter and an empty string for the parameter value. +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the server properly interprets that parameter value as an empty list +
{nbsp}{nbsp}DONE +
DONE
|===
////

[[ats_core_query-param-list-empty]]
[abstract_test]
====
[%metadata]
label:: /conf/core/query-param-list-empty
subject:: <<req_core_query-param-list-empty,/req/core/query-param-list-empty>>
test-purpose:: For every query parameter where the value may be a list, validate that the server interprets an empty string as an empty list.
test-method::
+
--
DO FOR ALL query parameters advertised in the API definition where the parameter value can be a list +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Generate a request using that parameter and an empty string for the parameter value. +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the server properly interprets that parameter value as an empty list +
{nbsp}{nbsp}DONE +
DONE
--
====
