[[ats_core_query-param-value-integer]]

////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/core/query-param-value-integer*
^|Test Purpose |For every query parameter where the value is an integer, validate that the server correctly interprets properly encoded integer values.
^|Requirement |<<req_core_query-param-value-integer,/req/core/query-param-value-integer>>
^|Test Method |DO FOR ALL query parameters advertised in the API definition where the parameter value is an integer +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Generate a request using that parameter and an unsigned numeric string for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the server properly interprets that parameter value as an unsigned integer +
{nbsp}{nbsp}{nbsp}{nbsp}3. Generate a request using that parameter and a negative signed numeric string for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}4. Validate that the server properly interprets that parameter value as a signed negative integer value +
{nbsp}{nbsp}DONE +
DONE
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/core/query-param-value-integer
subject:: <<req_core_query-param-value-integer,/req/core/query-param-value-integer>>
test-purpose:: For every query parameter where the value is an integer, validate that the server correctly interprets properly encoded integer values.
test-method::
+
--
DO FOR ALL query parameters advertised in the API definition where the parameter value is an integer +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Generate a request using that parameter and an unsigned numeric string for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the server properly interprets that parameter value as an unsigned integer +
{nbsp}{nbsp}{nbsp}{nbsp}3. Generate a request using that parameter and a negative signed numeric string for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}4. Validate that the server properly interprets that parameter value as a signed negative integer value +
{nbsp}{nbsp}DONE +
DONE
--
====
