[collection-description-example-1]

This Collection Description example response in JSON is for a single "buildings" collection.

The basic descriptive information includes:

* "id": an identifier for this collection
* "title": human-readable title for this collection
* "description": longer text describing this collection
* "attribution": markup providing attribution (owner, producer, logo, etc.) of this collection

The response includes links to:

* the response itself (link relation type: `self`),
* representations of this response in other formats are referenced using (link relation type: `alternate`),
* an additional link is to a logical schema for the collection (link relation type: `[ogc-rel:schema]`).

Finally, this response includes both spatial and temporal extents.

Reference system information is not provided as the service provides geometries only in the default system (spatial: WGS 84 longitude/latitude; temporal: Gregorian calendar).

.Example `/collections/{collectionId}` response describing a collections
[source,json]
----
{
  "id": "buildings",
  "title": "Buildings",
  "description": "Buildings in the city of Bonn.",
  "extent": {
    "spatial": [ 7.01, 50.63, 7.22, 50.78 ],
    "temporal": [ "2010-02-15T12:34:56Z", "2018-03-18T12:11:00Z" ]
  },
  "links": [
    { "href": "https://data.example.org/collections/buildings",
      "rel": "self", "type": "application/json" },
    { "href": "https://data.example.org/collections/buildings/schema",
      "rel": "[ogc-rel:schema]", "type": "application/schema+json",
      "title": "Logical schema for buildings" }
  ]
}
----
