[[rc_core-section]]
== Core Requirements Class

The following requirements and recommendations define protocol-level conventions that should be applicable to all OGC Web APIs.

include::requirements/requirements_class_core.adoc[]

[[http-protocol]]
=== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/general/REQ_http.adoc[]

[[http-status-codes]]
=== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
^|Status code ^|Description
^|`200` |A successful request.
^|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
^|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
^|`304` |An entity tag was provided in the request and the resource has not changed since the previous request.
^|`307` |The target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.
^|`308` |Indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
^|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
^|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
^|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
^|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
^|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
^|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
^|`500` |An internal error occurred in the server.
!===

The return status codes described in <<status-codes>> do not cover all possible conditions. See <<rfc7231,IETF RFC 7231>> for a complete list of HTTP status codes.

include::recommendations/general/PER_additional-status-codes.adoc[]

When a server encounters an error in the processing of a request, the server may wish to include information in addition to the status code in the response. Since Web API interactions are often machine-to-machine, a machine-readable report would be preferred. <<rfc7807,IETF RFC 7807>> addresses this need by providing "Problem Details" response schemas for both JSON and XML.

include::recommendations/general/REC_problem-details.adoc[]

[[query-parameter-requirements]]
=== Query parameters

==== Parameter Names

include::requirements/general/REQ_query-param-name-unknown.adoc[]

The criteria for a parameter to be "specified" in the API definition depends on the API definition language used, the complexity of the resources exposed, and the ability of the API server to tolerate errors.

A service implementer should endeavor to provide as much detail in the server's API definition as the API definition language allows. However, there is no requirement for the API definition to list every endpoint for which there is a non-404 behavior, for it to list every possible query parameter that might affect the behavior of an endpoint, or for it to list every possible value that each query parameter might accept.

include::recommendations/general/PER_query-param-name-specified.adoc[]

include::recommendations/general/PER_query-param-name-tolerance.adoc[]

==== Parameter Values

include::requirements/general/REQ_query-param-value-invalid.adoc[]

The criteria for a parameter value to be considered "invalid" varies with the expressiveness of the API definition language used and the ability of the API server to tolerate errors.

A service implementer should endeavor to provide as much detail in the server's API definition as the API definition language allows. However, there is no requirement to list every possible value that each query parameter might accept. Rather, the API implementation should include a reasonable degree of error recovery.

include::recommendations/general/PER_query-param-value-specified.adoc[]

include::recommendations/general/PER_query-param-value-tolerance.adoc[]

[[web-caching-section]]
=== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc7232,HTTP 1.1 (RFC 7232)>>.

include::recommendations/general/REC_etag.adoc[]

[[cross-origin-section]]
=== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/general/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[string-internationalization-section]]
===  String Internationalization

If the server supports representing resources in multiple languages, the usual HTTP content negotiation mechanisms apply. The client states its language preferences in the ``Accept-Language`` header of a request and the server responds with responses that have linguistic text in the language that best matches the requested languages and the capabilities of the server.

include::recommendations/general/REC_string-internationalization.adoc[]

For example, if JSON-LD is used as an encoding, the built-in capabilities to https://www.w3.org/TR/json-ld/#string-internationalization[annotate a string with its language] should be used.

The http://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/link.yaml[link object] based on <<rfc8288,RFC 8288 (Web Linking)>> includes a ``hreflang`` attribute that can be used to state the language of the referenced resource. This can be used to include links to the same data in, for example, English or French. Just like with <<resource-encoding-section,multiple encodings>>, a server that wants to use language-specific links will have to support a mechanism to mint language-specific URIs for resources in order to express links to, for example, the same resource in another language. Again, this document does not mandate any particular approach how such a capability is supported by the server.

[[resource-encoding-section]]
=== Resource Encodings

A Web API provides access to <<resource-definition,resources>> through <<representation-definition,representations>> of those resources. One property of a representation is the format used to encode it for transfer. Components negotiate the encoding format to use through the content negotiation process defined in <<rfc7231,IETF RFC 7231>>.

Additional content negotiation techniques are allowed, but support is not required of implementations conformant to this Standard.

While this Standard does not specify any mandatory encoding, the following encodings are recommended:

[[rec_html]]
HTML encoding recommendation:
include::recommendations/general/REC_html.adoc[]

[[rec_json]]
JSON encoding recommendation:
include::recommendations/general/REC_json.adoc[]

Requirement <<req_core_http,``/req/core/http``>> implies that the encoding of a server response is determined using content negotiation as specified by the HTTP RFC.

The section <<mediatypes-section,Media Types>> includes guidance on media types for <<rc_encoding-section,encodings>> that are specified in this document.

Note that any server that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, such as, to alternate representations of the same resource. This Standard does not mandate any particular approach for how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism of how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, such as manipulating ("hacking") URIs in the browser address bar, can study the API Definition document for that server.

Two common approaches are to use:

* An additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");
* An additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.

[[parameter-encoding-section]]
=== Parameter Encoding

The following sections provide the requirements and guidelines for encoding parameters for use in an OGC Web API request.

OGC Web API requests are issued using a URI. The URI syntax is defined in <<rfc3986,IETF RFC 3986>>. Rules for building URI Templates can be found in <<rfc6570,IETF RFC 6570>>.

The Backus-Naur Form (BNF) definition of a URI is provided in Annex <<uri-bnf-annex>>.

==== Capitalization

<<rfc3986,IETF RFC 3986>> sections 6.2.2.1 and 2.1 provide the requirements for capitalization in URIs.

include::requirements/general/REQ_query-param-capitalization.adoc[]

In order to minimize capitalization issues for implementers of OGC Web API standards:

include::recommendations/general/REC_query-param-capitalization.adoc[]

A Web API may allow filtering on properties of the target resource. In that case, the parameter name would be the name of the resource property. These names are defined by the standards and specifications defining the resource and cannot be constrained by this Standard.

==== Parameter Value Lists

Parameters may pass more than one value. These lists of parameter values may be passed in two ways.

. Repeated name:value pairs where the parameter name is repeated for each value in the list
. A parameter name followed by a delimited list of values.

The following requirements define how to encode a delimited list (case 2) of parameter values. They do not apply if replication (case 1) is used.

include::requirements/general/REQ_query-param-list-delimiter.adoc[]

include::requirements/general/REQ_query-param-list-escape.adoc[]

include::requirements/general/REQ_query-param-list-empty.adoc[]

Thus, two successive commas indicate an empty item, as does a leading comma or a trailing comma. An empty list can either be interpreted as a list containing no items or as a list containing a single empty item, depending on the context.

==== Numeric and Boolean Values

The Geospatial field is a mathematical discipline. A clear and accurate exchange of mathematical values is essential. The encoding rules in this section standardize the encoding of numeric and Boolean primitives when included in a URI. These rules are based on the computer science basic data types identified by <<k-and-r-1978,Kernighan and Ritchie>>.

Boolean values conform to the following requirement.

include::requirements/general/REQ_query-param-value-boolean.adoc[]

Integer values conform to the following requirement.

include::requirements/general/REQ_query-param-value-integer.adoc[]

Real numbers can be represented using either the decimal or double (exponential) format. The decimal format is typically used except for very large or small values.

Decimal values conform to the following requirement.

include::requirements/general/REQ_query-param-value-decimal.adoc[]

Double values conform to the following requirement.

include::requirements/general/REQ_query-param-value-double.adoc[]

Special values, if supported, should conform to the following recommendation.

include::recommendations/general/REC_query-param-value-special.adoc[]
