////
[[ats_core_query-param-value-boolean]]
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/core/query-param-value-boolean*
^|Test Purpose |For every query parameter where the value is a boolean, validate that the server correctly interprets boolean values of "true" and "false".
^|Requirement |<<req_core_query-param-value-boolean,/req/core/query-param-value-boolean>>
^|Test Method |DO FOR ALL query parameters advertised in the API definition where the parameter value is a boolean +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Generate a request using that parameter and the string "true" for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the server properly interprets that parameter value as true boolean value +
{nbsp}{nbsp}{nbsp}{nbsp}3. Generate a request using that parameter and the string "false" for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}4. Validate that the server properly interprets that parameter value as false boolean value +
{nbsp}{nbsp}DONE +
DONE
|===
////

[[ats_core_query-param-value-boolean]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/query-param-value-boolean
subject:: <<req_core_query-param-value-boolean,/req/core/query-param-value-boolean>>
test-purpose:: For every query parameter where the value is a boolean, validate that the server correctly interprets boolean values of "true" and "false".
test-method::
+
--
DO FOR ALL query parameters advertised in the API definition where the parameter value is a boolean +
{nbsp}{nbsp}DO FOR ALL operations for which that parameter is valid +
{nbsp}{nbsp}{nbsp}{nbsp}1. Generate a request using that parameter and the string "true" for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}2. Validate that the server properly interprets that parameter value as true boolean value +
{nbsp}{nbsp}{nbsp}{nbsp}3. Generate a request using that parameter and the string "false" for the parameter value +
{nbsp}{nbsp}{nbsp}{nbsp}4. Validate that the server properly interprets that parameter value as false boolean value +
{nbsp}{nbsp}DONE +
DONE
--
====
