== Conformance
Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

OGC API-Common provides a common foundation for OGC API standards. It is anticipated that this standard will only be implemented through inclusion in other standards. Therefore, all the relevant abstract tests in Annex A shall be included or referenced in the Abstract Test Suite in each separate standard that normatively references this standard.

This standard identifies four conformance classes. The conformance classes implemented by an OGC API are advertised through the /conformance path on the landing page. Each conformance class is defined by one requirements class. The tests in Annex A are organized by Requirements Class. So an implementation of the _Core_ conformance class must pass all tests specified in Annex A for the _Core_ requirements class.

The requirements classes for OGC API-Common are:

* <<rc_core-section,Core>>

The _Core Requirements Class_ is the minimal useful service interface for an OGC API. The requirements specified in this requirements class are mandatory for all OGC APIs

Additional capabilities such as support for transactions, complex data structures, and rich queries are specified in additional OGC API standards and in OGC managed API extensions. Those standards and extensions build on the API-Common foundation to provide the full functionality required of any OGC API implementation. 

* <<rc_encodings-section,Encodings>>
** <<rc_html-section,HTML>>
** <<rc_json-section,JSON>>

The _Core_ requirements class does not mandate a specific encoding or format for representing resources. The _HTML_ and _JSON_ requirements classes specify representations for these resources in commonly used encodings for spatial data on the web.

Neither of these encodings is mandatory. An implementor of the _API-Common_ standard may decide to implement another encoding instead of, or in addition to, these two.

* <<rc_oas30-section,OpenAPI 3.0>>

The _API-Common_ does not mandate any encoding or format for the formal definition of the API. The prefered option is the OpenAPI 3.0 specification. The _OpenAPI 3.0_ requirements class has been specified for APIs implementing OpenAPI 3.0.

