[[rc_core-section]]
== Requirement Class "Core"
:sectnums:

include::requirements/requirements_class_core.adoc[]

The Core Conformance Class of API-Common describes how the core resources are accessed through an OGC conformant API. The resources described in this Requirements Class are organized around the following resources:

[#core-resources-table,reftext='{table-caption} {counter:table-num}']
.Common Core Resources
[width="90%",cols="2,6",options="header"]
|===
^|**URI Path** ^|**Description**
^|"/" |the <<landing-page,landing page>>
^|"/api" |the <<api-definition,API Definition>> document for this API
^|"/conformance" |the <<conformance-classes,conformance>> information for this API
|===

In addition, requirements which are applicable to all OGC API standards and are not specific to a resource type are included in the <<general-requirements,General Requirements>> section.

[[landing-page]]
=== API landing page

Each API has a single landing page on the `{root}` node.

The purpose of the landing page is to provide clients with a starting point for using the API. It provides the basic information needed to understand the purpose, structure, and capabilities of the API. The landing page also serves as the starting point for navigation. Any resource exposed through an API can be accessed using a path or link starting from the landing page.

==== Operation

include::requirements/core/REQ_root-op.adoc[]

==== Response

include::requirements/core/REQ_root-success.adoc[]

In addition to the required resources, links to additional resources may be included in the Landing Page.

The landing page returned by this operation is based on the following link:https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/landingPage.json[Json schema].

.landingPage.json
[source, JSON]
include::openapi/schemas/landingPage.json[]

Examples of OGC landing pages are provided in <<landing-page-examples>>.

==== Error Situations

See <<http-status-codes>> for general guidance.

[[api-definition]]
=== API Definition

Every API is expected to provide a definition that describes capabilities provided by the API. This standard can be used by developers to understand API-Common, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

==== Operation

include::requirements/core/REQ_api-definition-op.adoc[]

==== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recommendations/core/REC_api-definition-oas.adoc[]

If multiple API definition formats are supported, use content negotiation to select the desired representation.

==== Error Situations

See <<http-status-codes>> for general guidance.

[[conformance-classes]]
=== Declaration of Conformance Classes

The OGC Web API Standards define a collection of modules which can be assembled into a Web API. The first question a client will ask when accessing one of these APIs is "what are you?" In other words, what modules were used to create you? Since implementors have a choice on which modules to use, there is no simple answer. The best that can be done is to provide a list of the modules implemented, the Conformance Classes.

The list of Conformance Classes is key to understanding and using an OGC Web API. So it is important that they are easy to access. A simple GET using an easily constructed URL is all that should be required. Therefore, the path to the Conformance Classes is fixed. It is always the same for every OGC Web API.

Ease of access is also supported by the structure of the Conformance Class resource. It is a simple list of URIs. This is a structure that requires almost no parsing and little interpretation. Designed to be accessible to even the simplest client.

==== Operation

include::requirements/core/REQ_conformance-op.adoc[]

==== Response

include::requirements/core/REQ_conformance-success.adoc[]

The conformance resource returned by this operation is based on the following link:https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/confClasses.json[Conformance Schema]. 

Examples of OGC conformance resources are provided in <<conformance-response-examples>>.

.Conformance Schema
[source, JSON]
include::openapi/schemas/confClasses.json[]

==== Error situations

See <<http-status-codes>> for general guidance.
