[[rc_core-section]]
== Requirement Class "Core"
:sectnums:

include::requirements/requirements_class_core.adoc[]

The Core Requirements Class of the API-Common Core Standard describes how `core` resources are accessed through an OGC conformant Web API. The requirements that make up this requirements class are grouped into two categories. <<general-requirements-section,General requirements>> are requirements that are applicable regardless of the resource being accessed. <<resource-requirements-section,Resource requirements>> are requirements that define the `core` resources and their applicable constraints. 

include::../general/clause_8_general.adoc[]

[[resource-requirements-section]]
=== Resource Requirements

The `core` resources are introduced in <<core-resources-table>>. The requirements and recommendations applicable to these resources are provided in the sections below.

[#core-resources-table,reftext='{table-caption} {counter:table-num}']
.Common Core Resources
[width="90%",cols="2,6",options="header"]
|===
^|**URI Path** ^|**Description**
^|"/" |the <<landing-page,landing page>>
^|"/api" |the <<api-definition,API Definition>> document for this API
^|"/conformance" |the <<conformance-classes,conformance>> information for this API
|===

[[landing-page]]
==== API landing page

An OGC Web API has a single landing page on the `{root}` node.

The purpose of the landing page is to provide clients with a starting point for using the API. Any resource exposed through an API can be accessed by following paths or links starting from the landing page.

The landing page includes three metadata elements: title, description, and attribution. These three elements describe the API as a whole. Clients can expect to encounter metadata that is more resource-specific as they follow links and paths from the landing page. 

While the three metadata elements are defined as text strings, the attribution element is special. Specifically, The attribution element can contain markup text. Markup allows a text string to import images and format text. The capabilities are only limited by the markup language used. See the example <<json-landing-page,landing page>> for an example of the use of markup in the attribution element.

===== Operation

include::requirements/core/REQ_root-op.adoc[]

===== Response

include::requirements/core/REQ_root-success.adoc[]

The landing page returned by this operation is based on the following link:https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/landingPage.json[JSON schema].

.landingPage.json
[source, JSON]
include::openapi/schemas/landingPage.json[]

That OGC Web APIs provide a set of Service Metadata that identifies the service and provides information about the service provider is recommended.     

include::recommendations/core/REC_service-metadata.adoc[]

Additional information about Service Metadata can be found in the http://docs.opengeospatial.org/DRAFTS/20-071.html#service-metadata-section[OGC API - Common Users Guide].

Examples of OGC landing pages are provided in <<landing-page-examples>>.

In addition to the required resources, links to additional resources may be included in the Landing Page.

===== Error Situations

See <<http-status-codes>> for general guidance.

[[api-definition]]
==== API Definition

Every API implementation should provide an API Definition resource that describes capabilities provided by that API. This resource can be used by client developers to understand the supported services, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

===== Operation

include::requirements/core/REQ_api-definition-op.adoc[]

include::recommendations/core/REC_api-definition-op.adoc[]

===== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recommendations/core/REC_api-definition-oas.adoc[]

===== Error Situations

See <<http-status-codes>> for general guidance.

[[conformance-classes]]
==== Declaration of Conformance Classes

The OGC Web API Standards define a collection of modules that can be assembled into a Web API. The first question a client will ask when accessing one of these APIs is "what are you?" In other words, what modules were used to create you? Since implementers have a choice on the modules to use, there is no simple answer. The best that can be done is to provide a list of the modules implemented, a declaration of the Conformance Classes.

The list of Conformance Classes is key to understanding and using an OGC Web API. So it is important that they are easy to access. A simple GET using an easily constructed URI is all that should be required. Therefore, the path to the Conformance Declaration is fixed.

Ease of access is also supported by the structure of the Conformance Declaration resource. It is a simple list of URIs. This is a structure that requires almost no parsing and little interpretation and is designed to be accessible to even the simplest client.

===== Operation

include::requirements/core/REQ_conformance-op.adoc[]

===== Response

include::requirements/core/REQ_conformance-success.adoc[]

The Conformance Declaration resource returned by this operation is based on the following link:https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/confClasses.json[Conformance Declaration Schema]. 

Examples of OGC Conformance Declarations are provided in <<conformance-response-examples>>.

.Conformance Declaration Schema
[source, JSON]
include::openapi/schemas/confClasses.json[]

===== Error situations

See <<http-status-codes>> for general guidance.
