[abstract]
== Abstract

The OGC has extended their suite of standards to include https://en.wikipedia.org/wiki/Resource-oriented_architecture[Resource Oriented Architectures] and https://portal.ogc.org/files/?artifact_id=71776&version=1[Web APIs]. In the course of developing these standards, some practices proved to be common across multiple OGC Web API standards. These common practices are documented in the OGC API - Common standard. The OGC API - Common standard is a multi-part standard that specifies reusable building-blocks that can be used in the construction of OGC API Standards. This document presents Part 1, the Core, of the OGC API – Common standard. Standards developers will use these building-blocks in the construction of other OGC Standards that relate to Web APIs. The result is a modular suite of coherent API standards which can be adapted by a system designer for the unique requirements of their system.

The purpose of the OGC API - Common - Part 1: Core Standard (API-Core) is to define those fundamental building blocks and requirements which are applicable to all OGC Web API Standards. 

[[preface-section]]
== Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[[security-considerations-section]]
== Security considerations

The OGC API - Common - Part 1: Core Standard does not specify any specific security controls. However, it was constructed so that security controls can be added without impacting conformance.

See <<rc_oas30-security>> for a discussion of OpenAPI support for security controls.

[[submitters-section]]
== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[#submitters-table,reftext='{table-caption} {counter:table-num}']
.Submitters
[width="90%",cols="4,6",options="header"]
|===
|*Name* |*Affiliation*
|Charles Heazel _(editor)_ |Heazeltech
|David Blodgett |U.S. Geological Survey
|Clemens Portele |interactive instruments GmbH
|Sylvester Hagler |U.S. National Geospatial-Intelligence Agency
|Jeffrey Harrison |U.S. Army Geospatial Center
|Frédéric Houbie |Hexagon
|Jérôme Jacovella-St-Louis |Ecere Corporation
|Chris Little | U.K. Met Office
|Joan  Masó |UAB-CREAF
|Donald Sullivan |NASA
|Panagiotis (Peter) A. Vretanos |CubeWerx Inc., part of the MariaDB Corporation
|===
