== Conventions

=== Identifiers

The <<WEBARCH,Architecture of the World Wide Web>> establishes the URI as the single global identification system for the Web. Therefore, URIs or <<rfc6570,URI Templates>> are used in OGC Web API standards to identify key entities in those standards.  

The normative provisions in this draft standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-common-1/1.0`.

All <<requirement-definition,Requirements>>, <<ctm-definition,Conformance Modules>>, and <<ctc-definition,Conformance Classes>> that appear in this document are denoted by partial URIs that are relative to this base.

A key requirement of Web API standards is the unambiguous identification of the <<resource-definition,resources>> they address. In an implementation of such a standard, URIs would be used to identify those resources. A standard, however, is not an implementation. A standard can identify potential resources, but not the resources themselves. Therefore, OGC Web API standards use <<rfc6570,URI Templates>> to identify <<resource-category-definition,resource categories>>. These resource categories are instantiated in the implementation of the standard.

The scope of each URI Template is specified in the standard. In some cases, API implementations are required to implement the template as a path in their API. In most cases they are optional.

Implementation of the URI Templates is recommended in that they provide a common look and feel to implementations of OGC Web API standards.

=== Link relations

<<rfc8288,RFC 8288 (Web Linking)>> is used to express relationships between resources. Link relation types from the https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA Link Relations Registry] are used wherever possible. Additional link relation types are registered with the https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/linkRelationTypes/linkrelations.csv[OGC Link Relation Registry].

The following link-relations are in common use by OGC Web API Standards.

* *alternate*: Refers to a substitute for this context. [IANA]

* *collection*: The target IRI points to a resource which represents the collection resource for the context IRI. [IANA]

* *conformance*: Refers to a resource that identifies the specifications that the link's context conforms to. [OGC]

* *data*: refers to the root resource of a dataset in an API. [OGC]

* *describedby*: Refers to a resource providing information about the link's context. [IANA]

* *item*: The target IRI points to a resource that is a member of the collection represented by the context IRI. [IANA]

* *items*: Refers to a resource that is comprised of members of the collection represented by the link's context. [OGC]

* *license*: Refers to a license associated with this context. [IANA]

* *self*: Conveys an identifier for the link's context. [IANA]

* *service-desc*: Identifies service description for the context that is primarily intended for consumption by machines. [IANA]

** API definitions are considered service descriptions.

* *service-doc*: Identifies service documentation for the context that is primarily intended for human consumption. [IANA]

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API. For example, an *enclosure* link could reference a bulk download of a collection. Or a *related* link on a feature could reference a related feature.

=== Use of HTTPS

For simplicity, this document only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS. It is simply a shorthand notation for "HTTP or HTTPS". In fact, most servers are expected to use <<rfc2818,HTTPS>>, not <<rfc2616,HTTP>>.

OGC Web API standards do not prohibit the use of any valid HTTP option. However, implementors should be aware that optional capabilities which are not in common use could be an impediment to interoperability.

=== HTTP URIs

This document does not restrict the lexical space of URIs used in the API beyond the requirements of the <<rc2616,HTTP>> and <<rc3986,URI Syntax>> IETF RFCs. If URIs include reserved characters that are delimiters in the URI subcomponent, these have to be percent-encoded. See Clause 2 of <<rfc3986,RFC 3986>> for details.

=== API definition

==== General remarks

So that developers can more easily learn how to use the API, good documentation is essential for every API. In the best case, documentation would be available both in HTML for human consumption and in a machine readable format that can be processed by software for run-time binding.

This OGC standard specifies requirements and recommendations for APIs that share spatial resources and want to follow a standard way of doing so. In general, APIs will go beyond the requirements and recommendations stated in this standard. They will support additional operations, parameters, and so on that are specific to the API or the software tool used to implement the API.

==== Role of OpenAPI

This document uses OpenAPI 3.0 fragments as examples and to formally state requirements. Using OpenAPI 3.0 is not required for implementing an OGC API. Other API definition languages may be used along with, or instead of, OpenAPI. However, any API definition language used should have an associated conformance class advertised through the /conformance path.  

This approach is used to avoid lock-in to a specific approach to defining an API. This standard includes a <<rc_oas30-section,conformance class>> for API definitions that follow the <<openapi,OpenAPI specification 3.0>>. Conformance classes for additional API definition languages will be added as the OGC API landscape continues to evolve.

In this document, fragments of OpenAPI definitions are shown in YAML. This is because YAML is easier to format than JSON and is typically used by OpenAPI editors.

==== References to OpenAPI components in normative statements

Some normative statements (requirements, recommendations and permissions) use a phrase that a component in the API definition of the server must be "based upon" a schema or parameter component in the OGC schema repository.

In this case, the following changes to the pre-defined OpenAPI component are permitted:

* If the server supports an XML encoding, `xml` properties may be added to the relevant OpenAPI schema components.
* The range of values of a parameter or property may be extended (additional values) or constrained (if a subset of all possible values is applicable to the server). An example for a constrained range of values is to explicitly specify the supported values of a string parameter or property using an _enum_.
* Additional properties may be added to the schema definition of a Response Object.
* Informative text may be changed or added, like comments or description properties.

For OGC API definitions that do not conform to the <<openapi,OpenAPI Specification 3.0>>, the normative statement should be interpreted in the context of the API definition language used.

==== Reusable OpenAPI components

Reusable components for OpenAPI definitions for an OGC API are referenced from this document.

CAUTION: During the development phase, these components use a base URL of "https://raw.githubusercontent.com/opengeospatial/oapi_common/master/", but eventually they are expected to be available under the base URL "http://schemas.opengis.net/ogcapi_common/1.0/openapi/".

