[[rc_encoding-section]]
== Encoding Requirements Classes

=== Overview

This clause specifies two requirements classes for encodings to be used by an OGC API implementation. These encodings are commonly used encodings for spatial data on the web:

* <<rc_html-section,HTML>>
* <<rc_json-section,JSON>>

Neither of these encodings are mandatory and an implementation of the <<rc_core-section,Core>> requirements class may implement some, all, or none of them.

[[rc_html-section]]
=== Requirement Class "HTML"

Geographic information that is only accessible in formats such as GeoJSON or GML have two issues:

* The data is not discoverable using Web crawlers and search engines,
* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, this publication should be done in a way that enables users and search engines to discover and access all of the data.

This is discussed in detail in the  <<SDWBP,W3C/OGC SDW Best Practice>>. Therefore, the OGC API - Common Standard <<rec_html,recommends>> supporting HTML as an encoding.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[rc_json-section]]
=== Requirement Class "JSON"

JSON is a text syntax that facilitates structured data interchange between programming languages. It commonly used for Web-based software-to-software interchanges. Most Web developers are comfortable with using a JSON-based format, so supporting JSON is recommended for machine-to-machine interactions.

include::requirements/requirements_class_json.adoc[]

include::requirements/json/REQ_definition.adoc[]

include::requirements/json/REQ_content.adoc[]

An example JSON Schema for the landing page is available at link:http://schemas.opengis.net/ogcapi/common/part1/1.0/schemas/landingPage.json[landingPage.json].
