== Introduction

[big]*i.     Abstract*

The OGC has extended their suite of standards to include https://en.wikipedia.org/wiki/Resource-oriented_architecture[Resource Oriented Architectures] and https://portal.ogc.org/files/?artifact_id=71776&version=1[Web APIs]. In the course of developing these standards, some practices proved to be common across multiple OGC Web API standards. These common practices are documented in the OGC API - Common Multi-Part Standard. OGC API - Common standards serve as reusable building-blocks. Standards developers will use these building-blocks in the construction of OGC Web API Standards. The result is a modular suite of coherent API standards which can be adapted by an system designer for the unique requirements of their system.

The purpose of the OGC API - Common - Part 1: Core Standard (API-Core) is to define those fundamental building blocks and requirements which are applicable to all OGC Web API Standards.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, geographic information, spatial data, API, json, html, OpenAPI, REST, Common

[big]*iii.   Preface*

*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* Ecere Corporation
* Heazeltech LLC
* Hexagon
* Interactive Instruments GmbH
* U.K. Met Office
* Universitat Autònoma de Barcelona (CREAF)
* U.S. Army Geospatial Center
* U.S. Geological Survey
* U.S. National Aeronautics and Space Administration (NASA)
* U.S. National Geospatial-Intelligence Agency

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*
|Charles Heazel _(editor)_ |Heazeltech
|David Blodgett |U.S. Geological Survey
|Clemens Portele |Interactive Instruments
|Sylvester Hagler |U.S. National Geospatial-Intelligence Agency
|Jeffrey Harrison |U.S. Army Geospatial Center
|Frédéric Houbie |Hexagon
|Jérôme Jacovella-St-Louis |Ecere Corporation
|Chris Little | U.K. Met Office
|Joan  Masó |UAB-CREAF
|Donald Sullivan |NASA
|Panagiotis (Peter) A. Vretanos |CubeWerx Inc.
|===
