[[rc_landing-page-section]]
== Landing Page Requirements Class
:sectnums:

include::requirements/requirements_class_landing-page.adoc[]

The Landing Page Requirements Class of the API-Common Core Standard describes how the `Landing Page` and its associated resources are accessed through an OGC conformant Web API. 

The Landing Page resources are introduced in <<lp-resources-table>>. The requirements and recommendations applicable to these resources are provided in the sections below.

[#lp-resources-table,reftext='{table-caption} {counter:table-num}']
.Landing Page Resources
[cols="30,15,40",options="header"]
!===
^|Resource ^|HTTP Method ^|*Description*
|Landing Page ^|GET |the <<landing-page,landing page>>
|API Definition ^|GET |the <<api-definition,API Definition>> document for this API
|Conformance Declaration ^|GET |the <<conformance-classes,conformance>> information for this API
!===

[[landing-page]]
=== API landing page

An OGC Web API has a single landing page on the `{root}` node.

The purpose of the landing page is to provide clients with a starting point for using the API. Any resource exposed through an API can be accessed by following paths or links starting from the landing page.

The landing page includes three metadata elements: title, description, and attribution. These three elements describe the API as a whole. Clients can expect to encounter metadata that is more resource-specific as they follow links and paths from the landing page. 

While the three metadata elements are defined as text strings, the attribution element is special. Specifically, The attribution element can contain markup text. Markup allows a text string to import images and format text. The capabilities are only limited by the markup language used. See the example <<json-landing-page,landing page>> for an example of the use of markup in the attribution element.

==== Operation

include::requirements/landing-page/REQ_root-op.adoc[]

==== Response

include::requirements/landing-page/REQ_root-success.adoc[]

The Landing Page returned by this operation is based on the following OpenAPI schema.

.landingPage.yaml
[source, YAML]
include::openapi/schemas/landingPage.yaml[]

In addition to the required resources, links to additional resources may be included in the Landing Page.

Examples of OGC landing pages are provided in <<landing-page-examples>>.

A JSON schema for the Landing Page resource can be found on the link:http://beta.schemas.opengis.net/ogcapi/common/part1/0.1/core/openapi/schemas/landingPage.yaml[OGC Schema Repository]. 

Additional information about the Landing Page can be found in the http://docs.opengeospatial.org/DRAFTS/20-071.html#landing-page-section[OGC API - Common Users Guide].

==== Error Situations

See <<http-status-codes>> for general guidance.

[[api-definition]]
=== API Definition

Every API implementation should provide an API Definition resource that describes the capabilities provided by that API. This resource can be used by client developers to understand the supported services, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

==== Operation

include::requirements/landing-page/REQ_api-definition-op.adoc[]

include::recommendations/landing-page/REC_api-definition-op.adoc[]

==== Response

include::requirements/landing-page/REQ_api-definition-success.adoc[]

include::recommendations/landing-page/REC_api-definition-oas.adoc[]

==== Error Situations

See <<http-status-codes>> for general guidance.

[[conformance-classes]]
=== Declaration of Conformance Classes

The OGC Web API Standards define a collection of modules that can be assembled into a Web API. The first question a client will ask when accessing one of these APIs is "what are you?" In other words, what modules were used to create you? Since implementers have a choice on the modules to use, there is no simple answer. The best that can be done is to provide a list of the modules implemented, a declaration of the Conformance Classes.

The list of Conformance Classes is key to understanding and using an OGC Web API. So it is important that they are easy to access. A simple GET using an easily constructed URI is all that should be required. Therefore, the path to the Conformance Declaration is fixed.

Ease of access is also supported by the structure of the Conformance Declaration resource. It is a simple list of URIs. This is a structure that requires almost no parsing and little interpretation and is designed to be accessible to even the simplest client.

==== Operation

include::requirements/landing-page/REQ_conformance-op.adoc[]

==== Response

include::requirements/landing-page/REQ_conformance-success.adoc[]

The Conformance Declaration returned by this operation is based on the following OpenAPI schema.

.Conformance Declaration Schema
[source, YAML]
include::openapi/schemas/confClasses.yaml[]

A JSON schema for the Landing Page resource can be found on the link:http://beta.schemas.opengis.net/ogcapi/common/part1/0.1/core/openapi/schemas/confClasses.yaml[OGC Schema Repository]. 

Examples of OGC Conformance Declarations are provided in <<conformance-response-examples>>.

==== Error situations

See <<http-status-codes>> for general guidance.
