[[rc_general-section]]
== Requirement Class "General"
:sectnums:

include::requirements/requirements_class_general.adoc[]

The General Conformance Class of API-Common captures requirements and recommentations which are applicable to all OGC Web APIs and Web API Modules.

=== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/general/REQ_http.adoc[]

[[http-status-codes]]
=== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/general/PER_additional-status-codes.adoc[]

[[query-parameter-requirements]]
=== Unknown or invalid query parameters

If a server wants to support query parameters, these have to be explicitly declared in the API definition.

include::requirements/general/REQ_query-param-known.adoc[]

Query parameters that have not been explicitly specified in the API definition for that operation will be treated as unknown.

include::requirements/general/REQ_query-param-unknown.adoc[]

If OpenAPI is used to represent the API definition, a capability exists to define query parameters without explicitly declaring them. That is,

.OpenAPI schema for query parameters
[source,java]
----
in: query
name: queryParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of ``queryParameters`` is this object:

[source,java]
----
{
  "first_parameter": "some value",
  "other_parameter": 42
}
----

In the request URI this would be expressed as ``&first_parameter=some%20value&other_parameter=42``.

include::requirements/general/REQ_query-param-invalid.adoc[]

This is a general rule that applies to all parameters, whether they are specified in this document or in additional parts. A value is invalid if it violates the API definition or any other constraint for that parameter stated in a requirement.

=== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc2616,HTTP/1.1 (RFC 2616)>>.

include::recommendations/general/REC_etag.adoc[]

[[cross-origin]]
=== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/general/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

=== Encodings

A Web API provides access to <<resource-definition,resources>> through <<representation-definition,representations>> of those resources. One property of a representation is the format used to encode it for transfer. Components negotiate which encoding format to use through the content negotiation process defined in <<rfc7231,IETF RFC 7231>>.

Additional content negotiation techniques are allowed, but support is not required of implementations conformant to this Standard.

While the OAPI Common Core standard does not specify any mandatory encoding, the following encodings are recommended:

[[rec_html]]
HTML encoding recommendation:
include::recommendations/general/REC_html.adoc[]

[[rec_json]]
JSON encoding recommndation:
include::recommendations/general/REC_json.adoc[]

[[CRS-core-section]]
=== Coordinate reference systems

As discussed in Chapter 9 of the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practices document>>, how to express and share the location of features in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, OGC API - Common uses WGS 84 longitude and latitude as the default coordinate reference system.

include::requirements/general/REQ_crs84.adoc[]

=== Link Headers

include::recommendations/general/REC_link-header.adoc[]
