[[rc_oas30-section]]
== OpenAPI 3.0 Requirements Class 

=== Basic requirements

APIs conforming to this requirements class document themselves by an link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oasDocument[OpenAPI Document].

include::requirements/requirements_class_oas30.adoc[]

include::requirements/oas30/REQ_oas-definition-1.adoc[]

CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/117[ISSUE 117] +

The OpenAPI media type has not been registered yet with IANA and will likely change. We need to update the media type after registration.

include::requirements/oas30/REQ_oas-definition-2.adoc[]

Two example OpenAPI documents are included in <<oas-examples,Annex B>>.

include::requirements/oas30/REQ_oas-impl.adoc[]

=== Complete definition

include::requirements/oas30/REQ_completeness.adoc[]

Note APIs that, for example, are access-controlled (see <<security,Security>>), support web cache validation, support CORS, or that use HTTP redirection will make use of additional HTTP status codes beyond regular codes such as `200` for successful GET requests and `400`, `404` or `500` for error situations. See <<http-status-codes>>.

Clients have to be prepared to receive responses not documented in the OpenAPI definition. For example, additional errors may occur in the transport layer outside of the server.

[[rc_oas30-exceptions]]
=== Exceptions

include::requirements/oas30/REQ_exception-codes.adoc[]

.An exception response object definition
=================
[source,YAML]
----
description: An error occurred.
content:
  application/json:
    schema:
      $ref: http://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/exception.yaml
  text/html:
    schema:
      type: string
----
=================

[[rc_oas30-security]]
=== Security

OpenAPI uses two constructs to describe the security features of an API; Security Requirements and Security Schemes. Security Requirements are packaged in an array. Only one of the Security Requirements in the array must be met in-order to authorize a request. Security Requirements are associated with one or more Security Schemes. Each Security Scheme describes a security control (ex. HTTP authentication). All of the security schemes associated with a Security Requirement must be satisfied in order for that Security Requirement to be met.

Security Requirements can be defined on following levels:

* Root - applicable to the whole API unless overriden
* Operation - only applicable to this operation. Overrides any requirements defined at the Root level. 

The OpenAPI specification currently supports the following link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object[security schemes]:

* HTTP authentication,
* an API key (either as a header or as a query parameter),
* OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and
* OpenID Connect Discovery.

include::requirements/oas30/REQ_security.adoc[]

[[rc_oas30-usage]]
=== Using OpenAPI (Informative)

The following section describes the main components of an OpenAPI document and how they should be used to construct API requests. The authoritative source is the OpenAPI 3.0 standard available https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#oasObject[here].

==== OpenAPI Document (root)

The OpenAPI document (Root) contains descriptive information about the API and serves as the root for the other parts of the document.

==== Paths

All API resources are accessed through a path. The Paths field of the OpenAPI document defines all of the paths available through this API. The Paths field is a collection of Paths Objects. Each Paths Object includes the URL or URL template for this path, any Server Objects specific to this Path, Parameters which are applicable to this Path, and an Operation Object for each of the HTTP Verbs applicable to this Path.

==== Operations

Operation Objects provide the details needed to create an HTTP request and response. Specifically, they provide definitions of the request message (including parameters) and all possible responses. In addition, they define any operation specific Server Objects or Security Requirements.

==== Parameters

Parameter Objects describe parameters which can be used in an API. These objects provide the parameter name, where it is passed (query, header, path, or cookie), and a detailed description of its' structure (if needed).  

Parameter Objects can be defined at the following levels:

* Path - applicable to all operations on this path. 
* Operation - only applicable to this operation. Overrides any parameters defined at the Path level which have the same name. 

==== Servers

An API is not restricted to a single server. Furthermore, the set of valid servers may be different for different sections of the API. An OpenAPI Server Object describes a single server. Most important, it provides the URL to that server. Server Objects are grouped into arrays. These arrays provide a list of the servers which can be used to access a section of the API.

.Example Array of Server Objects

[source,YAML]
----
servers:
  - url: https://dev.example.org/
    description: Development server
  - url: https://data.example.org/
    description: Production server
----

Server Objects can be defined on following levels:

* Root - applicable to the whole API unless overriden
* Path - applicable to all operations on this path. Servers defined at the Rool level are still valid.
* Operation - only applicable to this operation. Overrides any servers defined at the Path or Root level. 

===== Building URLs

An OpenAPI document can describe a large number of URLs. Extracting all of the URLs is a non-trivial task. The OpenAPI objects used to construct URLs are:

* Server Objects (URL template for the root and variables to populate it)
* Paths Objects (URL template for the path and parameters)
* Operation Objects (including parameters)

They are organized as follows:

{Server Object}/{Path Object}/?{Parameters}

Server Objects may be found at the OpenAPI document, Path Object, and Operation Object level. Given this potentially large number of servers, how do you create the valid paths?

We can assume that the authors of a OAS document are not doing it for their personal enjoyment. Therefore, if a Server Object is included, there must be a reason for its' presence. So the Server Objects with the most restrictive scope are the ones we should use.  Clients should look for Server Objects in the following order:

. The Operation Object,
. Then Path Item,
. The root.

The first scope where a Server Object is found dictates the behavior completely.


 IF Server Objects are supplied
     THEN save them for latter
     ELSE create a Server Object for the host of the OpenAPI document
 DO FOR each Path
     IF Server Objects are included, THEN
         Use them instead of those previously identified
     IF Parameter Objects are included, THEN
         save them for latter
     DO FOR Each Operation
         IF Server Objects are included, THEN
             Use them instead of those previously identified
         IF Parameter Objects are included THEN
             IF this parameter was previously defined
                 THEN replace the previous definition
                 ELSE add this parameter to the set.
         DO FOR Each Server Object
             Extract all URL roots
             DO FOR each URL root
                 Concatenate the URL root and Path to create a working URL
                 Concatenate the working URL with the Parameters
                 Save the completed URL for future use
             CONTINUE
         DONE
     DONE
 DONE


