[[general-requirements-section]]
=== General Requirements

The following requirements and recommentations are applicable to all OGC Web APIs.

==== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/general/REQ_http.adoc[]

[[http-status-codes]]
==== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/general/PER_additional-status-codes.adoc[]

[[query-parameter-requirements]]
==== Unknown or invalid query parameters

If a server wants to support query parameters, these have to be explicitly declared in the API definition.

include::requirements/general/REQ_query-param-known.adoc[]

Query parameters that have not been explicitly specified in the API definition for that operation will be treated as unknown.

include::requirements/general/REQ_query-param-unknown.adoc[]

If OpenAPI is used to represent the API definition, a capability exists to define query parameters without explicitly declaring them. That is,

.OpenAPI schema for query parameters
[source,java]
----
in: query
name: queryParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of ``queryParameters`` is this object:

[source,java]
----
{
  "first_parameter": "some value",
  "other_parameter": 42
}
----

In the request URI this would be expressed as

[source,java]
----
{
  &first_parameter=some%20value&other_parameter=42
}
----

include::requirements/general/REQ_query-param-invalid.adoc[]

This is a general rule that applies to all parameters, whether they are specified in this document or in additional parts. A value is invalid if it violates the API definition or any other constraint for that parameter stated in a requirement.

[[web-caching-section]]
==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc7232,HTTP/1.1 (RFC 7232)>>.

include::recommendations/general/REC_etag.adoc[]

[[cross-origin-section]]
==== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/general/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[resource-encoding-section]]
==== Resource Encodings

A Web API provides access to <<resource-definition,resources>> through <<representation-definition,representations>> of those resources. One property of a representation is the format used to encode it for transfer. Components negotiate which encoding format to use through the content negotiation process defined in <<rfc7231,IETF RFC 7231>>.

Additional content negotiation techniques are allowed, but support is not required of implementations conformant to this Standard.

While this standard does not specify any mandatory encoding, the following encodings are recommended:

[[rec_html]]
HTML encoding recommendation:
include::recommendations/general/REC_html.adoc[]

[[rec_json]]
JSON encoding recommndation:
include::recommendations/general/REC_json.adoc[]

[[parameter-encoding-section]]
==== Parameter Encoding

===== Capitalization

Parameter names SHALL be in Upper Camel Case.

All parameter value strings SHALL have the first word and any subsequent words in the name capitalized. All other letters SHALL be lower case.

EXAMPLE One possible `request` parameter value is ―GetCapabilities‖

===== Parameter Value Lists
Parameters values containing lists SHALL designate the list items using the comma (",") as a delimiter.

Additional white space shall not be used to delimit list items. 

Any list item values which include a space or comma SHALL escape the space or comma character using the URL encoding rules from <<rfc2396,IETF RFC 2396>>.

All empty entries SHALL be represented by the empty string (""). 

Thus, two successive commas indicates an empty item, as does a leading comma or a trailing comma. An empty list ("") can either be interpreted as a list containing no items or as a list containing a single empty item, depending on the context.

===== Numeric and Boolean Values

[source,java]
----
query         = *uric

uric          = reserved | unreserved | escaped
reserved      = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" | "$" | ","
unreserved    = alphanum | mark

mark          = "-" | "_" | "." | "!" | "~" | "*" | "'" | "(" | ")"
escaped       = "%" hex hex
hex           = digit | "A" | "B" | "C" | "D" | "E" | "F" |
                        "a" | "b" | "c" | "d" | "e" | "f"

alphanum      = alpha | digit
alpha         = lowalpha | upalpha

lowalpha = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" |
           "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" |
           "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
upalpha  = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" |
           "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" |
           "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
digit    = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
----

Integer numbers SHALL be represented using the URL encoding rules from <<rfc2396,IETF RFC 2396>> Section A.

integer has a lexical representation consisting of a finite-length sequence of decimal digits (#x30-#x39) with an optional leading sign. If the sign is omitted, "+" is assumed. For example: -1, 0, 12678967543233, +100000. <<xmlschema-part2,XML Schema Part 2>>

Real numbers SHALL be represented using the URL encoding rules from <<rfc2396,IETF RFC 2396>> Section A.

decimal has a lexical representation consisting of a finite-length sequence of decimal digits (#x30-#x39) separated by a period as a decimal indicator. An optional leading sign is allowed. If the sign is omitted, "+" is assumed. Leading and trailing zeroes are optional. If the fractional part is zero, the period and following zero(es) can be omitted. For example: -1.23, 12678967.543233, +100000.00, 210.<<xmlschema-part2,XML Schema Part 2>>


double values have a lexical representation consisting of a mantissa followed, optionally, by the character "E" or "e", followed by an exponent. The exponent ·must· be an integer. The mantissa must be a decimal number. The representations for exponent and mantissa must follow the lexical rules for integer and decimal. If the "E" or "e" and the following exponent are omitted, an exponent value of 0 is assumed. <<xmlschema-part2,XML Schema Part 2>>

The special values positive and negative infinity and not-a-number have lexical representations INF, -INF and NaN, respectively. Lexical representations for zero may take a positive or negative sign.

For example, -1E4, 1267.43233E12, 12.78e-2, 12 , -0, 0 and INF are all legal literals for double.


shall be represented in a manner consistent with the specification for double-precision numbers in Section 3.2.5 of [XML Schema Part 2: Datatypes]. This representation allows for integer, decimal and exponential notations. This representation also allows special values representing infinity and not-a-number, which shall not be used except where specifically allowed by an Implementation Specification. A real value is allowed in all numeric fields unless the value is explicitly restricted to integer. 

Boolean values shall be represented by the uppercase strings "TRUE" and "FALSE", representing Boolean true and false respectively.

===== Parameter Names
The set of all parameters and their names used in KVP encoding should be constant and fully specified by each specific OWS, except for allowed variations in capitalization.
That is, these parameter names should not depend on the values of other parameters, such as the specific dataset being accessed). This constancy of parameter names is required to allow describing the operation request using WSDL, and is desirable to allow use of options available in the OperationsMetadata section of service metadata (or Capabilities) documents.
EXAMPLE 1 The parameter named PARAMETER in WCS 1.0.0 GetCoverage requests fails this recommendation.
EXAMPLE 2 The ―other sample dimension(s)‖ in WMS 1.3.0 GetMap requests fails this recommendation.