[[rc_oas30-section]]
== OpenAPI 3.0 Requirements Class 

=== Basic requirements

APIs conforming to this requirements class document themselves by an link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oasDocument[OpenAPI Document].

include::requirements/requirements_class_oas30.adoc[]

include::requirements/oas30/REQ_oas-definition-1.adoc[]

include::requirements/oas30/REQ_oas-definition-2.adoc[]

Two example OpenAPI documents are included in <<oas-examples,Annex B>>.

include::requirements/oas30/REQ_oas-impl.adoc[]

=== Complete definition

include::requirements/oas30/REQ_completeness.adoc[]

Note APIs that, for example, are access-controlled (see <<security,Security>>), support web cache validation, support CORS, or that use HTTP redirection will make use of additional HTTP status codes beyond regular codes such as `200` for successful GET requests and `400`, `404` or `500` for error situations. See <<http-status-codes>>.

Clients have to be prepared to receive responses not documented in the OpenAPI definition. For example, additional errors may occur in the transport layer outside of the server.

[[rc_oas30-exceptions]]
=== Exceptions

include::requirements/oas30/REQ_exception-codes.adoc[]

.An exception response object definition
=================
[source,YAML]
----
description: An error occurred.
content:
  application/json:
    schema:
      $ref: http://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/exception.yaml
  text/html:
    schema:
      type: string
----
=================

[[rc_oas30-security]]
=== Security

OpenAPI uses two constructs to describe the security features of an API; Security Requirements and Security Schemes. Security Requirements are packaged in an array. Only one of the Security Requirements in the array must be met in-order to authorize a request. Security Requirements are associated with one or more Security Schemes. Each Security Scheme describes a security control (ex. HTTP authentication). All of the security schemes associated with a Security Requirement must be satisfied in order for that Security Requirement to be met.

Security Requirements can be defined on following levels:

* Root - applicable to the whole API unless overriden
* Operation - only applicable to this operation. Overrides any requirements defined at the Root level. 

The OpenAPI specification currently supports the following link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object[security schemes]:

* HTTP authentication,
* an API key (either as a header or as a query parameter),
* OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and
* OpenID Connect Discovery.

include::requirements/oas30/REQ_security.adoc[]

[[rc_oas30-service-metadata]]
=== Service Metadata

OGC Web Services provide a set of metadata that identifies the service and provides information about the service provider. It would be useful if OGC Web APIs provide the same information. A `service-meta` link is provided on the Landing Page for this purpose. 

include::recommendations/oas30/REC_service-metadata.adoc[]

An example of a populated OpenAPI `Info` object is provided in the <<service-metadata-examples>> section.

[[rc_oas30-query-parameter]]
=== Query Parameter Definition

OpenAPI defines query parameters using the `Parameter` object with the `in` property set to "query". The parameter name is a literal value provided by the `name` property. Since the parameter names are literals, each parameter must be described separately. 

API-Common requires that all query parameters are specified in the API definition. In the case of a Feature server, this could mean that every property of every feature type must be described in the API definition. a requirement that few implemetor would accept. 

OpenAPI provides a capability that allows additional parameters to be specified without explicitly declaring them. That is, parameters that have not been explicitly specified in the API definition for the operation will still be considered "specified" for purposes of validation (see <<per_core-query-param-specified,/per/core/query-param-specified>> and <<per_core-query-param-tolerance,/per/core/query-param-tolerance>>.

[[schema_free-form]]
.OpenAPI schema for additional "free-form" query parameters
[source,YAML]
----
in: query
name: freeFormParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of `freeFormParameters` is this object:

[source,JSON]
----
{
  "my_first_parameter": "some value",
  "my_other_parameter": 42
}
----

In the request URI this would be expressed as `&my_first_parameter=some%20value&my_other_parameter=42`.

=== Further Information

Additional guidance on using OpenAPI in OGC Web API implementations can be found in the link:http://docs.opengeospatial.org/DRAFTS/20-071.html#oas30-usage-section[OGC API - Common Users Guide].


