[[rc_encoding-section]]
== Encoding Requirements Classes

=== Overview

This clause specifies two requirements classes for encodings that may be used by an OGC Web API implementation. These encodings are commonly used for spatial data on the web applications:

* <<rc_html-section,HTML>>
* <<rc_json-section,JSON>>

Neither of these encodings are mandatory. An implementation of the OGC API - Common Standard may implement one, both, or none of them. Other encodings are possible.

[[rc_html-section]]
=== Requirement Class "HTML"

Geographic information that is only accessible in formats such as GeoJSON or GML have two issues when web application principles are considered:

* The data are not discoverable using Web crawlers and search engines,
* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, this publication should be done in a way that enables users and search engines to discover and access all of the data.

This is discussed in detail in the  <<SDWBP,W3C/OGC SDW Best Practice>>. Therefore, the OGC API - Common Standard <<rec_html,recommends>> supporting HTML as an encoding.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::recommendations/html/REC_schema-org.adoc[]

[[rc_json-section]]
=== Requirement Class "JSON"

JSON is a lightweight data-interchange format desiged to facilitate structured data interchange between applications. JSON is commonly used for Web-based software-to-software interchanges. Most Web developers are comfortable with using a JSON-based format. Therefore support for JSON is recommended for machine-to-machine interactions.

include::requirements/requirements_class_json.adoc[]

include::requirements/json/REQ_definition.adoc[]

include::requirements/json/REQ_content.adoc[]

include::recommendations/JSON/REC_Problem-Details.adoc[]

An example JSON Schema for the landing page is available at link:beta.schemas.opengis.net/ogcapi/common/part1/0.1/core/openapi/schemas/landingPage.yaml[landingPage.yaml].

An example JSON Problem Details report is available at link:beta.schemas.opengis.net/ogcapi/common/part1/0.1/core/openapi/examples/ExceptionExample.yaml[ExceptionExample.yaml].

