[[rc_core-section]]
== Requirement Class "Core"
:sectnums:

include::requirements/requirements_class_core.adoc[]

The Core Conformance Class of API-Common describes how <<foundation-resources-introduction,Foundation Resources>> are accessed through an OGC conformant API. The resources described in this Requirements Class are organized around the following standard paths:

. "/" - the landing page
. "/api" - the API Definition document for this API
. "/conformance" - the conformance information for this API

In addition, requirements which are applicable to all OGC API standards and are not specific to a resource type are included in the <<general-requirements,General Requirements>> section.

[[landing-page]]
=== API landing page

Each API has a single landing page (path `/`).

The purpose of the landing page is to provide clients with a starting point for using the API. It provides the basic information needed to understand the purpose, structure, and capabilities of the API. The landing page also serves as the starting point for navigation. Any resource exposed through an API can be accessed using a path or link starting from the landing page.

==== Operation

include::requirements/core/REQ_root-op.adoc[]

==== Response

include::requirements/core/REQ_root-success.adoc[]

In addition to the required resources, links to additional resources may be included in the Landing Page.

The landing page returned by this operation is based on the following link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/landingPage.json[Json schema].

.landingPage.json
[source, JSON]
include::openapi/schemas/landingPage.json[]

Examples of OGC landing pages are provided in <<landing-page-examples>>.

==== Error Situations

See <<http-status-codes>> for general guidance.

[[api-definition]]
=== API Definition

Every API is expected to provide a definition that describes capabilities provided by the API. This standard can be used by developers to understand API-Common, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

==== Operation

include::requirements/core/REQ_api-definition-op.adoc[]

==== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recommendations/core/REC_api-definition-oas.adoc[]

If multiple API definition formats are supported, use content negotiation to select the desired representation.

==== Error Situations

See <<http-status-codes>> for general guidance.

[[conformance-classes]]
=== Declaration of Conformance Classes

To support "generic" clients that want to accessing OGC APIs in general - and not "just" a specific API / server, the API has to declare the conformance classes it implements and conforms to.

==== Operation

include::requirements/core/REQ_conformance-op.adoc[]

==== Response

include::requirements/core/REQ_conformance-success.adoc[]

The conformance resource returned by this operation is based on the following link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/confClasses.json[Conformance Schema]. Examples of OGC conformance resources are provided in <<conformance-response-examples>>.

.Conformance Schema
[source, JSON]
include::openapi/schemas/confClasses.json[]

==== Error situations

See <<http-status-codes>> for general guidance.

[[general-requirements]]
=== General Requirements

The following general requirements and recommendations apply to all OGC APIs.

==== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/core/REQ_http.adoc[]

[[http-status-codes]]
==== HTTP Status Codes

NOTE: ISSUE: Should we expand our explanation of HTTP status codes? See issues https://github.com/opengeospatial/oapi_common/issues/75[75], and https://github.com/opengeospatial/oapi_common/issues/73[73].

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/core/PER_additional-status-codes.adoc[]

[[query-parameter-requirements]]
==== Unknown or invalid query parameters

If a server wants to support query parameters, these have to be explicitly declared in the API definition.

include::requirements/core/REQ_query-param-known.adoc[]

Query parameters that have not been explicitly specified in the API definition for that operation will be treated as unknown.

include::requirements/core/REQ_query-param-unknown.adoc[]

If OpenAPI is used to represent the API definition, a capability exists to define query parameters without explicitly declaring them. That is,

.OpenAPI schema for query parameters
[source,java]
----
in: query
name: queryParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of ``queryParameters`` is this object:

[source,java]
----
{
  "first_parameter": "some value",
  "other_parameter": 42
}
----

In the request URI this would be expressed as ``&first_parameter=some%20value&other_parameter=42``.

include::requirements/core/REQ_query-param-invalid.adoc[]

This is a general rule that applies to all parameters, whether they are specified in this document or in additional parts. A value is invalid if it violates the API definition or any other constraint for that parameter stated in a requirement.

==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc2616,HTTP/1.1 (RFC 2616)>>.

include::recommendations/core/REC_etag.adoc[]

[[cross-origin]]
==== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

==== Encodings

NOTE: Note to the Editor: Is this discussion of content negotiation sufficient? If not, what else do we need? See issues https://github.com/opengeospatial/oapi_common/issues/57[57] and https://github.com/opengeospatial/oapi_common/issues/28[28].

While the OAPI Common Core standard does not specify any mandatory encoding, the following encodings are recommended. See <<overview,Clause 7 (Overview)>> for a discussion of this issue.

[[rec_html]]
HTML encoding recommendation:
include::recommendations/core/REC_html.adoc[]

[[rec_json]]
JSON encoding recommndation:
include::recommendations/core/REC_json.adoc[]

Requirement <<req_core_http,`/req/core/http`>> implies that the encoding of a response is determined using content negotiation as specified in <<rfc7231,IETF RFC 7231>>.

The section <<mediatypes,Media Types>> includes guidance on media types for encodings that are specified in this standard.

Note that any API that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, such as to alternate representations of the same resource. This standard does not mandate how this mechanism shall be supported by a conformant API.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, manipulating ("hack") the browser address bar, can study the API definition.

[NOTE]
=========================================================
Two common approaches are:

* An additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");
* An additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.
=========================================================

[[CRS-core-section]]
==== Coordinate reference systems

As discussed in Chapter 9 of the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practices document>>, how to express and share the location of features in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, OGC API - Common uses WGS 84 longitude and latitude as the default coordinate reference system.

include::requirements/core/REQ_crs84.adoc[]

==== Link Headers

include::recommendations/core/REC_link-header.adoc[]
