[[terms_and_definitions]]
== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of https://portal.opengeospatial.org/files/?artifact_id=38867[OGC Web Services Common] (OGC 06-121r9), which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

[[landing-page-definition]]
* *Landing Page* +
This is the root resource of an API. It serves as the root node of the API Resource tree and provides the information needed to navigate all of the resources exposed through the API.

[[representation-definition]]
* *Representation* +
the current or intended state of a <<resource-definition,resource>> encoded for exchange between components. (based on <<fielding2000,Fielding 2000>>)

[[resource-definition]]
* *Resource* +
. Any information that can be named. (<<fielding2000,Fielding 2000>>) +
. The intended conceptual target of a hypertext reference. (<<fielding2000,Fielding 2000>>)

[[resource-type-definition]]
* *Resource Type* +
the definition of a type of <<resource-definition,resource>>. Resource types are re-usable components which are independent of where the resource resides in the API.  

[[uri-definition]]
* *Uniform Resource Identifier (URI)* +
an identifier consisting of a sequence of characters matching the syntax rule named <<identifier-concepts,<URI>>>. (<<rfc3986,IETF RFC 3986>>)

[[url-definition]]
* *Uniform Resource Locator (URL)* +
the subset of <<uri-definition,URIs>> that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (e.g., its network "location"). (<<rfc3986,IETF RFC 3986>>)

[[webapi-definition]]
* *Web API* +
API using an architectural style that is founded on the technologies of the Web. (<<DWBP,W3C Data on the Web Best Practices>>)


