[[overview]]
== Overview

[[evolution-introduction]]
=== Evolution from OGC Web Services

OGC Web Service (OWS) standards implement a Remote-Procedure-Call-over-HTTP architectural style using XML for payloads. This was the state-of-the-art when OGC Web Services (OWS) were originally designed in the late 1990s. However, technology has evolved. New Resource-Oriented APIs provide an alternative to Service-Oriented Web Services. New OGC Web API standards are under development to provide API alternatives to the OWS standards.

The OGC API - Common suite of standards specify common modules for defining OGC Web API standards that follow the current Web architecture. In particular, the recommendations as defined in the <<SDWBP,W3C/OGC best practices for sharing Spatial Data on the Web>> as well as the <<DWBP,W3C best practices for sharing Data on the Web>>.

In addition to the general alignment with the architecture of the Web (e.g., consistency with HTTP/HTTPS, hypermedia controls), another goal for OGC API standards is modularization. This goal has several facets:

* A common `core` which is the same for all OGC Web API standards. This OGC API - Common - Core Standard provides the information needed by a client to understand and use an OGC Web API.
* Clear separation between common requirements and more resource specific capabilities. The OGC API - Common suite of standards specify the _common_ requirements that may be relevant to almost anyone who wants to build an API for spatial resources. Resource-specific requirements are addressed in resource-specific OGC standards.
* Technologies that change more frequently are decoupled and specified in separate modules ("conformance classes" in OGC terminology). This enables, for example, the use/re-use of new encodings for spatial data or API descriptions.
* Modularization is not just about a single "service". OGC APIs provide building blocks that can be reused in APIs in general. In other words, a server supporting the OGC-Feature API should not be seen as a standalone service.  Rather, this server should be viewed as a collection of API building blocks which together implement API-Feature capabilities. A corollary of this is that it should be possible to implement an API that simultaneously conforms to conformance classes from the Feature, Coverage, and other current or future OGC Web API standards.

[[modular-API-introduction]]
=== Modular APIs

A goal of OGC API standards is to provide rapid and easy access to spatial resources. To meet this goal, the needs of both the resource provider and the resource consumer must be considered. The approach specified in this standard is to provide a modular framework of API components. This framework provides a consistent "look and feel" across all OGC APIs. When API servers and clients are built from the same set of modules, the likelihood that they will integrate at run-time is greatly enhanced.

A more detailed discussion of modular APIs can be found in the API-Common link:https://github.com/opengeospatial/oapi_common/blob/master/20-071.html#modular-api[Best Practices] document.

[[hypermedia-access-introduction]]
=== Hypermedia Access

Hypermedia Access is the use of hypermedia links to navigate from one resource to another. This pattern is typical of the Web Browser environment. A resource consumer starts from a landing page, selects a link on that page and then moves on to the referenced resource.

Navigation of hyperlinks is facilitated if the hyperlink includes information about the resource type at the link destination. Therefore, OGC APIs use a set of common link relationships. The link relationships used in API-Common Core are described in <<link-relations-table>>.

[#link-relations-table,reftext='{table-caption} {counter:table-num}']
.Link Relations
[width="90%",cols="2,6",options="header"]
|===
^|**Link Relation** ^|**Purpose**
|`alternate` |Refers to a substitute for this context [IANA]. + 
Refers to a representation of the current resource which is encoded using another media type (the media type is specified in the `type` link attribute).
|`collection`|The target IRI points to a resource which represents the collection resource for the context IRI. [IANA]
|`current` |Refers to a resource containing the most recent item(s) in a collection of resources. [IANA]
|`conformance`|Refers to a resource that identifies the specifications that the link's context conforms to. [OGC]
|`data`|Refers to the root resource of a dataset in an API. [OGC]
|`describedby`|Refers to a resource providing information about the link's context.[IANA] +
Links to external resources which further describe the subject resource
|`first`|An IRI that refers to the furthest preceding resource in a series of resources.[IANA]
|`item`|The target IRI points to a resource that is a member of the collection represented by the context IRI.[IANA]
|`items` |Refers to a resource that is comprised of members of the collection represented by the link's context. [OGC]
|`last`|An IRI that refers to the furthest following resource in a series of resources.
|`license`|Refers to a license associated with this context. [IANA]
|`next`|Indicates that the link's context is a part of a series, and that the next in the series is the link target. [IANA]
|`prev`|Indicates that the link's context is a part of a series, and that the previous in the series is the link target. [IANA]
|`self`|Conveys an identifier for the link's context. [IANA] +
A link to another representation of this resource.
|`service-desc`|Identifies service description for the context that is primarily intended for consumption by machines. [IANA] +
API definitions are considered service descriptions.
|`service-doc`|Identifies service documentation for the context that is primarily intended for human consumption. [IANA]
|`start`|Refers to the first resource in a collection of resources.[IANA]
|===

OGC API hyperlinks are defined using the following link:https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/link.json[Hyperlink Schema].

[source, JSON]
include::openapi/schemas/link.json[]
