== Introduction

[big]*i.     Abstract*

The OGC has extended their suite of standards to include Resource Oriented Architectures and Web APIs. In the course of developing these standards, some practices proved to be common across more than one of those standards. These common practices are documented in the OGC API - Common suite of standards. API-Common standards serve as reusable building-blocks. Developers of OGC standards will use these building-blocks in the construction of OGC Web API Standards. The result is a modular suite of coherent API standards which can be adapted by a system designer for the unique requirements of their system.

The OGC API - Common - Part 1: Core Standard defines the resources and access mechanisms which are useful for a client seeking to understand the offerings and capabilities of an API. These resources and their access mechanisms are described in <<cr-table>>. 

[#cr-table,reftext='{table-caption} {counter:table-num}']
.Common Core Resources
[cols="32,23,15,30",options="header"]
!===
^|Resource ^|URI ^|HTTP Method ^|Document Reference
|Landing page |`/` ^|GET |<<landing-page,API Landing Page>>
|API definition |`/api` ^|GET |<<api-definition,API Definition>>
|Conformance declaration |`/conformance` ^|GET |<<conformance-classes,Declaration of Conformance Classes>>
!===

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, geographic information, spatial data, API, json, html, OpenAPI, REST, Common

[big]*iii.   Preface*

*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* Ecere Corporation
* Heazeltech LLC
* Hexagon
* Interactive Instruments GmbH
* U.K. Met Office
* Universitat Autònoma de Barcelona (CREAF)
* U.S. Army Geospatial Center
* U.S. Geological Survey
* U.S. National Aeronautics and Space Administration (NASA)
* U.S. National Geospatial-Intelligence Agency

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*
|Charles Heazel _(editor)_ |Heazeltech
|David Blodgett |U.S. Geological Survey
|Clemens Portele |Interactive Instruments
|Sylvester Hagler |U.S. National Geospatial-Intelligence Agency
|Jeffrey Harrison |U.S. Army Geospatial Center
|Frédéric Houbie |Hexagon
|Jérôme Jacovella-St-Louis |Ecere Corporation
|Chris Little | U.K. Met Office
|Joan  Masó |UAB-CREAF
|Donald Sullivan |NASA
|===
