[[general-requirements-section]]
=== General Requirements

The following requirements and recommentations are applicable to all OGC Web APIs.

==== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/general/REQ_http.adoc[]

[[http-status-codes]]
==== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`302` |The target resource was found but resides temporarily under a different URI. A 302 response is not evidence that the operation has been successfully completed.
|`303` |The server is redirecting the user agent to a different resource. A 303 response is not evidence that the operation has been successfully completed.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not changed since the previous request.
|`307` |The target resource resides temporarily under a different URI and the user agent MUST NOT change the request method if it performs an automatic redirection to that URI.
|`308` |Indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/general/PER_additional-status-codes.adoc[]

[[query-parameter-requirements]]
==== Query parameters

Validation of query parameters in the request URL is complicated. Ideally, the parameter names and valid values would be completely defined in the API definition. However, there are a number of reasons why this may not be possible.

OGC Web API standards do not mandate a language nor data model for the API defintion. While OpenAPI does support this level of detail, other API description languages may not. Therefore, an API standard cannot assume the presence of a capabilty which iteself is not required.

Provision of this level of detail may result in an API which is difficult to use or maintain. Consider an API which allows queries against resource properties. A full specification of the query parameters would list all possible combinations of Feature Type and Property as well as the valid values for each. If the hosted content is subject to change, then each change would have to be reflected in the API definition. Implementors are unlikely to invest the resource needed to provide and maintain this level of detail. Likewise, client implementors would be reluctant to parse and extract this information. The increased complexity does not provide a comprable value to implementors or users.

A requirement for complete documentation of all query parameters would limit the abilty of a server to implement soft failures. For example, an API server may be able to identify and correct simple errors such as misspellings and capitalization. An OGC Web API standard should not preclude provision of this capabilty.

To accomodate this variety, the requirements for query parameter validation are defined around three casses:

* CASE A: The query parameter is fully described in the API definition
* CASE B: The query parameter is partially described in the API documentation
* CASE C: The server is able to detect and correct errors in the query parameter

*CASE A:*

include::requirements/general/REQ_query-param-known.adoc[]

This is the ideal case. The query parameter is fully defined in the API definition and the query parameter in the request URL matches that definition.

*CASE B:*

include::requirements/general/REQ_query-param-implied.adoc[]

This is the case where the definition of a query parameter provides some lattitude. For example, if the API server allows querying on resource properties. In that case, the parameter definition may be a bounded range of possible values. However, all possible values may not be valid at any one time. If the query parameter name matches one of the properties currently hosted, then the request can proceed.  

*CASE C:*

include::requirements/general/REQ_query-param-corrected.adoc[]

An API implementation may choose to be forgiving of minor errors in the query parameters. The goal here is not to ignore the errors, but the inform the client of the error and instruct them on how to fix it.

Status codes 307 and 307 are specified for this purpose. Both refer the client to a new (corrected) URI for the resource. 

Status code 308 indicates that the new URI is a permanent change. This is the most relevant response since the original URI will never be valid. However, Status Code 308 is defined in a separate RFC from the rest of the HTTP suite and may not be implemented by the client. Status Code 307 indicates that the new URI is a temporary change. While this staus is somewhat misleading, this code is incorporated in the main body of HTTP standards. So it is more likely to be implemented by a client.

It is imperative that the redirect URI is correct. For that reason, subrequirements B and C assure that a redirect URI is not returned until ALL errors have been resolved.

include::requirements/general/REQ_query-param-unknown.adoc[]

If the query parameter cannot be validated or corrected, then tell the client.  

[[web-caching-section]]
==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc7232,HTTP/1.1 (RFC 7232)>>.

include::recommendations/general/REC_etag.adoc[]

[[cross-origin-section]]
==== Support for Cross-Origin Requests

If the data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/general/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[resource-encoding-section]]
==== Resource Encodings

A Web API provides access to <<resource-definition,resources>> through <<representation-definition,representations>> of those resources. One property of a representation is the format used to encode it for transfer. Components negotiate which encoding format to use through the content negotiation process defined in <<rfc7231,IETF RFC 7231>>.

Additional content negotiation techniques are allowed, but support is not required of implementations conformant to this Standard.

While this standard does not specify any mandatory encoding, the following encodings are recommended:

[[rec_html]]
HTML encoding recommendation:
include::recommendations/general/REC_html.adoc[]

[[rec_json]]
JSON encoding recommndation:
include::recommendations/general/REC_json.adoc[]

[[parameter-encoding-section]]
==== Parameter Encoding

The following sections provide the requirements and guidelines for encoding parameters for use in an OGC Web API request. 

OGC Web API requests are issued using a Uniform Resource Identifier (URI). The URI syntax is defined in <<rfc3986,IETF RFC 3986>>. Rules for building URI Templates can be found in <<rfc6570,IETF RFC 6570>>. 

The Backus-Naur Form (BNF) definition of a URI is provided in <<uri-bnf-annex,Annex F>>. 

===== Capitalization

<<rfc3986,IETF RFC 3986>> sections 6.2.2.1 and 2.1 provide the requirements for capitalization in URIs.

include::requirements/general/REQ_query-param-capitalization.adoc[]

All parameter value strings should have the first word and any subsequent words in the name capitalized. All other letters should be lower case.

However, a Web API may allow filtering on properties of the target resource. In that case, the parameter name would be the name of the resource property. These names are defined by the standards and specifications defining the resource and cannot be constrained by this standard.

include::recommendations/general/REC_query-param-capitalization.adoc[]

===== Parameter Value Lists

Parameters may pass more than one value. The folowing requirements define how to encode a list of parameter values.

include::requirements/general/REQ_query-param-list-delimiter.adoc[]

include::requirements/general/REQ_query-param-list-escape.adoc[]

include::requirements/general/REQ_query-param-list-empty.adoc[]

Thus, two successive commas indicates an empty item, as does a leading comma or a trailing comma. An empty list ("") can either be interpreted as a list containing no items or as a list containing a single empty item, depending on the context.

===== Numeric and Boolean Values

Boolean values conform to the following requirement derived from <<ogc-06-121,OWS-Common>>.

include::requirements/general/REQ_query-param-value-boolean.adoc[]

Integer values conform to the following requirement derived from <<xmlschema-part2,XML Schema Part 2>>.

include::requirements/general/REQ_query-param-value-integer.adoc[]

Real numbers can be represented using either the decimal or double (exponential) format. The decimal format is typically used except for very large or small values.

Decimal values conform to the following requirement derived from <<xmlschema-part2,XML Schema Part 2>>. 

include::requirements/general/REQ_query-param-value-decimal.adoc[]

Double values conform to the following requirement derived from <<xmlschema-part2,XML Schema Part 2>>. 

include::requirements/general/REQ_query-param-value-double.adoc[]

Special values conform to the following requirement derived from <<xmlschema-part2,XML Schema Part 2>>. 

include::requirements/general/REQ_query-param-value-special.adoc[]

