[[req_landing-page_api-definition-op]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/landing-page/api-definition-op*
^|A |The server SHALL support the HTTP GET operation on all links from the landing page that have the relation type `service-desc`.
^|B |The server SHALL support the HTTP GET operation on all links from the landing page that have the relation type `service-doc`.
^|C |The responses to all HTTP GET requests issued in `A` and `B` SHALL satisfy requirement <<req_landing-page_api-definition-success,/req/landing-page/api-definition-success>>.
|===
////

[requirement]
====
[%metadata]
identifier:: /req/landing-page/api-definition-op
part:: The server SHALL support the HTTP GET operation on all links from the landing page that have the relation type `service-desc`.
part:: The server SHALL support the HTTP GET operation on all links from the landing page that have the relation type `service-doc`.
part:: The responses to all HTTP GET requests issued in `A` and `B` SHALL satisfy requirement <<req_landing-page_api-definition-success,/req/landing-page/api-definition-success>>.
====
