[[ats_html_definition]]

////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/html/definition*
^|Test Purpose |Verify support for HTML
^|Requirement |<<req_html_definition,/req/html/definition>> +
<<req_html_content,/req/html/content>>
^|Test Method |DO FOR EACH resource and operation defined in the Landing Page Conformance Class:

. Execute the operation specifing `text/html` as the media type
. Validate that a document was returned with a status code `200`
. Validate the contents of the returned document using test <<ats_html_content,/conf/html/content>>.

DONE
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/html/definition
subject:: <<req_html_definition,/req/html/definition>> +
<<req_html_content,/req/html/content>>
test-purpose:: Verify support for HTML
test-method::
+
--
DO FOR EACH resource and operation defined in the Landing Page Conformance Class:

. Execute the operation specifying `text/html` as the media type
. Validate that a document was returned with a status code `200`
. Validate the contents of the returned document using test <<ats_html_content,/conf/html/content>>.

DONE
--
====
