[[per_core-query-param-name-tolerance]]
////
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/core/query-param-name-tolerance*
^|A |Servers MAY display tolerance for requests with incorrect query parameter names. These acts of tolerance include:

*   Accept alternate capitalizations, spellings, and/or aliases of parameters,
*   Ignore unknown/unrecognized parameters,
*   Return a response with a status code of 30x redirecting the client to a more correct version of the request.
^|B |Servers should not be excessively tolerant. The response a client receives from the server should be a reasonable response for the request submitted.
|===
////

[recommendation]
====
[%metadata]
identifier:: /per/core/query-param-name-tolerance
part::
Servers MAY display tolerance for requests with incorrect query parameter names. These acts of tolerance include:

*   Accept alternate capitalizations, spellings, and/or aliases of parameters,
*   Ignore unknown/unrecognized parameters,
*   Return a response with a status code of 30x redirecting the client to a more correct version of the request.
part:: Servers should not be excessively tolerant. The response a client receives from the server should be a reasonable response for the request submitted.
====
