[[req_collections_rc-bbox-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections/rc-bbox-definition* 
^|A|The bounding box is provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth):

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Minimum value, coordinate axis 3 (optional)
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2
* Maximum value, coordinate axis 3 (optional)

^|B|The values for the CRS axis 1 and 2 SHALL be interpreted as WGS84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a  different coordinate reference system is specified in a parameter `bbox-crs`.
^|C|The coordinate values SHALL be within the extent specified for the coordinate reference system.
^|D|The `bbox` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment):

[source,YAML]
----
name: bbox
in: query
required: false
schema:
  type: array
  minItems: 4
  maxItems: 6
  items:
    type: number
style: form
explode: false
----

|===
