[[req_extent-uad-definition]]
[requirement]
====
[%metadata]
identifier:: /req/umd-collection/extent-uad-definition
part:: Any additional dimension property added to the `extent` of a collection description SHALL contain an `interval` property consisting of an array of one or more interval, where the first element describes the overall interval where data is available for the collection, whereas any additional elements describe intervals encompassing clusters of data availability within the overall interval.
part:: Each interval element SHALL be described as an array of two values, with the first being the lower bound and the second the upper bound.
part:: An unbounded or half-bounded interval SHALL be described using a null value for its lower and/or upper bound.
part:: Any additional dimension SHALL contain a `definition` property to indicate the semantic concept for the variable associated with the dimension, a `trs` to indicate a temporal reference system or a `vrs` property to indicate the vertical reference system.
part:: For additional dimension defined using `definition`, where a particular unit is used, that dimension SHALL contain a `unit` property expressing the unit of measure, where the language for defining the unit is UCUM, unless specified otherwise in a `unitLang` property (using values such as `"UCUM"` or `"QUDT"`).
====
