[[req_grid_description]]
[requirement]
====
[%metadata]
identifier:: /req/umd-collection/grid-description
part:: If data is organized as a regular or irregular grid for the temporal and any additional dimension, that dimension SHALL contain a `grid` object property describing the grid of that dimension.
part:: If data is organized as a regular or irregular grid for the spatial dimensions, the `spatial` object SHALL contain a `grid` array property, where each element is an object describing the grid of that dimension.
part::
+
--
If data is organized as a regular or irregular grid for a dimension, the grid object(s) for that dimension SHALL indicate the number of coordinates along the dimension in a `cellsCount` property. +

* For values representing the whole area of contiguous cells spanning _resolution_ units along the dimension, the _cellsCount_ will be (_upperBound_ - _lowerBound_) / _resolution_. +
* For values representing infinitely small point cells spaced by _resolution_ units along the dimension, the _cellsCount_ will be (_upperBound_ - _lowerBound_) / _resolution_ + 1.
--
part:: For regularly gridded dimensions, the grid object SHALL contain a `resolution` property indicating the resolution of the grid in the unit of the `unit` property or the unit associated with the `trs`, `vrs`, or `storageCrs` in the case of the spatial dimensions (defaulting to [OGC:CRS84] if none is provided). +
The regular grid can be generated by incrementally adding the resolution starting from the lower bound of the overall interval.
part:: For irregularly gridded (or categorical) dimensions, the grid object SHALL contain a `coordinates` property indicating the list of valid coordinates where data is available along that dimension.
====
