[[ats_collections]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections
target:: https://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections
classification:: Target Type:Web API

abstract-test:: /conf/collections/collections-list-op
abstract-test:: /conf/collections/collections-list-success
abstract-test:: /conf/collections/collections-list-links
abstract-test:: /conf/collections/collections-list-collections
abstract-test:: /conf/collections/description-op
abstract-test:: /conf/collections/description-success
abstract-test:: /conf/collections/description-links
abstract-test:: /conf/collections/description-extent
abstract-test:: /conf/collections/description-extent-multi
====

The <<rc_collections,Collections>> Conformance Class has a dependency on OGC API - Common - Part 1: Core's "Core" conformance class, implying a dependency on HTTP and optionally HTTPS protocols:

https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core

Conformance with the <<rc_collections,Collections>> Conformance Class is demonstrated by execution, in order, of all abstract tests it consists of:

==== List of Collections (`/collections`) Tests

include::collections/ATS_collections-list-op.adoc[]

include::collections/ATS_collections-list-success.adoc[]

include::collections/ATS_collections-list-links.adoc[]

include::collections/ATS_collections-list-collections.adoc[]

==== Collection Description (`/collections/{collectionId}`) Tests

include::collections/ATS_description-op.adoc[]

include::collections/ATS_description-success.adoc[]

include::collections/ATS_description-links.adoc[]

include::collections/ATS_description-extent.adoc[]

include::collections/ATS_description-extent-multi.adoc[]
