[[ats_landing-page_root-success]]

////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/landing-page/root-success*
^|Test Purpose |Validate that the landing page complies with the required structure and contents.
^|Requirement |<<req_landing-page_root-success,/req/landing-page/root-success>>
^|Test Method |Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>

For formats that require manual inspection, perform the following:

. Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition

. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/landing-page/root-success
subject:: <<req_landing-page_root-success,/req/landing-page/root-success>>
test-purpose:: Validate that the landing page complies with the required structure and contents.
test-method::
+
--
Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>

For formats that require manual inspection, perform the following:

. Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition

. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration
--
====

The landing page may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the landing page against that schema. All supported formats should be exercised.

[#landing-page-schema,reftext='{table-caption} {counter:table-num}']
.Schema and Tests for Landing Pages
[width="90%",cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |link:http://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/landingPage.yaml[landingPage.yaml]|<<ats_html_content,/conf/html/content>>
|JSON |link:http://schemas.opengis.net/ogcapi/common/part1/1.0/openapi/schemas/landingPage.yaml[landingPage.yaml] |<<ats_json_content,/conf/json/content>>
|===
