== Introduction

[big]*i.     Abstract*

The OGC has extended their suite of standards to include Resource Oriented Architectures and Web APIs. In the course of developing these standards, some practices proved to be common accross all OGC API standards. The purpose of this standard is to document those practices. It also serves as a common foundation upon which all OGC APIs will be built. As such, this OGC API Common standard serves as the "OWS Common" standard for OGC Resource Oriented APIs.

Consistent with the architecture of the Web, this specification uses a resource architecture and specifies a RESTful service interface consistent with the IETF HTTP/HTTPS RFCs.

This standard defines the resources listed in Table 1. These resources are common for all OGC APIs. For an overview of these resources, see section <<core-overview,7.1 Overview>>.

[#tldnr,reftext='{table-caption} {counter:table-num}']
.Overview of Resources
[cols="32,23,15,30",options="header"]
!===
^|Resource ^|Path ^|HTTP Method ^|Document Reference
|Landing page |`/` ^|GET |<<_api_landing_page,7.2 API landing page>>
|API definition |`/api` ^|GET |<<_api_definition_2,7.3 API definition>>
|Conformance classes |`/conformance` ^|GET |<<_declaration_of_conformance_classes,7.4 Declaration of conformance classes>>
|Collections metadata |`/collections` ^|GET |<<_collections_metadata,7.11 collections metadata>>
!===

The resources identified in Table 1 primarily support Discovery operations. Discovery operations allow clients the interrogate the API to determine its capabilities and retrieve information (metadata) about this distribution of the resource. This includes the API definition of the server(s) as well as metadata about the resources provided by those servers.

This standard also defines common Query operations for OGC APIs. Query operations allow resources or values extracted from those resources to be retrieved from the underlying data store. The information to be returned is based upon selection criteria (query string) provided by the client. This standard only defines simple query parameters which should be applicable to all resource types. Other OGC API standards may define additional query capabilities specific to their resource type. 

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, property, geographic information, spatial data, spatial things, dataset, distribution, API, geojson, html, OpenAPI, AsyncAPI, REST, Common

[big]*iii.   Preface*

*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.

[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* Heazeltech LLC
* others TBD

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*
|Chuck Heazel _(editor)_ |Heazeltech
|others |TBD
|===

