== Requirement Class "Core"
:sectnums:

include::requirements/requirements_class_core.adoc[]

[[core-overview]]
=== Overview

[[resources-introduction]]
==== Resources

An OGC API provides a lighweight interface to access one or more resources. The resources addressed by OGC APIs fall into three categories; Foundation Resources, Geospatial Resources, and Information Resources.

Foundation Resources are those resources which are common across all OGC APIs. Those resources are defined in this OGC API-Common standard. Other OGC API standards re-use these resources and, where necessary, extend them to address unique requirements.

Geospatial Resources are the resource which we usually think of as Geospatial Data. They include Features, Coverages, Maps, and Styles. This Standard defines basic patterns for accessing Geospatial Resources. Additional OGC API Standards have been developed to address specific API requirements for each Geospatial Resource type.

Information Resources are non-geospatial resources which support the operation of the API or the access and use of the Geospatial Resources. 

[[modular-API-introduction]]
==== Modular APIs

A goal of OGC API standards is to provide rapid and easy access to geospatial resources. To meet this goal, the needs of both the resource provider and the resource consumer must be considered. Our approach is to provide a modular framework of API components. This framework provides a consistent "look and feel" across all OGC APIs. When API servers and clients are built from the same set of modules, the likelyhood that they will integrate at run-time is greatly enhanced.

[[navigation-introduction]]
==== Navigation

OGC APIs are designed to support two access patterns; Hypermedia Access, and Direct Access. OGC APIs support both access patterns through the use of API Definition documents, standardized paths, and standardized hypermedia schemas. 

[[hypermedia-access-introduction]]
===== Hypermedia Access

Hypermedia Access is the use of hypermedia links to navigate from one resource to another. This pattern is typical of the Web Browser environment. A resource consumer (typically a human) starts from a landing page, selects a link on that page, then moves on to the referenced resource.

Navigation of hyperlinks is facilitated if the hyperlink includes information about the resource type at the link destination. Therefore, OGC APIs will use a set of common link relationships.

include::requirements/core/REQ_link-relations.adoc[]

OGC API hyperlinks are defined using the following link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/openapi/schemas/link.json[Hyperlink Schema].

.Hyperlink Schema
[source, JSON]
include::openapi/schemas/link.json[]

[[direct-access-introduction]]
===== Direct Access

Direct Access requires that the resource consumer possesses knowlege of the path to the resouce prior to attempting access. Typically this knowlege comes from the use of standard paths, receiving the path from another entity, or by processing an API definition resource. Direct access is particularly applicable to software analytics where there is no human in the loop.

Direct access is facilitated by the use of standard URL paths.

====== Foundation Resources

The standard paths defined in this Standard for Foundation Resources are:

. "/" - the landing page
. "/api" - the API Definition document for this API
. "/conformance" - the conformance information for this API

include::recommendations/core/REC_path-conventions.adoc[]

====== Geospatial Resources

Geospatial Resources can be exposed using the path template.

 /collections/{collectionId}/items
       where
 {collectionId} = a unique identifier for a resource collection (dataset)

[#path_behaviors,reftext='{table-caption} {counter:table-num}']
.Path Behaviors
[width="90%",cols="2,4",options="header"]
|===
^|**Path** ^|**Returns**
|"/collections" |Metadata describing the collections avalable from this API.
|"/collections/{collectionId} |Metadata describing the collection with the unique identifier {collectionId}
|"/collections/{collectionId}/items" |The collection identified by the {collectionId} parameter.
|===

====== Information Resources

Information Resources can exposed using two path templates:

* /collections/{collectionId}/{resourceType}
* /{resourceType}

Where 

{collectionId} = a unique identifier for a Geospatial Resource collection.

{resourceType} = a text string identifying the Information Resource type.

Information Resources associated with a specific collection should be accessed through the `/collections` path. Those which are not associated with a specific collection should use the `/{resourceType}` template.

The OGC API Information Resource types and their corresponding API standard are provided in <<information_resources>>

[#information_resources,reftext='{table-caption} {counter:table-num}']
.Information Resource Types
[width="90%",cols="2,4",options="header"]
|===
^|**Resource Type** ^|**API Standard**
|TBD |TBD
|===

[[foundation-resources]]
=== Foundation Resources

Foundation resources are those resources which are provided by every OGC API.

[[landing-page]]
==== API landing page

Each OGC API has a single `LandingPage` (path `/`).

The purpose of the landing page is to provide users with the basic information they need to use this API as well as links to the resources exposed through the API.

===== Operation

include::requirements/core/REQ_root-op.adoc[]

===== Response

include::requirements/core/REQ_root-success.adoc[]

In addition to the required resources, links to additional resources may be included in the Landing Page.

include::recommendations/core/PER_lp-links.adoc[]

The landing page returned by this operation is based on the following link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/openapi/schemas/landingPage.json[Landing Page Schema]. Examples of OGC landing pages are provided in <<landing-page-examples>>.

.Landing Page Schema
[source, JSON]
include::openapi/schemas/landingPage.json[]

===== Error Situations

See <<http_status_codes>> for general guidance.

[[API-definition]]
==== API Definition

Every API is expected to provide a definition that describes capabilities provided by the API. This document can be used by developers to understand the API, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

===== Operation

include::requirements/core/REQ_api-definition-op.adoc[]

===== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recommendations/core/REC_api-definition-oas.adoc[]

If multiple API definition formats are supported, use content negotiation to select the desired representation.

===== Error Situations

See <<http_status_codes>> for general guidance.

[[conformance-classes]]
==== Declaration of Conformance Classes

To support "generic" clients that want to accessing OGC APIs in general - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

===== Operation

include::requirements/core/REQ_conformance-op.adoc[]

===== Response

include::requirements/core/REQ_conformance-success.adoc[]

The conformance resource returned by this operation is based on the following link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/core/openapi/schemas/confClasses.json[Conformance Schema]. Examples of OGC conformance resources are provided in <<conformance-response-examples>>.

.Conformance Schema
[source, JSON]
include::openapi/schemas/confClasses.json[]

===== Error situations

See <<http_status_codes>> for general guidance.

[[geospatial-resources]]
=== Geospatial Resources

Geospatial Resources are the resource types which we usually think of as Geospatial Data. They include Features, Coverages, Maps, and Styles. 

Detailed requirements for each Geospatial Resource type are dealt with in the resource-specific API standards. However, this API Common standard has the responsiblity to see that they all OGC API standards work together by: 

. Providing specifications for the description of each collection (/collections/{collectionId}), and the list of collections (/collections)
. Providing a consistent framework for serving geospatial data from the OGC API, regardless of the type. Consistent means that #1 works exactly the same (potentially with type-specific additional properties) and that the different types of data can all be collections on the same OGC API end-point.
. Providing a tie point for other OGC API modules to connect to and reference (processes inputs & outputs, cataloging, searching and filtering collections, detailed metadata, tiles, styles, clipping and intersecting bounding boxes in common) Just by virtue of understanding that /collections/{collectionId} points to a geospatial(--dataset--) **data layer**.

[[collections-metadata]]
==== Collections Metadata

OGC APIs typically organize their Geospatial Resources into collections. These collections are accessed through the /collections path.

===== Operation

include::requirements/core/REQ_rc-md-op.adoc[]

===== Response

include::requirements/core/REQ_rc-md-success.adoc[]

The collections metadata returned by this operation is based on the link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/core/openapi/schemas/collections.yaml[Collections Metadata Schema]. Examples of collections metadata are provided in <<collections-metadata-examples>>.

.Collections Metadata Schema
[source, JSON]
include::openapi/schemas/collections.json[]

This schema is further constrained by the following requirements and recomendations.

include::requirements/core/REQ_rc-md-links.adoc[]

include::recommendations/core/REC_rc-md-descriptions.adoc[]

Examples for descriptions are: XML Schema, Schematron, JSON Schema, RDF Schema, OWL, SHACL, a feature catalogue, etc.

The `collections` property of the Collections Metadata is based on the schema described in <<collection-information>>. The follwing requirements and recommendations govern the use of Collection Information in the Collections Metadata.

include::requirements/core/REQ_rc-md-items.adoc[]

include::recommendations/core/PER_rc-md-items.adoc[]

include::requirements/core/REQ_rc-md-items-links.adoc[]

===== Error situations

See <<http_status_codes>> for general guidance.

[[collection-information]]
==== Collection Information

Each resource collection is described by a set of metadata. That metadata is accessed directly using the `/collections/{collectionId}` path or as an entry in the `collections` property of the Collections Metadata resource.

===== Operation

include::requirements/core/REQ_src-md-op.adoc[]

===== Response

include::requirements/core/REQ_src-md-success.adoc[]

Collection Information is based on the link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/core/openapi/schemas/collectionInfo.yaml[Collection Information Schema] Schema.

.Collection Information Schema
[source, JSON]
include::openapi/schemas/collectionInfo.json[]

Additional requirements and recomendations apply to the `extent` propery of the Collection Information.

include::requirements/core/REQ_rc-md-extent.adoc[]

include::recommendations/core/REC_rc-md-extent-single.adoc[]

include::recommendations/core/PER_rc-md-extent-extensions.adoc[]

===== Error situations

See <<http_status_codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status_codes>>).

[[collection-resource]]
==== Collection Resource

A collection resource is the content of the collection as opposed to metadata about that collection. This standard defines the general behavior of this operation, but detailed requirements are the purvue of the API standard for that resource type.

===== Operation

include::requirements/core/REQ_rc-op.adoc[]

===== Response

include::requirements/core/REQ_rc-response.adoc[]

===== Error situations

See <<http_status_codes>> for general guidance.

[[information-resources]]
=== Information Resources

Information Resources are non-geospatial resources which support the operation of the API or the access and use of the Geospatial Resources. These resources are usually specific to a geospatial resource type and will be defined in the appropriate API standards. 

=== Parameter Modules

Query parameters are used in URLs to limit the resources which are returned on a GET request. The API Common standard defines two standard parameters for use in OGC API standards.

==== Parameter bbox

include::requirements/core/REQ_rc-bbox-definition.adoc[]

include::requirements/core/REQ_rc-bbox-response.adoc[]

"Intersects" means that the rectangular area specified in the parameter `bbox` includes a coordinate that is part of the (spatial) geometry of the resource. This includes the boundaries of the geometries (e.g. for curves the start and end position and for surfaces the outer and inner rings).

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a latter version of this specification.

For WGS84 longitude/latitude the bounding box is in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the  box spans the anti-meridian the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/core/openapi/parameters/bbox.yaml[bbox.yaml].

==== Parameter datetime

include::requirements/core/REQ_rc-time-definition.adoc[]

include::requirements/core/REQ_rc-time-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.
 
.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`time=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate` in the building features), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/OAPI_Common/master/core/openapi/parameters/datetime.yaml[datetime.yaml].

[[general-requirements]]
=== General Requirements

The following general requirements and recomendations apply to all OGC APIs.

==== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/core/REQ_http.adoc[]

[[http_status_codes]]
==== HTTP Status Codes

<<status_codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`304` |An <<web_caching,entity tag was provided in the request>> and the resource has not been changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorised to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |The `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/core/PER_additional-status-codes.adoc[]

[[web_caching]]
==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc2616,HTTP/1.1 (RFC 2616)>>.

include::recommendations/core/REC_etag.adoc[]

[[cross_origin]]
==== Support for Cross-Origin Requests

Access to data from a HTML page is by default prohibited for security reasons, if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

==== Encodings

While the OAPI Common standard does not specify any mandatory encoding, the following encodings are recommended. See <<overview,Clause 6 (Overview)>> for a discussion.

include::recommendations/core/REC_html.adoc[]

include::recommendations/core/REC_geojson.adoc[]

<<_http_1_1,Requirement `/req/core/http`>> implies that the encoding of a response is determined using content negotiation as specified by the HTTP RFC.

The section <<mediatypes,Media Types>> includes guidance on media types for <<encodings,encodings>> that are specified in this document.

Note that any API that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the API.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") in the browser address bar, can study the API definition.

[NOTE]
=========================================================
Two common approaches are:

* an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");
* an additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.
=========================================================

==== Link Headers

include::recommendations/core/REC_link-header.adoc[]

==== Coordinate Reference Systems

As discussed in Chapter 9 of the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practices document>>, how to express and share the location of resources in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, OGC APIs use WGS84 longitude and latitude as the default coordinate reference system.

include::requirements/core/REQ_crs84.adoc[]

The implementations compliant with the Core are not required to support publishing geometries in coordinate reference systems other than http://www.opengis.net/def/crs/OGC/1.3/CRS84. The Core also does not specify a capability to request geometries in a different reference system than the native one of the published resource. Such a capability will be specified in other OGC API standards.



