== Conformance
This standard defines four requirements / conformance classes.

The standardization target of all conformance classes is "Web APIs".

The main requirements class is:

* <<rc_core,Core>>.

The _Core_ specifies requirements that all OGC APIs must implement.

The _Core_ does not mandate a specific encoding or format for representing resources. Two requirements classes depend on the _Core_ and specify representations for these resources in commonly used encodings for spatial data on the web:

* <<rc_html,HTML>>,
* <<rc_geojson,GeoJSON>>

None of these encodings are mandatory. An implementation of the _Core_ may decide to implement neither of them and to implement another encoding instead.

That said, the _Core_ requirements class includes recommendations to support where practical <<rec_html,HTML>> and <<rec_geojson,GeoJSON>> as encodings. <<overview,Clause 6 (Overview)>> includes a discussion about the recommended encodings.

The _Core_ does not mandate any encoding or format for the formal definition of the API either. The prefered option is the OpenAPI 3.0 specification. A requirements class has been specified for OpenAPI 3.0, which depends on the _Core_:

* <<rc_oas30,OpenAPI specification 3.0>>.

An implementation of the _Core_ requirements class may also decide to use other API definition representations in addition or instead of an OpenAPI 3.0 definition. Examples for alternative API definitions: OpenAPI 2.0 (Swagger), future versions of the OpenAPI specification, an OWS Common 2.0 capabilities document, or WSDL.

The _Core_ is intended to be the minimal useful service interface for fine-grained access to a spatial resource.

Additional capabilities such as support for transactions, complex data structures, rich queries, other coordinate reference systems, subscription/notification, returning aggregated results, etc., may be specified in future parts of OGC API Common, other OGC API standards, or as vendor-specific extensions.

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.
