[[req_collections_rc-time-collections-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections/rc-time-collections-response* 
^|A |If the `datetime` parameter is provided by the client and supported by the server, then only extents that have a temporal geometry that intersects the interval specified by the `datetime` parameter SHALL be part of the result set.
^|B |If an extent has multiple temporal geometries, the API implementor decides whether only a single temporal geometry is used to determine the extent or all relevant temporal geometry.
^|C |The ``datetime`` parameter SHALL match all collections which do not have an extent element with a temporal geometry.
^|D |Temporal geometries are either a date-time value or a time interval. The parameter value conforms to the following syntax (using link:https://tools.ietf.org/html/rfc2234[ABNF]):

[source,java]
----
interval-closed     = date-time "/" date-time
interval-open-start = "../" date-time
interval-open-end   = date-time "/.."
interval            = interval-closed / interval-open-start / interval-open-end
datetime            = date-time / interval
----
^|E |The syntax of `date-time` is specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6].
^|F |Open ranges in time intervals at the start or end are supported using a double-dot (`..`).
|===
