[[req_collections_description-extent-multi]]
[requirement]
====
[%metadata]
identifier:: /req/collections/description-extent-multi
part:: If the `extent` property includes a member `spatial`, all data in the collection SHALL be inside the extent described by the first bounding box in the `bbox` array.
part:: If the `extent` property includes a member `spatial` and the `bbox` array has more than one item, individual components (e.g., a feature or scene) of the collection SHALL be inside the extent described by one of the other bounding boxes in the `bbox` array.
part:: If the `extent` property includes a member `temporal`, all data in the collection SHALL be inside the extent described by the first time interval in the `interval` array.
part:: If the `extent` property includes a member `temporal` and the `interval` array has more than one item, individual components of the collection SHALL be inside the extent described by one of the other time intervals in the `interval` array.
====

NOTE: As a consequence, the first bounding box is a union of all subsequent bounding boxes, and the first temporal interval is a union of all subsequent temporal intervals.
