[[rc-hierarchical-collections]]
== Requirements Class "Hierarchical Collections"
:sectnums:

include::requirements/requirements_class_hierarchy.adoc[]

This "Hierarchical Collections" requirement class allows to organize a large number of collections according to a single pre-determined hierarchy.
This capability addresses two primary use cases:

- Drilling down through a very large number of collections in a tree-like manner, allowing clients to explore the entire hierarchy without first needing to retrieve the entire list of collections.
  The hierarchical organization also allows to present the list of collections in a hierarchical manner, for example using a tree view control, and makes it easier to discover or browse to a
  particular collection of interest using such an interface, with the ability to expand and collapse branches of the hierarchy.
  For example, data collections may be organized as a hierarchy of countries, states, and cities.
- Loading a limited subset of interest from the available collections.
  In conjunction with the "Searchable Collections" and/or "Filtering collections using CQL2" requirement classes, this parameter also allows to narrow down a search to a particular branch of the hierarchy.

NOTE: This requirement class does not address the use cases of defining simultaneous multiple hierarchies -- a collection can have a single `parent` collection.
Such multiple hierarchies capability could be defined independently (for example, the https://docs.ogc.org/per/18-045.html#hierarchical_paths_extension[`/themes` extension] proposed previously),
or the use case could be addressed through the `keywords` and/or `themes` core queryable properties defined by _OGC API - Records_ and applicable to the "Searchable Collections" requirement class.

All collections of the hierarchy, whether leaf colections, top-level collections, or anywhere in between, may or may not directly offer access to data using one or more access mechanisms
defined in one or more OGC API data access standards, such as _OGC API - Tiles_, _OGC API - Maps_, _OGC API - Features_ or _OGC API - Coverages_ (or others).
Those access mechanisms will be included as usual in `links` of the collections.

Conceptually, all data elements of the children collections are also considered to be data elements of their parent collections.
The practical meaning and implementation of this concept depends heavily on the access mechanisms available at each level of the collection hierarchy.

In the case where a parent collection offers a direct data access mechanism while also having children collections, the `collections=` query parameter might be applicable to some of these access mechanisms,
in a similar way to how `collections=` is applicable to data access mechanisms tied to the root of the API (see for example the "Collection Selection" requirement classes of _OGC API - Maps_ and _OGC API - Tiles_).

A client that is not aware of the capability defined in this requirement class can safely ignore it without any impact, and will simply treat the list of collections in the usual flat manner,
 as defined in the "Collections" requirement class.

=== `parent` property in collection description

A new `parent` property is defined to include in the collection description resources (`/collections/{collectionId}`)
and collection listing resource (`/collections`), indicating the `{collectionId}` of the parent for that collection.
The property is omitted or set to a _null_ value for top-level collections.

include::requirements/hierarchical-collections/REQ_parent_property.adoc[]

Although not required, implementations could opt for using a specific character (such as the colon `:`) to separate the hierarchical parts of collection identifiers.
This notably facilitates directly accessing a parent collection in a browser environment by editing URLs in the browser address bar.

CAUTION: Clients cannot rely on the use of any particular separator character to establish the hierarchical relationships between collections. Instead, they need to use the `parent` property specifying the identifier of the parent collection when applicable.

In the HTML representation of a collection description resource (`/collections/{collectionId}`), it can be useful to directly show the
list of children collections, allowing a user to directly click and explore the hierarchy this way.
For programmatic clients wishing not to retrieve an entire hierarchy of collections, separate `/collections?parent={parentId}&descendants=immediate` requests are performed to retrieve the list of immediate children collections (see below).

include::recommendations/hierarchical-collections/PER_collection_children.adoc[]

Example of a collection description response for `/collections/{collectionId}`:

```json
{
   "id": "Montreal",
   "parent": "Quebec",
   "links": [
      { "rel": "self", "/collections/Montreal" },
      { "rel": "items", "href": "/collections/Montreal/items" },
      { "rel": "[ogc-rel:map]", "href": "/collections/Montreal/map" },
      { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Montreal/tiles" }
   ],
   ...
}
```

Example of a hierarchical collection listing response for `/collections`:

```json
{
   "collections": [
      {
         "id": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Canada" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Canada/map" }
         ]
      },
      {
         "id": "USA",
         "links": [
            { "rel": "self", "href": "/collections/USA" },
            { "rel": "[ogc-rel:map]", "href": "/collections/USA/map" }
         ]
      },
      {
         "id": "Quebec", "parent": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Quebec" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Quebec/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Quebec/tiles" }
         ]
      },
      {
         "id": "Ontario", "parent": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Ontario" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Ontario/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Ontario/tiles" }
         ]
      },
      {
         "id": "NewYork", "parent": "USA",
         "links": [
            { "rel": "self", "href": "/collections/NewYork" },
            { "rel": "[ogc-rel:map]", "href": "/collections/NewYork/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/NewYork/tiles" }
         ]
      },
      {
         "id": "California", "parent": "USA",
         "links": [
            { "rel": "self", "href": "/collections/California" },
            { "rel": "[ogc-rel:map]", "href": "/collections/California/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/California/tiles" }
         ]
      },
      {
         "id": "QuebecCity", "parent": "Quebec",
         "links": [
            { "rel": "self", "href": "/collections/QuebecCity" },
            { "rel": "items", "href": "/collections/QuebecCity/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/QuebecCity/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/QuebecCity/tiles" }
         ]
      },
      {
         "id": "Montreal", "parent": "Quebec",
         "links": [
            { "rel": "self", "href": "/collections/Montreal" },
            { "rel": "items", "href": "/collections/Montreal/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Montreal/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Montreal/tiles" }
         ]
      },
      {
         "id": "Toronto", "parent": "Ontario",
         "links": [
            { "rel": "self", "href": "/collections/Toronto" },
            { "rel": "items", "href": "/collections/Toronto/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Toronto/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Toronto/tiles" }
         ]
      },
      {
         "id": "Ottawa", "parent": "Ontario",
         "links": [
            { "rel": "self", "href": "/collections/Ottawa" },
            { "rel": "items", "href": "/collections/Ottawa/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Ottawa/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Ottawa/tiles" }
         ]
      },
      {
         "id": "NewYorkCity", "parent": "NewYork",
         "links": [
            { "rel": "self", "href": "/collections/NewYorkCity" },
            { "rel": "items", "href": "/collections/NewYorkCity/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/NewYorkCity/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/NewYorkCity/tiles" }
         ]
      },
      {
         "id": "Syracuse", "parent": "NewYork",
         "links": [
            { "rel": "self", "href": "/collections/Syracuse" },
            { "rel": "items", "href": "/collections/Syracuse/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Syracuse/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Syracuse/tiles" }
         ]
      },
      {
         "id": "SanFrancisco", "parent": "California",
         "links": [
            { "rel": "self", "href": "/collections/SanFrancisco" },
            { "rel": "items", "href": "/collections/SanFrancisco/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/SanFrancisco/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/SanFrancisco/tiles" }
         ]
      },
      {
         "id": "SanDiego", "parent": "California",
         "links": [
            { "rel": "self", "href": "/collections/SanDiego" },
            { "rel": "items", "href": "/collections/SanDiego/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/SanDiego/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/SanDiego/tiles" }
         ]
      }
   ]
   ...
}
```

=== `parent` query parameter for `/collections`

A `parent` query parameter is defined to filter the list of collections returned to only those within the hierarchy of a specified parent collection.

Depending on the value of the `descendants` parameter, either the entire hierarchy underneath (`descendants=all`), or only the immediate children (`descendants=immediate`) of that parent are returned.
By default, all descendants of the specified parent, or all collections of the dataset if no parent is specified, are returned.

include::requirements/hierarchical-collections/REQ_parent_parameter.adoc[]

Example response, based on the hierarchical collections listed earlier, for `/collections?parent=Canada`:

```json
{
   "collections": [
      {
         "id": "Quebec", "parent": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Quebec" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Quebec/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Quebec/tiles" }
         ]
      },
      {
         "id": "Ontario", "parent": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Ontario" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Ontario/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Ontario/tiles" }
         ]
      },
      {
         "id": "QuebecCity", "parent": "Quebec",
         "links": [
            { "rel": "self", "href": "/collections/QuebecCity" },
            { "rel": "items", "href": "/collections/QuebecCity/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/QuebecCity/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/QuebecCity/tiles" }
         ]
      },
      {
         "id": "Montreal", "parent": "Quebec",
         "links": [
            { "rel": "self", "href": "/collections/Montreal" },
            { "rel": "items", "href": "/collections/Montreal/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Montreal/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Montreal/tiles" }
         ]
      },
      {
         "id": "Toronto", "parent": "Ontario",
         "links": [
            { "rel": "self", "href": "/collections/Toronto" },
            { "rel": "items", "href": "/collections/Toronto/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Toronto/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Toronto/tiles" }
         ]
      },
      {
         "id": "Ottawa", "parent": "Ontario",
         "links": [
            { "rel": "self", "href": "/collections/Ottawa" },
            { "rel": "items", "href": "/collections/Ottawa/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Ottawa/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Ottawa/tiles" }
         ]
      }
   ]
   ...
}
```


=== `descendants` query parameter for `/collections`

A `descendants` query parameter is also defined to retrieve only the immediate children of a specified parent, or only the top-level collections, when using the value `immediate`.
The default value `all` returns all collections as usual, or the whole hierarchy under a parent if `parent` is specified.

include::requirements/hierarchical-collections/REQ_descendants_parameter.adoc[]

Example response, based on the hierarchical collections listed earlier, retrieving only the top-level collections with `/collections?descendants=immediate`:

```json
{
   "collections": [
      {
         "id": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Canada" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Canada/map" }
         ]
      },
      {
         "id": "USA",
         "links": [
            { "rel": "self", "href": "/collections/USA" },
            { "rel": "[ogc-rel:map]", "href": "/collections/USA/map" }
         ]
      }
   ]
   ...
}
```

Example response, based on the hierarchical collections listed earlier, for retrieving only the immediate children of the `Canada` collection `/collections?parent=Canada&descendants=immediate`:

```json
{
   "collections": [
      {
         "id": "Quebec", "parent": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Quebec" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Quebec/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Quebec/tiles" }
         ]
      },
      {
         "id": "Ontario", "parent": "Canada",
         "links": [
            { "rel": "self", "href": "/collections/Ontario" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Ontario/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Ontario/tiles" }
         ]
      }
   ]
   ...
}
```

Example response, based on the hierarchical collections listed earlier, for retrieving only the immediate children of the `Quebec` collection `/collections?parent=Quebec&descendants=immediate`:

```json
{
   "collections": [
      {
         "id": "QuebecCity", "parent": "Quebec",
         "links": [
            { "rel": "self", "href": "/collections/QuebecCity" },
            { "rel": "items", "href": "/collections/QuebecCity/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/QuebecCity/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/QuebecCity/tiles" }
         ]
      },
      {
         "id": "Montreal", "parent": "Quebec",
         "links": [
            { "rel": "self", "href": "/collections/Montreal" },
            { "rel": "items", "href": "/collections/Montreal/items" },
            { "rel": "[ogc-rel:map]", "href": "/collections/Montreal/map" },
            { "rel": "[ogc-rel:tilesets-vector]", "href": "/collections/Montreal/tiles" }
         ]
      },
   ]
   ...
}
```

In order to allow implementations and deployments to present a list of collections in a hierarchical manner by default in a browser,
a permission specific to an HTML representation is introduced.
Since such an HTML representation is not primarily intended for consumption by programmatic clients, this should not impact compatibility with clients not implementing this extension.

include::recommendations/hierarchical-collections/PER_descendants_default_html.adoc[]


The following example query demonstrates combining filtering with a parent hierarchy (with default `descendants=all`) with capabilities defined in "Searchable Collections" to look for collections related to precipitations
in a hierarchy within the descendants of a collection with the identifier `Canada`:

```
GET /collections?parent=Canada&q=precipitations
```
