[[rc-sortable-collections]]
== Requirements Class "Sortable Collections"
:sectnums:

include::requirements/requirements_class_sorting.adoc[]

This Requirements Class describes query parameters that can be used to retrieve a list of collections exposed through an OGC Web API sorted in a specific order.

[[sorting-overview]]
=== Overview

This "Sortable Collections" defines the <<sorting-sortby-parameter,sortby>> query parameter which can be used with the `/collections` endpoint (described in the the https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section[Collections Requirements Class of OGC API - Common - Part 2: Geospatial Data])
to retrieve a list of collections returned by a GET request in a specific order.

If implementing https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1: Core] "Landing Page", these supported query parameters need to be described in the API definition as described in that part.

[[sorting-api-records]]
=== OGC API - Records compliance

This "Sortable Collections" requirement class is consistent with the requirements of https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-local-resources-catalog_filtering[OGC API - Records - Part 1: Core "Local Resources Catalog - Filtering" (Deployment)].
An implementation may gain additional interoperability by conforming to that requirement class from OGC API - Records as well.
In this case, in addition to the five OGC API - Records requirement classes mentioned in the <<collections-api-records,Collections requirements class>>, the implementation should verify and declare conformance with these additional two conformance classes defined in Records corresponding to the following URIs:

[cols="2,7",options="header"]
|===
| OGC API - Records Requirements Class | URI
| https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-sorting[Sorting]                                                           | https://www.opengis.net/spec/ogcapi-records-1/1.0/req/sorting
| https://docs.ogc.org/is/20-004r1/20-004r1.html#clause-local-resources-catalog_sorting[Local Resources Catalog - Sorting]         | https://www.opengis.net/spec/ogcapi-records-1/1.0/req/local-resources-catalog/sorting
|===

[[sorting-sortby-parameter]]
=== Query Parameter `sortby`

The Implementation needs to return a sortables schema from some end-point (e.g., `/collectionsSortables`) linked to using the
https://www.opengis.net/def/rel/ogc/1.0/sortables link relation from the `/collections` end-point. The client can discover the available sortables from the `properties` of that schema.

While this implies a first request to discover the sortables end-point,
the client could use `/collections?limit=1` if the Searchable Collections requirement class is also implemented to limit the size of that initial response.
The server is also allowed to limit the default or maximum number of collections returned in a single response.

include::requirements/sortable-collections/REQ_sortby-definition.adoc[]

include::requirements/sortable-collections/REQ_sortby-response.adoc[]
