[[conformance-section]]
== Conformance

Conformance with this Standard shall be checked using the tests specified in Annex A (normative) of this document.

The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the <<citepp,OGC Compliance Testing Policies and Procedures>> and the
https://www.ogc.org/compliance/[OGC Compliance Testing] web site.

The Standardization Target for this Standard is Web APIs.

OGC API - Common - Part 4: Discovery Within Many Collections defines API components intended for re-use by other OGC Web API standards.
For the purpose of conformance, the applicable API components are identified by Conformance Classes.

Typically, the OGC API - Common - Part 4: Discovery Within Many Collections will only be implemented through reference to these Conformance Classes by other standards.

OGC API - Common - Part 4: Discovery Within Many Collections identifies four conformance classes. Each conformance class is defined by one <<requirements-class-definition,requirements class>>.

The tests in Annex A are organized by Requirements Class. Therefore, an implementation of the _Collections_ conformance class must pass all tests specified in Annex A for the _Collections_ requirements class.

The requirements classes defined in Part 4: Discovery Within Many Collections are:

* <<rc-searchable-collections-section,Searchable Collections>>
* <<rc-sortable-collections-section,Sortable Collections>>
* <<rc-filterable-collections-section,Filterable Collections>>
* <<rc-hierarchical-collections-section,Hierarchichal Collections>>

Common API-4: Discovery Within Many Collections builds on API components defined in the https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 2: Geospatial Data] Standard.

Each <<requirements-class-definition,requirements class>> in the Common API-4: Discovery Standard depends on the https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section[Collections Requirements Class of CommonAPI-2: GeoData].

Proof of conformance with a Conformance Class includes demonstration of conformance with all dependencies of that Conformance Class.

The abstract tests in <<annex-ats,Annex A>> have been organized to facilitate validation of these dependencies.

These tests have been organized by <<requirements-class-definition,requirements class>>.

A referencing standard only has to require conformance with a Conformance Class and all of the requirements and relevant tests are identified.

In addition, each conformance class includes one or more test.

=== Summary of conformance URIs

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Corresponding requirements class                          | Conformance class URI
| <<rc_searchable-collections,Searchable Collections>>      | https://www.opengis.net/spec/ogcapi-common-4/1.0/conf/searchable-collections
| <<rc_sortable-collections,Sortable Collections>>          | https://www.opengis.net/spec/ogcapi-common-4/1.0/conf/sortable-collections
| <<rc_filterable-collections,Filterable Collections>>      | https://www.opengis.net/spec/ogcapi-common-4/1.0/conf/filterable-collections
| <<rc_hierarchical-collections,Hierarchical Collections>>  | https://www.opengis.net/spec/ogcapi-common-4/1.0/conf/hierarchical-collections
|===
