[[rc-subset-section]]
== Subset Requirements Class
:sectnums:

include::requirements/requirements_class_subset.adoc[]

NOTE: This Requirements Class under construction

This Requirements Class describes query parameters that can be used to discover and select resource collections exposed through an OGC Web API. 

[[subset-parameter-requirements]]
=== Parameter subset

Query parameters are used in URIs to limit the resources which are returned on a GET request. The <<rc-simple-query-section,Simple Query>> Requirements Class defines two parameters for selecting resources based on simple geospatial and temporal geometries. However, not all spatial-temporal resources are so well behaved. The Subset Requirements Class enables selection of resources based on a domain-specific n-dimensional geometry. 

include::requirements/REQ_subset-definition.adoc[]

include::requirements/REQ_subset-success.adoc[]

[[subset-target-resource]]
=== Target Resource

The target of the `subset` parameter is the <<collection-description,Collection>> resource described in the <<rc-collections-section,Collections>> Requirements Class. The purpose of this parameter is to select a subset of <<collection-description,Collection>> resources to be included in the response to a <<collections-metadata,/collections>> request.

The `collections` property of the Collections response provides a description of each individual collection hosted by the API. These descriptions are based on the link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/schemas/collectionDesc.json[Resource Collection Schema]. This schema is described in detail in the <<collection-description,Resource Collection>> section of this Standard. 

The requirements governing the processing of the `subset` parameter are:

include::requirements/REQ_rc-subset-collection-response.adoc[]

