=== What is a Collection

*<OGC API> Collection* +
A geospatial data resource that may be available as one or more sub-resource distributions that conform to one or more OGC API Standards.

==== Rationale

[[dataset-definition]]
*Dataset* +
collection of data

NOTE: Published or curated by a single agent, and available for access or download in one or more serializations or formats.

NOTE: This definition was adopted as the OGC definition of "dataset" by the OAB (see https://portal.ogc.org/?m=projects&a=view&project_id=228&tab=5&act=details&issue_id=1434[OAB issue 1434])

A dataset is a restriction on the general concept of a <<collection-definition,collection>>

. A dataset is a collection of data
. A dataset is published or curated by a single agent.
. A dataset is available in one or more serializations or formats (<<distribution-definition,distributions>>).
. A <<distribution-definition,distribution>> is synonymous to the REST concept of a <<representation-definition,representation>>.

*<OGC API> Collection (proposed)* +
A geospatial data resource that may be available as one or more sub-resource distributions that conform to one or more OGC API Standards.

An OGC API Collection is a restriction on the general concept of a <<collection-definition,collection>>:

. An OGC API Collection may only contain data. It does not encompass non-data <<definition-resource, resources>> (but the Collection resource may still have related auxiliary resources, such as schemas, or processes, as sub-resources).
. Geospatial datasets include <<spatial-thing-definition,Spatial Things>> and/or <<temporal-thing-definition,Temporal Things>> as data items (but not all data items in the dataset have to have a spatial or temporal extent).
. An OGC API Collection has one or more <<sub-resource-distribution-definition,sub-resource distributions>>.
. A <<distribution-definition,distribution>> provides access to a <<representation-definition,representation>> of a dataset.

*Conclusions*

. Any subset of a dataset can be an OGC API Collection.
. To generalize the OGC API Collection concept so that a dataset or dataset series could also be a OGC API Collection, a different definition without "sub-resource distribution" would be needed. Maybe change "as one or more sub-resource distributions" to "in one or more representations"?
. Such a change, however, would again require a mechanism to identify how datasets are related to the resources in a Web API that conforms to Common Part 2. How to identify that an OGC API Collection represents a dataset? How to identify that an API provides access to a single dataset?

==== Key Concepts

[[collection-definition]]
* *Collection* +
A body of resources that belong or are used together. An aggregate, set, or group of related resources. (Derived from Websters)

[[distribution-definition]]
* *Distribution* +
specific representation of a <<dataset-definition,dataset>>. (<<DCAT,DCAT>>) +
 +
EXAMPLE: a downloadable file, an RSS feed or an API.

[[sub-resource-distribution-definition]]
* *Sub-resource Distribution* +
a subset of the distribution of a dataset

[[feature-collection-definition]]
* *Feature Collection* +
a set of *Features* from a *dataset*

[[media-type-definition]]
* *Media Type* +
The data format of a <<representation-definition,representation>>. (Fielding 2000)

[[resource-definition]]
* *Resource* +
. Any information that can be named. (Fielding 2000)
. A conceptual mapping to a set of entities. (Fielding 2000)
. A resource R is a temporally varying membership function M~R~(t), which for time t maps to a set of entities, or values, which are equivalent. (Fielding 2000)

[[Representation-definition]]
* *Representation*
. A format matching one of an evolving set of standard data types, selected dynamically based on the capabilities or desires of the recipient and the nature of the resource. (Fielding 2000)
. The current or intended state of a resource. (Fielding 2000)

[[spatial-thing-definition]]
* *Spatial Thing* +
anything with spatial extent, (i.e. size, shape, or position) and is a combination of the real-world phenomenon and its abstraction. (<<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>>)

[[temporal-thing-definition]]
* *Temporal Thing* +
Anything with temporal extent, i.e. duration. e.g. the taking of a photograph, a scheduled meeting, a GPS time-stamped track-point. (<<W3C-BASIC-GEO,W3C Basic Geo>>)

==== OAPI Collections and OGC Resource Types

NOTE: Jeff's analysis goes here.
