[[identifiers]]
== Identifiers

The http://docs.opengeospatial.org/DRAFTS/19-072.html#WEBARCH[Architecture of the World Wide Web] establishes the URI as the single global identification system for the Web. Therefore, URIs or http://docs.opengeospatial.org/DRAFTS/19-072.html#rfc6570[URI Templates] are used in OGC Web API standards to identify key entities in those standards.

In accordance with OGC policy, only the http://docs.opengeospatial.org/DRAFTS/19-072.html#url-definition[Uniform Resource Locator (URL)] form of URIs is used.

The normative provisions in this draft standard are denoted by the URI ``http://www.opengis.net/spec/ogcapi-common-1/1.0[http://www.opengis.net/spec/ogcapi-common-1/1.0]``. All http://docs.opengeospatial.org/DRAFTS/19-072.html#requirement-definition[Requirements], http://docs.opengeospatial.org/DRAFTS/19-072.html#ctm-definition[Conformance Modules], and http://docs.opengeospatial.org/DRAFTS/19-072.html#ctc-definition[Conformance Classes] that appear in this document are denoted by partial URIs that are relative to this base.

http://docs.opengeospatial.org/DRAFTS/19-072.html#resource-definition[Resources] described in this document are denoted by partial URIs that are relative to the ``root``
 node of the API. This node serves as the head of the resource tree 
exposed through an API. In OpenAPI, the root node is identified by the ``url`` field of the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object[Server Object]. In this document the tag ``{root}`` designates the root node of a URI.

The partial URIs used to identify http://docs.opengeospatial.org/DRAFTS/19-072.html#resource-definition[Resources] in this document are refered to as the resource ``path``. The purpose of a resource ``path`` is to identify the referenced resource within the context of this standard.
 Implementors are encouraged to use these partial URIs in their 
implementations, thereby providing a common look and feel to OGC APIs.

This standard defines http://docs.opengeospatial.org/DRAFTS/19-072.html#resource-definition[Resources] which may appear in more than one place in the API. These http://docs.opengeospatial.org/DRAFTS/19-072.html#resource-type-definition[Resource Types] are identified by name rather than by URI.

**Summary for Developers:**

http://docs.opengeospatial.org/DRAFTS/19-072.html#rfc3986[RFC 3986] defines a URI in Backus-Naur Form http://docs.opengeospatial.org/DRAFTS/19-072.html#bnf-citation[(BNF)] as follows:

Backus-Naur Definition of URI

[source,java]
----
    URI = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

        hier-part     = "//" authority path-abempty
                         / path-absolute
                         / path-rootless
                         / path-empty

        authority     = [ userinfo "@" ] host [ ":" port ]

        path-abempty  = *( "/" segment )

        path-absolute = "/" [ segment-nz *( "/" segment ) ]

        path-rootless = segment-nz *( "/" segment )

        path-empty    = 0<pchar>
----

The following rules should be used when interpreting the BNF for use with this standard:

*   ``scheme`` is assumed to be ``HTTP`` or ``HTTPS``

*   ``authority`` is provided by the API developer

*   ``{root}`` designates the ``scheme``, ``authority``, and ``path`` to the root node of the API implementation.

*   only the ``path-absolute`` and ``path-rootless`` patterns are used

*   parameters passed as part of an operation are encoded in the ``query``.

*   parameters passed in HTTP headers or as cookies are out of scope for this Standard.

The following example shows a URI categorised according to RFC 3986 and OGC Web API standards.

Example URI and Components

[source,java]
----
URI     foo://example.com:8042/myapi/mydata/?name=roads#centerline
        \__/ \______________/\____________/ \_________/ \________/
          |           |            |            |           |
3986    scheme     authority     path         query      fragment
        \__________________________/\_____/\__________/
                      |                |        |
OGC                {root}             path   parameters
----

This document does not restrict the lexical space of URIs used in the API beyond the requirements of the http://docs.opengeospatial.org/DRAFTS/19-072.html#rc2616[HTTP] and http://docs.opengeospatial.org/DRAFTS/19-072.html#rc3986[URI Syntax]
 IETF RFCs. If URIs include reserved characters that are delimiters in 
the URI subcomponent, these have to be percent-encoded. See Clause 2 of http://docs.opengeospatial.org/DRAFTS/19-072.html#rfc3986[RFC 3986] for details.

|====
| Note | OGC Web API standards may include a community-defined identifier as part
 of a URI (ex. image id or feature id). Definition of the format of 
those identifiers is out of scope for these standards. Implementors 
should take care that these identifiers are properly encoded (see http://docs.opengeospatial.org/DRAFTS/19-072.html#rfc3986[RFC 3986]) in the URIs for all hosted resources.
|====
