[[architecture-section]]
== Architecture
The following "architecture" captures the core concepts which inform all OGC API Standards.

=== Datasets

Web APIs implement a Resource Oriented approach to Web-based distributed computing. A coherent set of APIs must be based on a common understanding of the resources to be shared. For OGC API Standards, those resources would be identified using an abstract concept of a geospatial dataset. Such a dataset would have the following characteristics:

*   A dataset can be a vector feature collection, a coverage/imagery, or a collection of datasets (therefore potentially a mix of any of these things)
*   A dataset has associated metadata, including some essential information:
**   Information about what type of dataset it is (vector features (and what type of vector features if limited to one type, e.g. polygons,lines, or points), coverages (values) / imagery (pixels), or sub-datasets-- more than one of those things)
**   A textual identifier (e.g. which figures in the resource path)
**   A title (short name / description)
**   Access point for the dataset (could be hosted locally or remote)
**   Geospatial & temporal extent
**   Resolution/scale
**   Units/Range/Bit-Depth/Channels/Dimensions etc. for imagery/coverages
**   A description of queryables, if applicable
*   Keywords/Tags, and longer descriptions are also a commonly useful piece of metadata information
*   Any other ISO 19115 metadata fields can also be associated with the dataset, but are nowhere near as essential to discovering and using geospatial data as those mentioned above. Metadata containing, at a minimum, those essential elements can always be retrieved in ISO 19115-based encodings and potentially other formats.

=== Processes
Processes take one or more datasets as input, add parameters, and produce one or more datasets as output. The following are examples of types of processes that can all run on a server and be invoked by a remote client application:

.	A complex process built as a container or executable, as typical of implementations of the Web Processing Service (WPS) standard
.	Process description languages such as the Web Coverage Processing Service (WCPS)
.	Pre-defined named processes such as 'vectorization', 'buffering', 'rasterization' or 'rendering of a styled map'

All of these kinds of processes could share aspects such as taking in an OGC API dataset as input and their output being usable as an OGC API dataset, for direct access and/or asynchronous delivery, and support multiple data partitioning/access mechanisms, estimates/billing elements, and so on.

=== Resource Paths

The resources exposed through implementations of OGC API Standards are accessed through standardized URL templates. These "paths" and their associated resources are described in <<dataset-paths>>. This table documents a selection of the paths and resources as of December 2022. This information will be updated as these and other OGC API Standards mature.

[#dataset-paths,reftext='{table-caption} {counter:table-num}']
.A selection of OGC Dataset Paths from OGC API Standards approved as of 2022-11-08
[width="90%",cols="6,4",options="header"]
|===
^|**Path Template** ^|**Resource**
2+^|**Common**
|/collections |Metadata describing the spatial collections available from this API.
|/collections/{collectionId} |Metadata describing the collection which has the unique identifier `{collectionId}`.
2+^|**Features**
|/collections/{collectionId} |The Feature Collection resource identified by the `{collectionId}` parameter.
|/collections/{collectionId}/items |The individual Features in a Feature Collection.
2+^|**Spatio-temporal environmental data resources**
|/collections/{collectionId} |Identifies a collection of spatio-temporal data with the unique identifier {collectionId}.
|/collections/{collectionId}/{queryType} |Identifies an Information Resource of type {queryType} associated with the {collectionId} collection.
2+^|**Tiles**
2+^|Note: A tile is associated with a resource. {resource} is a place holder for a path segment appropriate for a resource type.
|/collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol} |Feature tile representation of real-world elements at a given resolution restricted by the selected Tile Matrix Set.
|/collections/{collectionId}/tiles/{tileMatrixSetId} |A description of the TileMatrixSet identified by the {tileMatrixSetId} identifier.
|/collections/{collectionId}/tiles |An enumeration of the feature tileset list.
2+^|**Processes**
|/process |Lists the processes this API offers.
|/processes/{process-id} |Returns a detailed description of a process.
|/processes/{process-id}/jobs |Returns the running and finished jobs for a process (GET), Executes a process, i.e. creates a new job. Inputs and outputs will have to be specified in a JSON document that needs to be send in the POST body. (POST)
|/processes/{process-id}/jobs/{job-id} |Returns the status of a job of a process.
|/processes/{process-id}/jobs/{job-id}/results |Returns the result of a job of a process.

|===
